### PR TITLE
[Channel selection context menu] Neat ordering of entries.

### PR DESCRIPTION
**Pull request by RobvanderDoes**

### CODE REVIEW

**Comment by littlesat** [comment]
Most numbers already assinged were choosen via a linux standard... I would consider to keep at least the already numbered options... For the rest this looks nice ands gives a good feeling...

**Comment by RobvanderDoes** [comment]
I have no idea what the 'Linux standard' is in this respect, but feel free to take the commit aboard and enhance as desired.

**Comment by littlesat** [comment]
The keys that had already numbers, except for key 1 (parental) were based on linux standard.....

**Comment by RobvanderDoes** [comment]
So again:

> I have no idea what the 'Linux standard' is in this respect, but feel free to take the commit aboard and enhance as desired.

**Comment by RobvanderDoes** [comment]
And I really can't imagine that Linux has standards for 'use as startup service', 'Mark as dedicated 3D' etc. etc.

**Comment by littlesat** [comment]
Use as startup has no,standard... But move, copy, delete, rename has....

**Pull request merged**
