### PR TITLE
ServiceInfo.py: Add "IS_STEREO"

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by littlesat** [comment]
Why is this required... please explain more?

**Comment by eriksl** [comment]
I suggest showing the amount of channels instead, 1 .. 8.

**Comment by persianpros** [comment]
@eriksl That's a good idea so please do it :)

**Comment by littlesat** [comment]
i still do not get the real added value? Where is it used...do you have some examples?

**Comment by littlesat** [comment]
Why not.... It does not harm....

**Pull request merged**
