### PR TITLE
[t2mi] WIP: UI patches

### PR DESCRIPTION
**Pull request by Huevos**
[t2mi/ScanSetup] add SystemInfo; add t2mi_pid memory for stickyness in UI; add indent of grouped config items

This commit requires SystemInfo["has_t2mi_in_drivers"] to be added to "SystemInfo.py"

[t2mi/satfinder] Add SystemInfo; add t2mi_pid memory for stickyness in UI; add indent of grouped config items

[ServiceInfo] convert t2mi_pid value to string; Use built-in enigma default, not hard coding

### CODE REVIEW

**Comment by athoik** [comment]
I think SystemInfo["has_t2mi_in_drivers"] approach is wrong, simply because a usb tuner attached on the box will have the T2MI menu enabled.

The following is more realistic approach and it can work only on tuners that have such feature.

```
--- a/lib/python/Components/NimManager.py
+++ b/lib/python/Components/NimManager.py
@@ -593,6 +593,10 @@ class NIM(object):
                        multistream = True
                return multistream

+       def isT2MI(self):
+               # Check if t2mi feature exists using procfs due to missing FE_CAN_T2MI in DVB API
+               return os.path.exists("/proc/stb/frontend/%d/t2mi" % self.frontend_id)
+
        def supportsBlindScan(self):
                return self.supports_blind_scan
```

**Comment by athoik** [comment]
Also the last 3 commits from this pull request where cherry-picked.

**Comment by Huevos** [comment]
Yes I agree on the proc idea but wanted some sort of dummy that allowed testing.

Also what do you mean about the last 3 commits? Yes I picked them from my git but they were all merged manually due to differences.

**Comment by athoik** [comment]
From your PR several commits included, even the ones already in existing in branch.

So I manually push them on branch t2mi-development.

Please make a diff and let me know if something is missing.


Do you think it's ok to enable the is T2MI in mom manager?

**Comment by Huevos** [comment]
I don't know how the PR got in this mess. Something must have gone wrong with my repo.

I agree about using proc and NimManager. But we need a dummy for testing until we get the proc added to the drivers.

I'll go through it errors later today.

**Comment by athoik** [comment]
```
+       def isT2MI(self):
+               # Check if t2mi feature exists using procfs due to missing FE_CAN_T2MI in DVB API
+               return os.path.exists("/tmp/stb/frontend/%d/t2mi" % self.frontend_id)
+
```

Something like above will do the job! Make the file under /tmp and you are ready to test!

**Comment by athoik** [comment]
I implemented it here: https://github.com/OpenPLi/enigma2/commit/b520f758a99b815201cbeea7d29b74e0c3a41afd

Testing can go on ;)

**Comment by littlesat** [comment]
It is not clear anymore for me which t2mi related stuff I should merge????

**Comment by Huevos** [comment]
Nothing currently to merge.

**Pull request closed without merging**
