### PR TITLE
Make front LED configurable

### PR DESCRIPTION
**Pull request by persianpros**
Thanks to Hains

### CODE REVIEW

**Comment by littlesat** [comment]
Why is a restart required.... Can't we make it without restart required???

**Comment by Dima73** [comment]
Maybe this for old dreambox

**Comment by persianpros** [comment]
https://github.com/OpenPLi/enigma2/blob/develop/lib/python/Components/Renderer/FrontpanelLed.py changes won't get applied immediately so we need to restart enigma2.

**Comment by Dima73** [comment]
Need add SystemInfo requires="NumFrontpanelLEDs"

**Comment by persianpros** [comment]
And check what exactly?

**Comment by Dima73** [comment]
this https://github.com/OpenPLi/enigma2/pull/1664/commits/dfe3245d7372ad52dc4517196d41f1bda13dee7e#diff-0fdcfce87c5affad740c8fc9a087f165R215

**Comment by persianpros** [comment]
I mean check what proc file for it ...

**Comment by Dima73** [comment]
setup.xml

**Comment by littlesat** [comment]
And also something with addNotification so a restart of e2 is not mandatory when you change the config... doing it this way is not done...

**Comment by Dima73** [comment]
That's right, it's not necessary for anyone.

**Pull request closed without merging**
