### PR TITLE
Update sk.po

### PR DESCRIPTION
**Pull request by Pr0metheus2**
Slovak language update / Aktualizácia slovenského prekladu

### CODE REVIEW

**Comment by Pr0metheus2** [comment]
Hi, any problem with merging?

**Comment by littlesat** [comment]
I can't merge is.... because it is blocked for me. Did you push it to release candidate or release?

**Comment by Pr0metheus2** [comment]
I pushed it to 7.0 release. Developer branch is done, but it was not mirrored into 7.0, that's why I updated also 7.0.
What is the best way to have updated latest release?

**Comment by WanWizard** [comment]
Ideally make sure develop is up to date before the rc is created. ;-)

**Pull request merged**
