### PR TITLE
Vu Zero 4K support

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by technl** [comment]
shouldn't the new name (vu2) also been used in rc_models.cfg?

in that file the old name (vuuno4kse) is still used instead of vu2....

**Comment by persianpros** [comment]
Check all commits please, It's there ;)

**Comment by technl** [comment]
You're right, I need new glasses :)

**Comment by persianpros** [comment]
Not a big deal :) Also https://github.com/OpenPLi/openpli-oe-core/pull/361 is related ...

**Pull request merged**
