### PR TITLE
Fix typo, kB is wrong and just like MB, GB we should use KB

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by ims21** [comment]
I do not know, if you know Metric prefix SI, but kilo is always "k" and not "K"

**Comment by persianpros** [comment]
One "kilobyte" (KB) is 1024 bytes in JEDEC-standard, whereas the definition has shifted, in most contexts, to mean 1000 bytes (kB) in accordance with SI. To resolve this difference, binary prefixes (kiB) are used.

Now take a look at https://github.com/OpenPLi/enigma2/blob/develop/lib/python/Components/Converter/MovieInfo.py#L57 we're dividing it to 1024 so it's KB ;)

**Comment by ims21** [comment]
omg ...

**Comment by persianpros** [comment]
Is it wrong ?

**Comment by ims21** [comment]
all Win / Linux filemanagers using kB ... It's optically highlighting that the file is small ...

**Comment by persianpros** [comment]
But in windows I have KB :|

**Comment by littlesat** [comment]
I have no idea if I should merge this request.... because both are fine in my perspective....

**Comment by Pr0metheus2** [comment]
I prefer also kB...

**Comment by persianpros** [comment]
Still it's the right thing to do because it's 1024 not 1000

**Comment by ims21** [comment]
All know, that kilo is in binary 2 to 10 and not 10 to 3 ... 
I prefer kB, not KB...  As I saw on filesystems (Linux, W10), both using B, kB, MB

**Comment by persianpros** [comment]
But in windows 7 and server 2008 r2 I have KB not kB, If you need i can provide you some screenshots ;)

**Comment by ims21** [comment]
ubuntu, server 2012, W7, W10 ... kB  ...  It seems, it will be nationaly dependent .

... make it translatable (use KB) and who will want, - will change it in translation - in .po files

**Comment by ims21** [comment]
but then create actual .pot and po files for enigma2

**Comment by littlesat** [comment]
When it is indeed language depended we should indeed make it translatable

**Comment by ims21** [comment]
I think, it is ... because my all programs and operation systems using kB ... his KB. How is it in NL ?
If it will be translatable, then translator can choose, how he will want :-)

**Comment by Pr0metheus2** [comment]
I have also KB in Win7.

**Comment by blzr** [comment]
checked here on _some_ PC's - on all win (xp,7,8,10) running machines there is KB, regardless PL or EN locale; on ubuntu 16.04 I have KiB; kB nowhere to be found...

**Comment by Pr0metheus2** [comment]
Then, maybe we should do what is right and not what we like... :)

**Comment by persianpros** [comment]
As I said before the true form is KB when we have 1024 and KiB when we have 1000 so it's better to merge this request ;)

**Comment by blzr** [comment]
actually KiB stands for kibybyte = 1024 bytes (same as a KB - 'kilo'byte),
kB is 1000 bytes...

**Comment by persianpros** [comment]
Should I close this ?

**Comment by ims21** [comment]
i think, littlesat will merge it.

**Comment by littlesat** [comment]
When a language needs to have it in capital letters it can be arranged by translation. For now I think we should leave it as-is.... Please re-open when there are new good arguments to change it....

**Comment by persianpros** [comment]
But it's the right thing to do, Check https://github.com/OpenPLi/enigma2/pull/915#issuecomment-300740600 there is no kB :|

**Comment by blzr** [comment]
@littlesat, 
apparently you did not read above comments at all (?)
change has nothing to do with language, kB = 1000 bytes, KB (or KiB) = 1024 bytes, so for now we use wrong unit, simple as that...

**Comment by eriksl** [comment]
Seconded.

And KB is wrong anyway. "k" as in unit prefix is always written lowercase (as in "km", not "Km"), which is a bit illogical, but that's the way it is.

**Comment by eriksl** [comment]
Some of the other changes may be useful though.

**Pull request closed without merging**
