### PR TITLE
Update enigma2.bb

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by WanWizard** [comment]
Your local clone isn't up to date. Fixed a few days ago: https://github.com/OpenPLi/openpli-oe-core/commit/66b702094e52b241d5e69ea9c240600a6d9481a0

**Comment by persianpros** [comment]
It's inside "enigma2" repo not "openpli-oe-core".

**Comment by WanWizard** [comment]
Huh? Why is there a bb file in the enigma repo?

**Comment by persianpros** [comment]
For local build: https://github.com/OpenPLi/enigma2/commits/develop/enigma2.bb

**Comment by WanWizard** [comment]
Didn't know it existed, never used it.

**Comment by WanWizard** [comment]
Can't re-open it, as you already deleted the original. ;)

**Comment by WanWizard** [comment]
Applied it, with credit.

**Comment by persianpros** [comment]
:+1:

**Pull request closed without merging**
