### PR TITLE
[ConfigList] add sanity check in getCurrentValue

### PR DESCRIPTION
**Pull request by Dima73**
crash log when entering the audio selection:
File "/usr/lib/enigma2/python/Components/ConfigList.py", line 187, in getCurrentValue
IndexError: tuple index out of range
+
https://github.com/OpenPLi/enigma2/pull/3604#issuecomment-1426793855

### CODE REVIEW

**Comment by littlesat** [comment]
When do you get it?

**Comment by Dima73** [comment]
IPTV empty audioSelection

Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 57, in action
  File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 2790, in audioSelection
  File "/usr/lib/enigma2/python/StartEnigma.py", line 302, in openWithCallback
    dlg = self.open(screen, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/StartEnigma.py", line 315, in open
    self.execBegin()
  File "/usr/lib/enigma2/python/StartEnigma.py", line 233, in execBegin
    self.instantiateSummaryDialog(c)
  File "/usr/lib/enigma2/python/StartEnigma.py", line 267, in instantiateSummaryDialog
    self.summary.show()
  File "/usr/lib/enigma2/python/Screens/Screen.py", line 128, in show
  File "/usr/lib/enigma2/python/Screens/Setup.py", line 55, in addWatcher
  File "/usr/lib/enigma2/python/Screens/Setup.py", line 64, in selectionChanged
  File "/usr/lib/enigma2/python/Components/ConfigList.py", line 187, in getCurrentValue
IndexError: tuple index out of range

**Comment by Taapat** [comment]
After this https://github.com/OpenPLi/enigma2/commit/7338acbbe4b98cd631be4b62cfe655de0d6c255b we allow only one argument in config entry, so you need to check if the second argument exists before using it.

**Comment by littlesat** [comment]
Is len and > 1 really needed. Can't we simplify the sanity check? An empty list is also False

**Comment by Dima73** [comment]
I think this should have been done many years ago.

**Comment by Dima73** [comment]
See same https://github.com/OpenPLi/enigma2/pull/3604/commits/0a611f3830959a724e2567d9428f4605cb852bd0#diff-f9d00888cec8d881617939d06474477c3ebbb87d4eb07384cc5fc041fa72246eR190
This is not my whim, I showed the crash log when entering the audio selection.

**Comment by littlesat** [comment]
Why check for an empty list with Len while [] an empty list should also be False?

**Pull request merged**
