### PR TITLE
ServiceMP3 enigma2 freeze by changing audio track while paused

### PR DESCRIPTION
**Pull request by christophecvr**
When media is paused and user tried to change the used audio track
 To the next avbl track enigma2 freeze stb freezed.
 To solve this we will pass to play state,
 change the track and pause again.
 works well on dm8000 and vuduo2 no sync issues.

	modified:   lib/service/servicemp3.cpp

### CODE REVIEW

**Comment by littlesat** [comment]
For latest gstreamer or also for the 0.1?

**Comment by mx3L** [comment]
@christophecvr, @littlesat 
Sorry for jumping into this, but what about this one which I proposed in PM, which solves same issue and even fixes lost caps event?
https://gist.github.com/anonymous/55db2ce50621062bc2a6

I think it's not even a workaround just replacing order of flush and switch track.

**Comment by christophecvr** [comment]
@littlesat I did not test on 0.1 , but I'm almost shure it's ok for 1.0 and 0.1 .

This issue is not directly gstreamer related, but cause we 
- need to work async by stb no other option.
- the problem was present on 0.1 , it also never worked ok on 0.1.
- I only found this ok solution on 1.0

**Comment by christophecvr** [comment]
@mx3L 

gues I missed this pm or it most have been long ago.
Need to test it but I'm in doubt it will work however will try it out.

What I well can say strictly speaking if we would work only with video/audio. a seek flush is even not required up on change off audio track. But if working with /video/audio/subtitle its' a must.
and this for intern and extern subtitles and is also the cause off the pos - 90000 ns which was not brought in by me but by someone who worked on it long before me.

**Comment by mx3L** [comment]
@christophecvr 
Look in Sequencing servicemp3 page 4, @MastaG is using it quite a long time in his images. It works, it also solve issue when you have different audio tracks like AAC and AC3 and when you are switching between them, you will not lose caps event in sink, so audio decoder gets correct streamtype with correctly written PES packets for both audio streams.

I didn't create pull request yet, because I don't understand, why exactly it solves the problem.

**Comment by mx3L** [comment]
Here is what I wrote about patch in PM, but didn't get answer from Openpli guys @athoik and @littlesat 


> Please note that above patch was made by making assumption when dealing with missing caps event in audio sink, that something in gstreamer is dropping caps event when we first select audio track and then we drop it by flush. So I tested this assumption by first doing flushing and then change audio track. It solved the problem and it also solved the second one with deadlock. Problem is that I don't have any hard evidence to support my assumption, only that it works :).
> 
> So I'm not sure if you're willing to push it. I think both ways should work i.e. flush then change track or change track and then flush, but from a test it looks like there is only one way of doing it "right", 
> but I don't know why. I tried to debug it but didn't find where is dropping of caps event happening.
> 
> Should I create a pull request? Or do we need to find out what is the problem in gstreamer?

**Comment by christophecvr** [comment]
@mx3L 

I never have had that patch. But Yess it does solve the freeze problem and indead it's just sequencing error. After You're patch the try to flush an non existend buffer is not there anymore and then we change track. I well did only a brutal test at this time, and only on dm8000. but there is still a small new error to solve after this patch . resume does not work ok anymore. But think i just found why. That will need more serious tests and try out's tommorow.

**Comment by christophecvr** [comment]
@littlesat 

mx3l solution is also an option but ,... at this time the patch is not complete more needs to be done as it causes other isues. I think what it is but will work on it tommorow. 

So this pull request maybe removed.

And I work on the sequencing correction done by mx3L + extra correction off me.

**Comment by christophecvr** [comment]
just to let the comments actif I reopend the pull request

**Comment by christophecvr** [comment]
Think now all comments are read mx3L with some extra removal off work-arounds does it

**Pull request closed without merging**
