### PR TITLE
ServiceInfo: small optimization in ShowTransponderInformation

### PR DESCRIPTION
**Pull request by Taapat**
Avoids unnecessary function calls.
Call self.feinfo.getAll(False) only if need data from the tuner.

### CODE REVIEW

**Comment by mirakels** [comment]
I think you should credit Dima73 in the commit log for pointing in this direction in the first place. (#630)

**Comment by Taapat** [comment]
You can add this on merge.

**Comment by littlesat** [comment]
I still do not understand why this is required....  With this patch you cannot toggle anymore at all as far I can see...

**Comment by Taapat** [comment]
This is necessary because using 
`self.feinfo and self.feinfo.getAll(self.getTitle() == _("Service info - tuner setting values"))` insted of `self.feinfo.getAll(False)` is unreasonable and strange.

You are wrong if you think that it affects the toggle.
For toggle it is used self["key_blue"].text and it is not changed here.

**Pull request merged**
