### PR TITLE
update hu.po (release 6.2)

### PR DESCRIPTION
**Pull request by mcfly822**
Update + minor corrections.

### CODE REVIEW

**Comment by mcfly822** [comment]
User error, I planned to add the [second commit](https://github.com/OpenPLi/enigma2/pull/1611/commits/9acfa96f71689b4c4a650f0169a0b171950d7846) in a separate pull request.

**Comment by mcfly822** [comment]
Is this acceptable in this format or should I revert the second commit?

**Comment by WanWizard** [comment]
It is ok, I can merge them individually.

**Comment by mcfly822** [comment]
@WanWizard thank you!

**Pull request merged**
