### PR TITLE
Label.py: Detect render source errors

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by persianpros** [comment]
Also this is a safe merge: https://github.com/OpenPLi/openpli-oe-core/pull/257

**Comment by persianpros** [comment]
What ?
First you tell me change the if https://github.com/OpenPLi/enigma2/pull/993 now you close this ?

**Comment by WanWizard** [comment]
I didn't, it probably auto-closed after we had to rebuild the develop branch. And I can't re-open it as the source repo has disappeared.

**Comment by betacentauri** [comment]
It's already included:
https://github.com/OpenPLi/enigma2/commit/2c489200a210c280e456980c5dcd1bdbbedc7105

**Pull request closed without merging**
