### PR TITLE
[PositionerSetup] add checking USALS ,update skin  and new option sav…

### PR DESCRIPTION
**Pull request by Dima73**
…e index to setup

### CODE REVIEW

**Comment by littlesat** [comment]
But is position zero degrees still available... Or are we happy we (currently) do not have a satellite on that position?
I also se some code that could be coded smarter... ;) 
Could you at least revert the usals calibrarion capital line as it brakes all translations... And pump up the rvent description?

**Comment by Dima73** [comment]
My mistake:
this "USALS calibration"
new "USALS Calibration"
Sorry.

And the other new gettext is very small:
msgid "Press OK, save and exit..."
msgstr ""

msgid "Exit/OK"
msgstr ""

msgid "Current rotor position: "
msgstr ""

msgid "Select slot"
msgstr ""

msgid "Write to /tmp/positionersetup.log"
msgstr ""

msgid "Failed to write /tmp/positionersetup.log: "
msgstr ""

msgid "Positioner setup log"
msgstr ""

msgid "Open setup tuner "
msgstr ""

msgid "Yes (save index in setup tuner)"
msgstr ""

msgid "Really store at index %2d for current position?"
msgstr ""

msgid "Sorry, this tuner is in use."
msgstr "

msgid "AGC:"
msgstr ""

msgid ""
"Maybe the reason that recording is currently running. Please stop the "
"recording before trying to configure the positioner."
msgstr ""

**Comment by littlesat** [comment]
See above... sorry....

**Comment by eriksl** [comment]
So please fix the "zero"-position issue first.

**Comment by Dima73** [comment]
This https://github.com/Dima73/enigma2/commit/7805268758d3a49afe69ee764b3795ef7abff293 fix it

**Pull request merged**
