### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by persianpros**
No need to check with old GCC as you're not working on Open PLi 4 anymore.

### CODE REVIEW

**Comment by WanWizard** [comment]
@athoik, ok with you ?

**Comment by athoik** [comment]
I would prefer adding gcc-8 first.

Removing older gcc won't harm.

**Comment by persianpros** [comment]
Then you could merge this and do that later ;)
After this all checks will be faster for sure ...
You could remove "release 4" branches from enigma2 and your oe too as people are using them for clones only.

**Comment by WanWizard** [comment]
removing a branch is pointless, the commits themselfs won't disappear.

**Pull request merged**
