### PR TITLE
Get rid of getConfigListEntry()

### PR DESCRIPTION
**Pull request by Hains**
No need to check the number of arguments when they are fixed in the function call.
Assertion is disabled in OpenPLi oe-core as well.

Remain all brackets to create a tuple with the arguments. Except Autodiseqc.py since it has one argument.

### CODE REVIEW

**Comment by Hains** [comment]
PR for review

**Comment by Taapat** [comment]
Please leave the getConfigListEntry function in config for compatibility.
I think many plugins use this function.

I agree remove getConfigListEntry in enigma code, but the function should be left.

**Comment by Taapat** [comment]
In addition, why leave these many appends for list?
Create list immediately or use extend.
See how I did it in my plugin: https://github.com/Taapat/enigma2-plugin-youtube/commit/5fcea3cd920599beb8c9366fbf894f61790b8ac1

**Comment by Taapat** [comment]
And please fix invalid syntax: https://github.com/OpenPLi/enigma2/actions/runs/3919504702/jobs/6700550930#step:8:3501
https://github.com/OpenPLi/enigma2/actions/runs/3919504702/jobs/6700550930#step:8:3462

**Comment by Hains** [comment]
> In addition, why leave these many appends for list? Create list immediately or use extend. See how I did it in my plugin: [Taapat/enigma2-plugin-youtube@5fcea3c](https://github.com/Taapat/enigma2-plugin-youtube/commit/5fcea3cd920599beb8c9366fbf894f61790b8ac1)

+1
But I think better to do that in another commit.

**Comment by Taapat** [comment]
> +1
> But I think better to do that in another commit.

I agree.

**Comment by Huevos** [comment]
Do not delete the method from config.py or you are going to break every plugin.

**Comment by Hains** [comment]
https://github.com/OpenPLi/enigma2/commit/dc5413b1fd841960672871138bc6f83066932903

getConfigListEntry() not deleted.

**Pull request closed without merging**
