### PR TITLE
LT-2019-01-05

### PR DESCRIPTION
**Pull request by UrmasP**
Thx: Adga

### CODE REVIEW

**Comment by WanWizard** [comment]
Can't merge this: "This branch has conflicts that must be resolved"

**Comment by Adga52** [comment]
> Can't merge this: "This branch has conflicts that must be resolved"

What's wrong here? did not understand

**Comment by WanWizard** [comment]
I can only assume you used an old version. There were po updates earlier today.

**Comment by Adga52** [comment]
> I can only assume you used an old version. There were po updates earlier today.

Yes, this branch select old 2019-01-04. I am very sorry :)

**Pull request closed without merging**
