### PR TITLE
configure.ac check for msginit/msgmerge/msguniq/xgettext too, We need…

### PR DESCRIPTION
**Pull request by persianpros**
… these commands for pot/po creation and updating translations

### CODE REVIEW

**Comment by littlesat** [comment]
Please clarify the need...

**Comment by persianpros** [comment]
It's already in the commit : check for msginit/msgmerge/msguniq/xgettext too, We need these commands for pot/po creation and updating translations.

**Comment by Taapat** [comment]
Did you checked configure.ac, or simply copied these changes from somewhere?
All of this already is in configure.ac if you compile with the option --with-po: https://github.com/OpenPLi/enigma2/blob/master/configure.ac#L133

**Comment by persianpros** [comment]
Hmm, I think the new changes would apply without the need of --with-po am I wrong ?
And which one is better ?

**Comment by Taapat** [comment]
These tools are required only if you compile with the flag --with-po.
Why need check for them when not using them?

**Pull request closed without merging**
