### PR TITLE
timer conflict detection advanced checking

### PR DESCRIPTION
**Pull request by Dima73**
-show option"Enable timer conflict detection" only
SystemInfo["Fallback_remote_tuner"]  is True.Since this option is only for advanced users.

### CODE REVIEW

**Comment by eriksl** [comment]
Littlesat beat me to it. There are other circumstances where conflict detection may need to be disabled, so I won't accept this approach.

**Comment by Dima73** [comment]
OK.
No problems.

Question ...
I make a patch for each timer to disable conflicts check?

**Comment by eriksl** [comment]
If you want to.

**Comment by Dima73** [comment]
Standard timers and autotimers

**Comment by eriksl** [comment]
I you think it is necessary. The problem I had is solved with the global setting.

**Pull request closed without merging**
