### PR TITLE
[ClockToText] hours with one digit look much better with preceding "0"

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Review by athoik — APPROVED** [review]
I prefer this form too.

**Comment by littlesat** [comment]
Should be configurable by the skin and not always

**Comment by littlesat** [comment]
It is a question if taste.... we have it for years without the proceeding zero!

**Comment by Dima73** [comment]
Many times I was asked to fix this.

**Comment by littlesat** [comment]
Is is not a fix...

**Comment by littlesat** [comment]
Nothing was wrong... it is just meaning or tasteZzz

**Comment by littlesat** [comment]
If done make it configurable by skin attribute or config

**Comment by littlesat** [comment]
I told you before!

**Comment by NietGiftig** [comment]
> Nothing was wrong... it is just meaning or tasteZzz

That is correct,  Dima73 has indeed a better taste.

**Pull request closed without merging**
