### PR TITLE
[skin.py] PEP8, logging and comment cleanup

### PR DESCRIPTION
**Pull request by IanSav**
This change is a PEP8 code cleanup.  There should be no functional changes to the code.

Error and logging text been improved to enhance the accuracy and presentation of all error and log messages.

Comments have also been cleaned up, spell corrected and enhanced.

Again these changes should have no functional changes, yet.  The purpose of this change is to make it easier to compare and merge "skin.py" code between images.  Once this code is accepted I will start to apply other optimisations and code enhancements, these next changes will be changing code.  The purpose of these future changes will be to enhance the operation on OpenPLi and make it easier to compare differences between images.  I also hope to make more of the skin code interchangeable between images.

### CODE REVIEW

**Comment by nautilus7** [comment]
Hi, nice work.

Do you plan to make any further improvements in the logging? Currently, the biggest problem in skin.py regarding debugging is that when I make a typo in my skin.xml, like for example I type `position="10,10"size="50,40"` without leaving a space between the attributes, or I forgot the closing xml bracket (/>) I get the ["primary skin not found"](https://github.com/OpenPLi/enigma2/pull/2376/commits/06b5efed1d28b8315c9f8f59ce5ce216ea04e9a7#diff-b2a9ece706415994fb9593fe11dfdc8aR113) error in line 113. The problem is that I have NO CLUE where the actual problem is, as skin.py gives no info about it! It is a must to get the exact line number of the problem in this case.

Is it possible to add this feature?

**Comment by IanSav** [comment]
For a first pass I didn't want to change any functionality.

The error you are highlighting is found in the main "addSkin()" code during the XML parse process.  The new code change I have already coded but not yet submitted does differentiate between a skin file not being found and a parse error.  As a future enhancement I can look at seeing what information is available about the parser error.

Edit: It seems that more information may be available from the parser.  I will explore the options and try to add a more informative parsing error.

**Comment by nautilus7** [comment]
Ok, thanks. Any improvement is welcome. Regards.

**Comment by IanSav** [comment]
Okay, I think I now have XML parsing error logging done.  I am still testing the code but it is looking very promising.

Here is a sample from my OpenViX test box:
```
<122930.431> [Skin] Warning: Skin '/etc/enigma2/skin_user.xml' does not exist or is not readable!
<122930.432> [Skin] Warning: Skin '/usr/share/enigma2/skin_box.xml' does not exist or is not readable!
<122930.432> [Skin] Warning: Skin '/usr/share/enigma2/skin_second_infobar.xml' does not exist or is not readable!
<122930.434> [Skin] Skin '/usr/share/enigma2/display/skin_default/skin_display.xml' added successfully.
<122930.435> [Skin] Skin '/usr/share/enigma2/skin_subtitles.xml' added successfully.
<122930.438> [Skin] XML Parse Error: 'not well-formed (invalid token): line 7, column 36' in '/usr/share/enigma2/OverlayHD/skin.xml'
<122930.438> [Skin] XML Parse Error: '  <resolution xres="1280" yres="720"bpp="32" />'
<122930.438> [Skin] XML Parse Error: '------------------------------------^          '
<122930.438> [Skin] Error: Adding current GUI skin has failed!
<122930.439> [Skin] Current GUI skin reset to default GUI skin 'ViX-Night-HD/skin.xml'!
<122930.441> [Skin] Skin '/usr/share/enigma2/ViX-Night-HD/skin.xml' added successfully.
<122930.479> [Skin] Skin '/usr/share/enigma2/skin_default/skin.xml' added successfully.

```

**Comment by nautilus7** [comment]
That's wonderful!!!

You won't believe how many hours I've lost searching for an error somewhere in my skin code (3000 lines) in the past...

**Comment by IanSav** [comment]
When the code is submitted and accepted I would welcome your stress testing this new feature.  ;)

**Comment by nautilus7** [comment]
Yes, I am 100% sure I would trigger some skin parsing errors, even by accident. Looking forward.

**Pull request merged**
