### PR TITLE
VirtualKeyBoard.py: Fix possible BSOD + Some cleanups

### PR DESCRIPTION
**Pull request by persianpros**
And please check https://github.com/OpenPLi/enigma2/pull/915 again.

### CODE REVIEW

**Comment by ims21** [comment]
cleaning in InfoBar is nonsence ... very unclear if is all in one line. but it is only my opinion

**Comment by littlesat** [comment]
I afreed with ims and Plessers offer 4 different merge requests....

**Comment by persianpros** [comment]
It's about not using \ in imports nothing more (InfoBar.py)

**Comment by littlesat** [comment]
It's choosing between extreme long lines -or- having some "\".... a question of "taste"... so I think this is not mandatory to change.

Please offer the other 3 in a separate merge request.

**Comment by persianpros** [comment]
What about https://github.com/OpenPLi/enigma2/pull/915 ?

**Pull request closed without merging**
