### PR TITLE
Update all language po files with latest strings using

### PR DESCRIPTION
**Pull request by persianpros**
Persian Prince's enigma2-language.sh: https://github.com/PLi-metas/enigma2-language/blob/master/enigma2-language.sh

### CODE REVIEW

**Comment by littlesat** [comment]
I’m not sure if mergjng this one might break the build proces...

**Comment by persianpros** [comment]
Well it got the green check from Travis and we did this before: https://github.com/OpenPLi/enigma2/commit/aeaeb0ad489a482c7674d9fd9ee03024203bef0d

**Comment by eriksl** [comment]
It looks okay, if the processor does not mind the # style comments, I am not sure about that.

**Comment by eriksl** [comment]
Apparently it doesn't mind.

**Pull request merged**
