### PR TITLE
Directories.py: Introduce isPluginExtensionInstalled and isSystemPluginInstalled

### PR DESCRIPTION
**Pull request by persianpros**
If you read the comments here: https://github.com/openatv/enigma2/commit/384032df3d9c6ef40d6ac0fc2138d200c5c4d4dd you'll get what it does.

This will reduce the code and should be available in all e2 images so all future .py cleanups and plugin changes be compatible.

Example: https://github.com/OpenVisionE2/enigma2-openvision/commit/11559c0fa83f701f0ecf58a6142528a4ed7b5833

### CODE REVIEW

**Comment by persianpros** [comment]
https://github.com/OpenViX/enigma2/commit/b6f7ddf5d5580c3ddf634082f1ad0799f6acb553 could later be added too.

**Comment by nautilus7** [comment]
Nice, but why the naming of the functions is not consistent (_isPluginExtensionInstalled_ vs _isSystemPluginInstalled_)?

It should be both _isExtensionPluginInstalled_ and _isSystemPluginInstalled_ or something.

**Comment by persianpros** [comment]
Sorry but we're using it on Vision, ATV and ViX so no changes I guess.

**Comment by AbuBaniaz** [comment]
OpenViX have added following to cover both types: of plugin: https://github.com/OpenViX/enigma2/commit/25ec52d908e1f231e6951b0421daa0ce60cb7d0d

But that uses both the two variable sin this pull request. Hopefully this pull request can be merged so the other one can be added too. Unless persianpros wants to add it to this pull request too so both are added in one go.

**Comment by persianpros** [comment]
@AbuBaniaz I wrote about that in comment #2 ;)

**Comment by AbuBaniaz** [comment]
OpenATV have further improved it and combined the functions into one.

https://github.com/openatv/enigma2/commit/8f5d86199f57dfa330da04ccd13d3967297fbf86
https://github.com/openatv/enigma2/commit/37f8bd8df77e90a0605cb7af254a5b960f8cabda

**Comment by persianpros** [comment]
I think PLi does not want this otherwise there will be a reply after 5 days.

**Comment by nautilus7** [comment]
5 days is not that much... You can have patience.

**Comment by persianpros** [comment]
My other PR was there for 13 days.

**Comment by WanWizard** [comment]
We have a code freeze atm pending the release of 8.1.

**Pull request closed without merging**
