### PR TITLE
List.py - enhance functionality thx VTI

### PR DESCRIPTION
**Pull request by arn354**
This commit is necessary for menu_sort.
This solves also some issues with plugins which are mainly created for VTI.

### CODE REVIEW

**Comment by mx3L** [comment]
Hello,

1. How do you know how many items has one page of List? I don't think it's right to just hardcode 10 entries for one page.

2. Why don't just use self.index which is defined as property which will call setIndex, getIndex methods, instead of calling them directly? or at least for cleaner code, we shouldn't mixed them up.

3. I'm wondering, what is the reason that these plugins don't use standard List Source functions selectNext, selectPrevious, getIndex and instead create and use aliases for them like down, up and getCurrentIndex.

**Comment by RobvanderDoes** [comment]
This is (or should have been) part of this commit: https://github.com/OpenPLi/enigma2/pull/331#issuecomment-229058173.
As the latter is now in PLi and causes crashes, I suggest to merge this one as-is.
That whole new 'sort'-functionality needs cleaning up and enhancements anyway, so your suggestion could be part of that.

**Comment by arn354** [comment]
I simply took over those functions.
Why they exist in VTI and why they were used by plugins of VTI (e.g. webradiofs) - i can't answer.

a) reject (then revert the menu_sort commit too)
or
b) merge and improve

**Comment by RobvanderDoes** [comment]
LOL: webradiofs is not a VTi-plugin, but made by a rather eccentric coder. 
Remember: PLi tries 'clean coding', so it would be a good idea to enhance the lot.
But for now: please merge. And go on from there.

**Comment by RobvanderDoes** [comment]
See http://forums.openpli.org/topic/41917-new-option-sort-menu/?p=555347

**Comment by mx3L** [comment]
I think adding pageUp and pageDown is good suggestion, but aliases shouldn't be there.

This could be used as fix instead of patching List source:
https://gist.github.com/anonymous/c64e717f66777d2b5922ac44d54e0a9e

**Comment by mx3L** [comment]
I don't understand, why merge something which is not correct and not to use suggested patch which does the same thing, but without polluting List Source?

**Pull request merged**
