### PR TITLE
Add possibility to remove native key binding

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by littlesat** [comment]
Why should you need this?

**Comment by persianpros** [comment]
:( github is such pain in ... because it automatically merges new commits in last merge request and I have to wait for it to be merged or closed.
Please tell me which ones do you accept so I can send them one by one from different forks.

**Comment by littlesat** [comment]
All of this is currently a bit too much to evaluate.... It might have a big impact and it does not help to finalyse other stuff (like openpli 5)

**Comment by persianpros** [comment]
As far as I can see they are all safe to merge because cleanups are not anything new and the rest won't be used at the moment and they're  just new functions.

**Comment by littlesat** [comment]
Can you please redo these commit requests.?

And still please clarify why we should unbind key stuff?

**Pull request closed without merging**
