### PR TITLE
[skin.py] Negative coordinates are valid, and used in OpenPLi skins. …

### PR DESCRIPTION
**Pull request by Huevos**
…This code is blocking that.

### CODE REVIEW

**Comment by IanSav** [comment]
This is an odd observation as the original code has been in place for over 11 years (code added on 15-Sep-2009) and has not triggered any issues.  It could be argued that this code may be protecting the skins from erroneous calculations.

Some examples and proof of why this change is required should be provided.

**Comment by Huevos** [comment]
If you don't see the value of negative coordinates why do you use them in OverlayHD skin?

**Comment by IanSav** [comment]
Not that your response in any way addresses my comment, where do I actively use negative coordinates in OverlayHD?

My original observation still stands.  Please demonstrate that the code change is appropriate and/or corrects an issue.

**Comment by Huevos** [comment]
Ian, this code is for any time you want to partially or fully have an element outside the viewable area, just as you are using it in OverlayHD.

**Comment by IanSav** [comment]
I asked for an example where this is done and you have not provided any.

Contrary to your assertion, I do not use it in OverlayHD.  This code change is inappropriate and should be reverted.

**Comment by Huevos** [comment]
Yes you do Ian. 

Also, anyone with knowledge of html/css will understand the usefulness of negative values.

Anyway just because you don't agree is no reason to block others from benefiting from this bug being removed.

**Comment by IanSav** [comment]
Prove that I use ANY negative coordinates for any positioning or sizing.  (That will be difficult as it doesn't happen.)  This is not HTML or CSS!  You are demonstrating that you don't know how the Enigma2 skins or code works.  If you want to break OpenViX that is your call.  You should not be inflicting broken code onto OpenPLi.

I do not use any negative coordinates for any positioning or sizes.  I am suggesting this change be reverted because it is incorrect and you are yet to demonstrate that there is any problem or issue with the original code that has been in place for 11 years without ANY issues.   So far you have yet to show *any* valid skin code that uses negative values to achieve a valid purpose.

**Comment by IanSav** [comment]
If you are fixing a bug it should be easy to demonstrate the bug.  It should be equally easy to show me where I actively use negative values for any coordinates or sizes.  If you can't then reverting the change is easier.

**Comment by Huevos** [comment]
Ian, why don't you stop following me around and interfering in everything I commit?

Here is an example of negative co-ordinates in OverlayHD:
`	<screen name="HelpMenuEnigma2" title="Help" position="0,0" size="1280,720" flags="wfNoBorder">
		<widget name="rc" pixmaps="images/rc.png,images/rcold.png" position="150,110" size="154,500" alphatest="blend" transparent="0" />
		<widget name="arrowdown" pixmap="images/arrowdown.png" position="-100,-100" size="37,70" alphatest="blend" />
		<widget name="arrowdown2" pixmap="images/arrowdown.png" position="-100,-100" size="37,70" alphatest="blend" />
		<widget name="arrowup" pixmap="images/arrowup.png" position="-100,-100" size="37,70" alphatest="blend" />
		<widget name="arrowup2" pixmap="images/arrowup.png" position="-100,-100" size="37,70" alphatest="blend" />
		<widget name="list" position="400,80" size="830,500" backgroundColor="MenuBackground" backgroundColorSelected="MenuSelected" enableWrapAround="1" font="HelpFont;20" foregroundColor="MenuText" foregroundColorSelected="MenuTextSelected" itemHeight="25" scrollbarMode="showOnDemand" transparent="0" />
		<widget name="long_key" position="400,620" size="830,30" backgroundColor="TextBackground" font="HelpFont;25" foregroundColor="HelpPress" halign="right" transparent="1" />
	</screen>`

**Comment by IanSav** [comment]
I am not following you.  After all, I have always working on the UI and skins.  I should be accusing you of interfering with my efforts.  Just because you have chosen to break OpenViX doesn't mean that OpenPLi should be fair game for you commit incorrect and inappropriate changes.

I am still coding for and supporting OpenPLi.  When you make inappropriate commits I intend to spean up and defend OpenPLi from errors and bad code.

That skin segment you quoted just proves that you don't understand what the skin and code are doing.  The help screen pointer position values are not used.  They are irrational numbers to highlight that those values are NOT used.  Some sort of value is required to keep the skin syntactically correct.  The help arrow coordinates are calculated by the code and NOT by the skin.  In the new help engine code you will note that I just used 0.  The value is irrelevant, if anything perhaps I should have just used the not used character but I guessed that most people would not know what it meant.

You should understand the code before you start changing it.  You have proven by a number of your comments and code changes that you don't understand how the skins work.  This code change is an example of a change that inappropriate and wrong.  The Enigma2 positioning engine uses coordinates from 0 to the maximum value of the current resolution.  Similarly sizes are always a positive integer unless you don't want the item to display in which case 0 is the appropriate value.

You have been making a number of incorrect changes to the skin engine that proves that you do not fully grasp all the concepts and code involved.  You still haven't demonstrated that this change in code is valid or appropriate for OpenPLi  (or any version of Enigma2).

I still believe that this change should be reverted as inappropriate.

**Comment by RobvanderDoes** [comment]
IMHO github is not the place for this kind of abusive, public discussions. Why don't you discuss this on the forum instead?

**Comment by IanSav** [comment]
Sorry Rob, but this is an error that should be corrected.

**Comment by Huevos** [comment]
It is not an error. Someone created this bug years ago and this commit corrects it.

Just because you did not realize the error in the code does not make it wrong.

As usual, if you don't agree with something you have to start making personal remarks about the person making the commit without any foundation.

**Comment by Huevos** [comment]
> I intend to spean up and defend OpenPLi from errors and bad code

Anything not written by IanSav must be wrong. If you keep on the way you are OpenPLi won't have any contributors left.

**Comment by IanSav** [comment]
You got the help marker coordinates wrong.  Your proof of the error is?

As usual I comment on the code and you comment on the person.

I can't wait until you prove that objects can have a negative size.  That is what the code change now allows.

**Pull request merged**
