### PR TITLE
all po files updated from develop at 2020-11-27 15:30

### PR DESCRIPTION
**Pull request by pr2git**
Include full french translation

### CODE REVIEW

**Comment by WanWizard** [comment]
Sorry, merged the polish updates first, now this one conflicts...

**Comment by pr2git** [comment]
Please merge in the order the PR are submitted! Mine was there before the pl.po

**Comment by blzr** [comment]
and I'm just curious, why you insist on updating all po's  a g a i n ?

**Comment by pr2git** [comment]
You came from nowhere you never update the po files for OpenPLi I was doing it since years and now you want to take the job?
I have a full automated process in place I generate all the PO file translate the french one press the save button and everything is done automatically.
Why don't YOU just update the pl.po file, why YOU decide to update all the other po files?

Do I need to wait for your ask you kindly: "Please blzr now that you are interested in generating the po files can I update them or not?"

Do you want me just to generate the fr.po file

Where were you all those years when the OpenPLi translation management was nowhere?

**Pull request closed without merging**
