### PR TITLE
Support for comming Micro v2 Miraclebox

### PR DESCRIPTION
**Pull request by miraclebox-git**

### CODE REVIEW

**Comment by littlesat** [comment]
I consider not to allow this merge request... Why do we need a second TV key... ??????

**Comment by miraclebox-git** [comment]
Hmm We only add one line

7005S miraclebox2

in file

data/rc_models/rc_models.cfg 

To show proper RCU picture in Wizard. Thats all We pull request.

**Comment by littlesat** [comment]
And the key tv2 stuff?

**Comment by miraclebox-git** [comment]
You are right, that is not need at all. Just modification in rc_models.cfg.

**Comment by miraclebox-git** [comment]
As I checked pull request it is only about RCU support :) In file changes only one file change.

**Comment by littlesat** [comment]
Could you please make a new merge request to the DEVELOP branch....

**Comment by eriksl** [comment]
No need for a new PR. I will apply this PR to both branches. It's called "cherry-pick"...

**Comment by WanWizard** [comment]
@eriksl only cherry-pick 98b34133d31282454d9ed6aa4f1074d02aa40cb9, not the other two commits in this PR please.

**Comment by eriksl** [comment]
Cherry-picked into master and develop.

**Pull request closed without merging**
