### PR TITLE
[ServiceScan] fix auto scan (thanks openATV developers)

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by littlesat** [comment]
The eTimer gives me a feeling this fix is not a real fix... it is more a work-a-round.... Can you please describe more what happens and why we need a timer here?

**Comment by Dima73** [comment]
I just picked up without going into the code.
We spent a few months, but the error was not found.

**Comment by Dima73** [comment]
Please see this http://forums.openpli.org/topic/40266-general-issues/?view=findpost&p=531929

**Comment by littlesat** [comment]
I understand now what happens here... but I still have the idea it is 'driver' related... so it is still somehow a dirty work-a-round....

**Pull request merged**
