### PR TITLE
Fix ntpdate-sync crontab entry never written

### PR DESCRIPTION
**Pull request by scriptmelvin**

### CODE REVIEW

**Comment by littlesat** [comment]
Can you please describe why this exactly is needed?

**Comment by scriptmelvin** [comment]
Because `/var/spool/cron/crontabs/root` exists but is empty after a fresh flash without backup restore, so the next line that writes the crontab entry never gets executed.

**Comment by littlesat** [comment]
Good point!!! And good finding... Thanks!!!
Next time maybe also describe it in the merge request 😀

**Comment by scriptmelvin** [comment]
I described it in the forum, I thought that was enough. Will describe in next PR, thanks.

**Pull request merged**
