### PR TITLE
lt.po and fr.po update + add mk_MK.po also in Makefile.am

### PR DESCRIPTION
**Pull request by pr2git**
Probably that more changes are needed to fully support Macedonian since it is a new language in OpenPLi.

### CODE REVIEW

**Comment by persianpros** [comment]
@blzr 

Needs your attention :+1:

**Comment by pr2git** [comment]
Why do you  think that this should be watched? 
This is the same po update as I always do. Why suddenly blzr should watch the PR that I create?

**Comment by persianpros** [comment]
To help you with mk_MK.po and supporting it in related repos not watching your commit ;)

**Comment by pr2git** [comment]
Thanks for the clarification, but I already internally draw the attention of the developpers on it. So don't worry.

**Pull request merged**
