### PR TITLE
Skin.py: don't make "objecttypes" conditional

### PR DESCRIPTION
**Pull request by Huevos**
Don't make this otherwise very useful new feature conditional as doing so will severely limit its usefulness.

### CODE REVIEW

**Comment by littlesat** [comment]
Sorry I need to investigate this one... Yesterday I did not get it to work for e.g. FlashImage and Hotkey.

**Comment by littlesat** [comment]
I verified it... it cannot work... Sorry

**Comment by Huevos** [comment]
Please look at this. Works fine and does not interfere with the conditional code.

https://github.com/Huevos/enigma2/blob/df6750aa5f2dd54cbb4da0fe3415ecda272f260f/skin.py#L1057-L1061

**Comment by Huevos** [comment]
By the way your code is clearly wrong because a conditional can hold multiple conditions. And an object name will never contain a comma.

**Comment by littlesat** [comment]
But is has side effect.... it is somehow not working... time you can try a develop image ;)

**Comment by littlesat** [comment]
And you are right if I understand you... when the conditional has more then one thing te check in an or it cannot work... but first I need to fix and find the why of that site effect...

**Comment by littlesat** [comment]
One side effect is e.g. ePixmap does not have a name or source... but you need to check an object being a specific class... probably we should consider having the first parameter of the value being the key to check for...

**Comment by littlesat** [comment]
Instead of defining a new key parameter...

**Comment by littlesat** [comment]
Or even do ‘key_red=Botton,Label’ and seperate also in =...

**Comment by nautilus7** [comment]
Regarding hotkey... On this commit https://github.com/OpenPLi/enigma2/commit/5e89e8a5cd7ead533b8b6f9bab800ae14e9d0dcc, in line 344 you rename method "yellowButton" to "yellow", but in line 395, the def still remains " yellowButton.

**Comment by Huevos** [comment]
Discussion continued on OpenPLi forum.
https://forums.openpli.org/topic/56924-button-and-label-pli-opinion/page-12#entry834755

**Pull request closed without merging**
