### PR TITLE
[TimerList] add tuner number before tuner type name

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by littlesat** [comment]
Can you please describe why this is needed?

**Comment by Dima73** [comment]
> Can you please describe why this is needed?

Very convenient for those who use a complex system of tuners and a lot of recordings.
Now you will know exactly which tuner is used for which recording.

**Comment by RobvanderDoes** [comment]
Although that may change because of live-tv.

**Comment by Dima73** [comment]
Timerlist dynamic list.
Changes every time any timer state changes.

**Comment by littlesat** [comment]
For what is it needed....? for showing stuff with the recording info bar plugin or so?
I think it is a good idea to know which tuner is used for which recording. Can also be used to get OWIF better showing where tuners are used for etc....  Would also be nice to have the tuner number when something is streamed from a box....

In the patch there are also some cosmetic things observable for example " replaced by ' and visa versa. Can they be removed to keep the merge request clean for the change it does.

**Comment by littlesat** [comment]
Just a small observation to think about

And maybe also those can be 'streamlined'

return tuner_name + ("%s" % "DVB-T") + alternative

->

return ("%s %s %s" % (tuner_name, "DVB-T", alternative)).strip()

(then also for tuner_name and alternative (A) you do not need the extra space)

**Comment by Dima73** [comment]
> Just a small observation to think about
> 
> And maybe also those can be 'streamlined'
> 
> return tuner_name + ("%s" % "DVB-T") + alternative
> 
> ->
> 
> return ("%s %s %s" % (tuner_name, "DVB-T", alternative)).strip()
> 
> (then also for tuner_name and alternative (A) you do not need the extra space)

In your version, if there is tuner_name = "", then we will get an extra space.

**Comment by littlesat** [comment]
The strip will remove it. But it is ok like you did it. I have to sleep on that part. But preferably the ' to " changes could be our.

**Pull request merged**
