### PR TITLE
[CI] Possibility to disable operator profiles for CI+ module

### PR DESCRIPTION
**Pull request by Dima73**
thanks @DimitarCC

### CODE REVIEW

**Comment by WanWizard** [comment]
What does this do?

**Comment by DimitarCC** [comment]
Exactly what description says...For CI+ 1.3 modules disable operator profiles since implementation is incomplete (in enigma) and for some modules it give "error 10 " on every enigma restart.

**Comment by WanWizard** [comment]
That would require me to know what an Operator profile is... :grin:

**Comment by DimitarCC** [comment]
Its meant for TVs so module to have information about services and their operator's order and numbering. And it makes a channel list with that services in that order/numbering.
Completely  meaningless for enigma imho.

**Comment by WanWizard** [comment]
Clear.

**Pull request merged**
