### PR TITLE
decoder: use audio only on primary decoder if external pip mode not used

### PR DESCRIPTION
**Pull request by Taapat**
This should fix the audio on vuplus and possible on other receivers after swap pip.
On vuplus lacks sound while not switch to another channel.

### CODE REVIEW

**Comment by littlesat** [comment]
Apologies... me again...
Do we really need m_pip_mode? Can't we simply do:
if ((m_apid >= 0) && (m_apid < 0x1FFF) && !noaudio && (m_decoder == 0 || eConfigManager::getConfigValue("config.av.pip_mode") == "external"))

**Comment by Taapat** [comment]
I think that it is better to use the function getConfigValue only once, to set m_pip_mode on eTSMPEGDecoder start, instead using this function at each channel change.

**Comment by Taapat** [comment]
Yes, the config can be changed while the decoder is already running, but are external pip changes  working without enigma restart?

And as I understand, with the current drivers external pip do not work in et, therefore a possibility that anyone even uses this config actually does not exist.
Really therefore we should unnecessary call getConfigValue at each channel change?

**Comment by Dima73** [comment]
checked, resolved to issue solo 4k

**Comment by littlesat** [comment]
I still think we do not need m_pip_mode.... It does not make any sense... It is wrong... 
And indeed it seens with the latest already old drivers external pip is not working at all...

**Comment by Taapat** [comment]
I changed it as you offeed.
But the reason is that by looking deeper, I see that config.av.pip_mode is not set on eTSMPEGDecoder start.

**Pull request merged**
