### PR TITLE
Update fi.po translation

### PR DESCRIPTION
**Pull request by jmuuriai**
A large(ish) update to the Finnish translation after 5+ years of no updates.

Baseline update merges common strings from the OpenVIX project, which has a much better maintained Finnish translation. Additional OpenPLI specific translations by myself.

### CODE REVIEW

**Comment by WanWizard** [comment]
You can't just copy a translation file from a different project? It will not be complete, and it will add VIX specific translations to OpenPLi.

**Comment by WanWizard** [comment]
@pr2git could you check if this is mergeable?

**Comment by jmuuriai** [comment]
That is absolutely correct WanWizard. You should not do that. And I did not.

I only merged the strings from OpenVIX that had an exact match to strings in the OpenPLI translation file. This was easy using a combination of msgmerge and msgcat. The result is the first commit in this PR, which contains the original OpenPLI strings, with updated translations where one was found. Strings from VIX which did not match anything in the OpenPLI file were not copied over.

After that, the rest of the translation was business-as-usual - manual.

**Comment by pr2git** [comment]
I had a quick look into it, this seems to have been done properly. I think that you can merge it. Then I can rerun a full po generation and see how fi.po become after this.

**Comment by WanWizard** [comment]
Thanks, merged.

**Comment by jmuuriai** [comment]
Thanks @WanWizard ! Is the process of how commits move from develop onto releases documented somewhere? I'm new to this project, and was wondering whether I need to make further pull requests onto release branches, or will the commits get merged by the core members.

**Comment by WanWizard** [comment]
Commits don't move. 

Releases are made by branching off develop into rc, which is publicly tested, and when ok, it will be branched off into release (and the rc branch will be deleted).

So if develop is up to date, release will be too.

In general we don't accept PR's on release branches, with some exceptions for non-PLi-code related data, such as channel lists, picon packages, the odd 3rd-party plugin update, etc.

**Pull request merged**
