### PR TITLE
[CableScan] Add decimal point to frequencies / update skin

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by littlesat** [comment]
This oatch has an issue... The frequency in the settings is an integer and nit a float.... It does also include two changes in one....

**Comment by Dima73** [comment]
As will be right?

**Comment by littlesat** [comment]
Sorry I saw you changed fequency to frequence...  This name is nog as wished but it will work a round the setting issue, but current config is gone and autocablescan will stop working until you reconfigure. I was looking in between for a solution for that config behavior...

What about the change in the id. I do not understand the reason why?

**Comment by Dima73** [comment]
To inform the user.
Many users do not know what can be scanned without ID.

**Comment by arn354** [comment]
why delete def keyCancel(self) if it is still used in self["actions"] ?

**Comment by Dima73** [comment]
Use ConfigListScreen.keyCancel -->https://github.com/OpenPLi/enigma2/blob/53f768c987411b62eedfd105bdb9baac4be770be/lib/python/Components/ConfigList.py#L300

**Comment by littlesat** [comment]
Can you please split this one into the all networks scan patch and skin changes patch... For the frequency I'm still investigating a different solution so it does not need a rename and is backwards compatible,with the current settings...

**Pull request closed without merging**
