### PR TITLE
[servicedvb] exclude SR services from seek and pause

### PR DESCRIPTION
**Pull request by Dima73**
thanks @DimitarCC

### CODE REVIEW

**Comment by littlesat** [comment]
Why is this needed?

**Comment by Dima73** [comment]
[[Updated] Allow streams to be pausable and seekable](https://github.com/OpenViX/enigma2/commit/ef04c891a07de3bb36273ed1161e3053b3540b8a)
[[Fixed] Exclude SR services from seek and pause](https://github.com/OpenViX/enigma2/commit/2e040db07e6ec3008ada9520b3be2db3235fa43e)

**Comment by littlesat** [comment]
What are SR services?

**Comment by Dima73** [comment]
SR = Stream Relay

**Comment by littlesat** [comment]
Now it is clear thanks…

**Pull request merged**
