### PR TITLE
Update ServiceInfo.py

### PR DESCRIPTION
**Pull request by jpuigs**
Add Orbital Position according to namespace
https://devtools.openpli.org/issues/435

### CODE REVIEW

**Comment by littlesat** [comment]
Why do we need a nsOrb variable here?

**Comment by jpuigs** [comment]
fillList = fillList + nsOrb
I could do it without, yes, but as all appends to fillList  done by external functions are done with variables (sublist, tracklist), I did it as well.

**Comment by ims21** [comment]
and why not in HEX ?

**Comment by jpuigs** [comment]
Because the final result has to be decimal (º degrees), so Namespace's 4 first char. have to be converted anytime to decimal.
So I do it initally.

What's the difference between … ??
if posi == 61166  and 
if posi == EEEE

**Comment by ims21** [comment]
better readability !!!  If user see EEEE, is clear for first look, that it is DVB-T !

**Comment by jpuigs** [comment]
Yes but this value is not show on screen,so users don't see it

**Comment by pr2git** [comment]
I agree that using 0xEEEE and 0xFFFF will make the code more readable because viewing the hexa is self explanatory because sorry I don't know by heart that 0xEEEE = 61166 and it is expressed in hexa in the namespace.

The "E" (East) and "W" (West) should be defined to be translatable (if possible).

**Comment by jpuigs** [comment]
Ok. I can change it.
I'm not at home. Later this night I'll do it.
How can I edit this request ? Or do I have to do a new one ?

**Comment by jpuigs** [comment]
I close this request and open a new one.

**Pull request closed without merging**
