### PR TITLE
add "header" for Title with translation

### PR DESCRIPTION
**Pull request by Dima73**
-and gettext plugins description

### CODE REVIEW

**Comment by RobvanderDoes** [comment]
"Cutlist Editor" instead of "Cutlist editor" is a very bad idea: it is bad English and it makes the title hard to read.

**Comment by eriksl** [comment]
I agree with Rob BUT the All Caps Style is already widely in use within Enigma. Some people seem to like it.

**Comment by eriksl** [comment]
Virtual KeyBoard is even worse!

**Comment by Dima73** [comment]
I really do not know much English.
Byt...
This "Virtual KeyBoard" It has been for many years without translation.

**Comment by RobvanderDoes** [comment]
Indeed: even a worse example....

**Comment by RobvanderDoes** [comment]
A Good Moment To Improve Things?

**Comment by Dima73** [comment]
please...
My native language is russian.

**Comment by RobvanderDoes** [comment]
Sorry Dimitrij, I was not teasing you. I just wanted some attention for the use of proper texts, English and other.

**Comment by Dima73** [comment]
Rob no problem.
I just said that the bad English.
Especially his spelling.

**Comment by eriksl** [comment]
Rob, the general consensus seems to be that Most People Like Many Caps In Their Sentences. Not much I can do.

**Comment by RobvanderDoes** [comment]
OK, it was just a suggestion to make things better :(

**Pull request merged**
