### PR TITLE
Update sk.po

### PR DESCRIPTION
**Pull request by Pr0metheus2**
- small corrections

### CODE REVIEW

**Comment by littlesat** [comment]
Shouldn’t we consider to merge this one in rc?

**Comment by Pr0metheus2** [comment]
Yes

**Comment by WanWizard** [comment]
Then please close this one, and re-create the PR against rc instead of develop, so we can merge it.

**Comment by Pr0metheus2** [comment]
Ok, my mistake. Sorry

**Review by Pr0metheus2 — COMMENTED** [review]
Small corrections

**Pull request closed without merging**
