### PR TITLE
[InstantRecordings] show message in set record from channel list

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by littlesat** [comment]
Can you please give me a small description what this is doing and why?

**Comment by Dima73** [comment]
When set recording from channel list(key record in selected service) from RecordTimer start message not show.
Instead this PR -->"Recording time has been set."

**Comment by ims21** [comment]
my mistake ... :-)

**Comment by littlesat** [comment]
Do I still need to merge it....?

**Comment by ims21** [comment]
> Do I still need to merge it....?

Why not ? Merge it, pls

**Pull request merged**
