### PR TITLE
Add CRID and EPG changes

### PR DESCRIPTION
**Pull request by AbuBaniaz**
CRID by@ SimonCapewell
EPG changes by @LraiZer

### CODE REVIEW

**Comment by WanWizard** [comment]
This PR seems to have broken the EPG import plugin, XMLTV file import hangs indefinitely without importing anything (and therefore also hangs E2), and via epg.dat it generates a V7 file, which is no longer supported. 

Any one willing to have a look? This is above my "paygrade"...

**Comment by LraiZer** [comment]
Will start to look tomorrow night.

**Comment by WanWizard** [comment]
Thanks! The import issues don't seem to be related, so that leaves V8 format compatibility.

**Comment by LraiZer** [comment]
So, i guess it just need to change byte to unsigned short 0x0000 and update the text to "ENIGMA_EPG_V8" in epgdat.py for V8 format compatibilty?
```
diff --git a/src/EPGImport/epgdat.py b/src/EPGImport/epgdat.py
index 908108c..7724b07 100644
--- a/src/EPGImport/epgdat.py
+++ b/src/EPGImport/epgdat.py
@@ -157,7 +157,7 @@ class epgdat_class:
                self.s_I = struct.Struct(self.LB_ENDIAN+"I")
                self.s_II = struct.Struct(self.LB_ENDIAN+"II")
                self.s_IIII = struct.Struct(self.LB_ENDIAN+"IIII")
-               self.s_B3sBBB = struct.Struct("B3sBBB")
+               self.s_B3sHBB = struct.Struct("B3sHBB")
                self.s_3sBB = struct.Struct("3sBB")
 
        def set_endian(self,endian):
@@ -183,7 +183,7 @@ class epgdat_class:
                num_tot_desc = (len(s) + 244) // 245
                for i in range(num_tot_desc):
                        ssub = s[i*245:i*245+245]
-                       sres = self.s_B3sBBB.pack((i << 4) + (num_tot_desc-1),'eng',0x00,len(ssub)+1,0x15) + str(ssub)
+                       sres = self.s_B3sHBB.pack((i << 4) + (num_tot_desc-1),'eng',0x0000,len(ssub)+1,0x15) + str(ssub)
                        r.append((crc32_dreambox(sres,0x4e), sres))
                return r
 
@@ -276,7 +276,7 @@ class epgdat_class:
                        self.EPG_TMP_FD.close()
                        epgdat_fd=open(self.EPGDAT_FILENAME,"wb")
                        # HEADER 1
-                       pack_1=struct.pack(self.LB_ENDIAN+"I13sI",0x98765432,'ENIGMA_EPG_V7',self.EPG_HEADER1_channel_count)
+                       pack_1=struct.pack(self.LB_ENDIAN+"I13sI",0x98765432,'ENIGMA_EPG_V8',self.EPG_HEADER1_channel_count)
                        epgdat_fd.write(pack_1)
                        # write first EPG.DAT section
                        EPG_TMP_FD=open(self.EPGDAT_TMP_FILENAME,"rb")
```

**Comment by WanWizard** [comment]
You're the expert... :laughing: 

If this is it, I'll apply the diff and commit it.

**Pull request merged**
