### PR TITLE
all po files updated from develop at 2019-05-21 20:50

### PR DESCRIPTION
**Pull request by pr2git**

### CODE REVIEW

**Comment by persianpros** [comment]
If you close this PR and open a new one after https://github.com/OpenPLi/enigma2/pull/2144 that would have new strings as well.

**Comment by pr2git** [comment]
There is no conflict between each others, once your PR and mine will be accepted I will generate again the po files. Generating po is done on a (quite) regular basis.

**Comment by persianpros** [comment]
Yeah I know, just wanted not to have two same string updates right after each other ;)

**Comment by pr2git** [comment]
The all po also include the very latest french translation so would be nice to have it approuved anyway. ;-)

**Pull request merged**
