### PR TITLE
[ServiceInfo] fix when not play service

### PR DESCRIPTION
**Pull request by Dima73**
File "/usr/lib/enigma2/python/Screens/Screen.py", line 93, in execBegin

File "/usr/lib/enigma2/python/Screens/ServiceInfo.py", line 190, in
ShowServiceInformation
  File
"/usr/lib/enigma2/python/Screens/ServiceInfo.py", line 224, in
getTrackList
AttributeError: 'NoneType' object has no attribute
'getCurrentTrack'

### CODE REVIEW

**Comment by WanWizard** [comment]
Isn't it better to move it inside the "if", as that is where it is needed, and assuming NumberOfTracks is 0 if there are no tracks (so also no CurrentTrack)?

**Comment by Dima73** [comment]
I do not see the difference.

**Comment by WanWizard** [comment]
I didn't say the check should go... ;-)

**Comment by littlesat** [comment]
Dima thanks... we just touched this detail because you touched that part of code...

**Pull request merged**
