### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by persianpros**
occured -> occurred
I'm updating my Persian translation after months and it seems we have some typos ...

### CODE REVIEW

**Comment by nautilus7** [comment]
Better change the strings from this:

> Some error occurred - Please try later

to this:

> An error occurred. Please try again later.

**Comment by persianpros** [comment]
I didn't want to change the string just fix the typo ;)

**Comment by WanWizard** [comment]
I agree with @nautilus7 that if you update it, better make sure it's correct. Not a lot of effort.
There is already enough "toe-curling" English in Enigma, lets do something about it ... ;)

**Comment by persianpros** [comment]
Ok so wait for my next merge request as I have to check other files too :)

**Comment by WanWizard** [comment]
All the time in the world... :ok_hand:

**Comment by nautilus7** [comment]
@WanWizard, I though you agreed that it was better we change the strings to what I suggested above.

**Comment by persianpros** [comment]
Don't worry I'll change some strings this week as I have to check more files ;)

**Comment by nautilus7** [comment]
OK good to know, BUT since it is already committed, translators might start translating these new strings, and then they will have to do them again.

@WanWizard said

> if you update it, better make sure it's correct

and then he committed the not-so-correct version...  I'm confused.

**Comment by WanWizard** [comment]
Sorry, my mistake, wasn't paying (enough) attention. I'll commit the updates in a minute.

**Pull request merged**
