### PR TITLE
[Fastscan] inherit

### PR DESCRIPTION
**Pull request by Huevos**

### CODE REVIEW

**Comment by littlesat** [comment]
Thanks but do I see a session = ession here?

**Comment by littlesat** [comment]
Indeed a typo
ssession=ession,

**Comment by Huevos** [comment]
LOL. Sorry. Can you copy and correct and test on your machine... Please?

**Comment by littlesat** [comment]
I do not have ‘boxtime’ now…

**Comment by Huevos** [comment]
Ok... Is your save/cancel commit tested?

**Comment by littlesat** [comment]
Yes that is tested.
But I need a bit more investigation because eg in en av setup I needed the hasattr… and I want to avoid this. And in configuration it crashed on fan missing. That is why I added the try/except around the eval while adding it to the list. But this is finetuning. Now everything is canceled as it should be and saved as it should be. Another solution here is of course put them all in the list and do not show them (by flag)…. But I think that does not make the code better.

**Pull request merged**
