### PR TITLE
latest JESS patch from adenin

### PR DESCRIPTION
**Pull request by persianpros**
Also with some OE-A changes

I think you really need to review this before merging it because OE-A is messy always specially in e2 part as they don't merge with latest PLi changes

I hope this patch could help you save some time at least

### CODE REVIEW

**Comment by RobvanderDoes** [comment]
< I think you really need to review this before merging it because OE-A is messy always specially in e2 part as they don't merge with latest PLi changes >
As the name already reveals: the OE-A has nothing to do with (whatever which version of) E1/2.

**Comment by milosoftware** [comment]
What is a "JESS"?

**Comment by persianpros** [comment]
http://forums.openpli.org/topic/37669-e2-patch-for-jess-jultec-enhanced-stacking-system-en50607-support/

**Comment by littlesat** [comment]
I did overlook this patch... But this patch does not really look 'nice'.... :(

**Pull request closed without merging**
