### PR TITLE
Add new option 'use dvbapi5 statistics' for show snr/db in gui

### PR DESCRIPTION
**Pull request by Dima73**
dvbapi5 statistics  show incorrect values from sundtek/osmega/et7000/et8500
return old api

### CODE REVIEW

**Comment by littlesat** [comment]
Why do we need a config for this?

**Comment by Dima73** [comment]
Manufacturers use false values dvbapi5 statistics snr/db.

**Comment by littlesat** [comment]
They Should fix it... And to make a config of it is bad. The UI mist not be involved with this. Then make a feature of it instead.........

**Comment by Dima73** [comment]
littlesat
I do not understand what should I do?

**Comment by littlesat** [comment]
Basically wakt until xtrend solve the issue... Or add it as feature not a config....

**Comment by Dima73** [comment]
What means "add it as feature not a config"?

**Comment by littlesat** [comment]
Yep now it is a config... I think that is 'not done' when it is for specific boxes... then it should be via a SystemInfo.py (key) -or- a machine feature.

**Pull request closed without merging**
