### PR TITLE
[elistbox] Add method to calculate max list-item width for use in Mes…

### PR DESCRIPTION
**Pull request by Huevos**
…sageBox

Removes terrible "autoresize" hack in MessageBox.

Author: @DimitarCC

### CODE REVIEW

**Comment by littlesat** [comment]
Please do not close... I now postpone it in regards to the release of 9.0.

**Comment by Taapat** [comment]
This also could be used in ChoiceBox: https://github.com/OpenPLi/enigma2/blob/develop/lib/python/Screens/ChoiceBox.py#L102-L106

**Comment by Huevos** [comment]
ChoiceList is eListboxPythonMultiContent.

MenuBox is eListboxPythonStringContent.

We would need to check.

**Comment by DimitarCC** [comment]
it should work in my opinion. But have to be tested on a skin that uses it.

**Pull request merged**
