### PR TITLE
pl.po update

### PR DESCRIPTION
**Pull request by j00zek**

### CODE REVIEW

**Comment by littlesat** [comment]
Sorry I cannot read the comments as they are in polish... Can I merge it or should I wait???

**Comment by eriksl** [comment]
"hmm, I'm not entirely convinced about the 'skin' ...
generally, the name 'skin' already long been accepted in the dialect e2, I think it is more understandable and unambiguous than a 'skin';)
(btw. like I have with the term 'timer' - everyone knows what it is 'Timer', a short word fits everywhere, and suddenly openwebif appears 'work time' ...)"

**Comment by eriksl** [comment]
Apparently it boils down to translating or not of the word "skin".

**Comment by eriksl** [comment]
This does add a lot translations, so I will add it. Blzr, please contribute a patch with your insights.

**Comment by eriksl** [comment]
Applied.

**Pull request closed without merging**
