### PR TITLE
enigma2.sh improvements

### PR DESCRIPTION
**Pull request by persianpros**
Thanks to "arn354", "atvcaptain", "andyblac".

### CODE REVIEW

**Comment by WanWizard** [comment]
I'd like to know the why for all three, before merging. If needed, they all seem to be done in the wrong place. We don't do workaround like ATV, we like to fix things permanently...

**Comment by littlesat** [comment]
I also do not see the real need....???

**Comment by persianpros** [comment]
Well in my opinion "OOM score" is a nice thing to have but the rest are just workarounds for some situations.

**Comment by littlesat** [comment]
Why is that OOM score a nice thing to have?

**Pull request closed without merging**
