### PR TITLE
[Picon] add new skin attrib "usePicLoad" for use ePicLoad

### PR DESCRIPTION
**Pull request by Dima73**
Need for some box(e.g. gigablue uhd ue/quad 4k) in lcd display.
- example:
<widget source="session.CurrentService" render="Picon"
isFrontDisplayPicon="1" usePicLoad= "1" zPosition="13"
position="224,394" size="242,142" transparent="1" alphatest="blend">

<convert type="ServiceName">Reference</convert>
  </widget>

### CODE REVIEW

**Comment by littlesat** [comment]
Why do we need the function updatePicon (here)

**Comment by Dima73** [comment]
Don't know, original code https://github.com/openatv/enigma2/blob/7.0/lib/python/Components/Renderer/LcdPicon.py

**Comment by Taapat** [comment]
I have a feeling that the LcdPicon code is from old images that do not have the function setPixmapFromFile, or in which the image scale does not work.

**Comment by nautilus7** [comment]
These commits should have been merged as a squash commit.

**Pull request merged**
