### PR TITLE
Small code optimization in Movieplayer Filemanager

### PR DESCRIPTION
**Pull request by Taapat**

### CODE REVIEW

**Comment by ims21** [comment]
I think, it is in conflict , because you used old file version, imho. 
Lines "```
-		elif choice[1] == 8:
-			return
-		else:
-			return"
```
are not long time in file.

**Comment by Taapat** [comment]
There are no conflicts. See 
> This branch has no conflicts with the base branch

Check MovieSelection on git: https://github.com/OpenPLi/enigma2/blob/develop/lib/python/Screens/MovieSelection.py#L2221

elif choice[1] == 8:... is in MovieSelection now.

**Comment by ims21** [comment]
hmm, I thought, that it was removed ... my mistake ... then all my patches will be problem for merge :-(

**Comment by Taapat** [comment]
You made a pull request after me.
And the code in your pull request conflicts with my changes.

But if you are lucky more than me, and your pull request will be added before my, then I will need to change my code.

**Pull request merged**
