### PR TITLE
py files: E101 and E121 PEP8 cleanup

### PR DESCRIPTION
**Pull request by persianpros**
Indentation contains mixed spaces and tabs (E101)
Continuation line under-indented for hanging indent (E121)

### CODE REVIEW

**Comment by persianpros** [comment]
@littlesat @WanWizard @IanSav 

Done in all Open Vision repos, if you're up for it let me know to do it for all PLi repos as well.

And later for ViX, ATV and OE-A because it's the standard.

**Comment by IanSav** [comment]
I am more than happy to see all code PEP8 cleaned.

I also standardise quote marks, clean up comments and try to convert variables to camelCase.

**Comment by littlesat** [comment]
I did merge it... But it is such huge it is undoable to check for anomalies. So we might consider to revert it later when it breaks something...
I like the job is done, but it would be nicer that such kind of big topics are better coordinated... :) so we see something like this is coming

**Comment by persianpros** [comment]
@littlesat 

In OV I did this for all repos (except python 3 branches for now) and we're testing it and so far with no problem.

I say accept no more PRs and first test this if it was ok then I will send PRs for all other repos, is it ok?

I hope we could do this once for all.

**Pull request merged**
