### PR TITLE
SimpleChannelSelection - added epg button for select channel too

### PR DESCRIPTION
**Pull request by ims21**

### CODE REVIEW

**Comment by WanWizard** [comment]
@ims21 for the release notes: what exactly does this do?

**Comment by ims21** [comment]
> @ims21 for the release notes: what exactly does this do?

You’re asking me after more than 11 months? What did you have for lunch back then? :-)
It must have made sense at the time, but today I can’t tell you why, especially after so many changes (e2 or some plugin). I’ll take a look at it. 

Is there some problem with it?

**Comment by ims21** [comment]
Found it:  it solve [this](https://forums.openpli.org/topic/16424-some-questions-bugs/page-368#entry1660763)

**Comment by WanWizard** [comment]
It came up as a question when the 9.2 release notes were made, the question was simply "what does this do" so it can be explained to users, if needed. Thats all.

**Comment by ims21** [comment]
Alright. I tried commenting it out, and it really still fixes the issue described in the link. So - bug fix.

**Comment by WanWizard** [comment]
I am clueless what you are doing now. 

All I asked was to explain what this change meant in user terms? i.e. "what does this change for the user"?

**Comment by ims21** [comment]
Sorry, I didn’t mean to upset anyone. It does:
"Fixed a bug where, after selecting Single EPG from the channel list and then using the CH+/- (Bouq+/-) buttons to return back to the channel list, it was no longer possible to open the EPG again without closing and reopening the channel list."

**Comment by WanWizard** [comment]
Yes, I understand that now, I've added a text to that effect to the release notes.

**Pull request merged**
