### PR TITLE
[About] not visible  fp_version is zero

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by WanWizard** [comment]
If I look at getFPVersion(), it returns None if all lookups fail, or the value of the succeeded lookup.

In which cases is 0 not a valid value?

**Comment by Dima73** [comment]
Front processor this is for very old DM/VU+ receivers.

**Comment by WanWizard** [comment]
I get that, but it doesn't answer the question?

Which box returns 0 instead of None, and why is that a problem?

**Comment by Dima73** [comment]
0 is default answer, but 99% of receivers simply don't support front processor updates.
What's the point of showing it?

**Comment by WanWizard** [comment]
If I look at https://github.com/OpenPLi/enigma2/blob/develop/lib/python/Tools/StbHardware.py#L7, the default is clearly `None`, and not `0`. 

You can only get `0` if one of the nodes exist and returns it.

**Comment by Dima73** [comment]
Yes, this node is there, but it is a vestige(rudiment) if the value is 0.

**Comment by WanWizard** [comment]
Odd, it is a dummy you say? Which box is that?

**Comment by Dima73** [comment]
gbquad4k login: root
root@gbquad4k:~# cat /proc/stb/fp/version
0

same vu+solo4k

**Comment by Dima73** [comment]
lunix3-4k login: root
root@lunix3-4k:~# cat /proc/stb/fp/version
cat: can't open '/proc/stb/fp/version': No such file or directory
root@lunix3-4k:~# cat /dev/dbox/fp0
^C
root@lunix3-4k:~# pythin
-sh: pythin: command not found
root@lunix3-4k:~# python
Python 2.7.18 (default, Aug  4 2021, 02:29:18)
[GCC 9.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from fcntl import ioctl
>>> fp = open("/dev/dbox/fp0")
>>> ioctl(fp.fileno(), 0)
0
>>>

**Comment by WanWizard** [comment]
Great, more Dags crap... :angry:

**Pull request merged**
