### PR TITLE
fix typo in Makefile.inc regarding LIBSDL_CFLAGS

### PR DESCRIPTION
**Pull request by technic**
This is a minor commit, but SDL still doesn't work because of enigma2 changes in gMainDC interface.
can we setup travis-ci to build with different configurations? (-with/without-sdl)

### CODE REVIEW

**Comment by technic** [comment]
pushed one more commit to make it compile without errors.

**Comment by athoik** [comment]
Those changes look safe. Anyone against merging?

**Comment by WanWizard** [comment]
I don't have the skills to comment. ;)

**Comment by technic** [comment]
This changes doesn't concern any code that is built for stb binary. So
indeed they are safe :)

**Pull request merged**
