### PR TITLE
[TuneTest] remove wrong value pidsFailed

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by littlesat** [comment]
Why not merging this in py3 branch?

**Comment by persianpros** [comment]
What's the origin of this commit?

https://github.com/openatv/enigma2/commit/96f86d19a0efb1900a5a382ca3700cca36eef670

or

https://github.com/OpenViX/enigma2/commit/91ee9c2385305354bbbaed5324853a3ae2b03e23

?

**Comment by Dima73** [comment]
Don't know.
The discussion went on in parallel.

**Comment by WanWizard** [comment]
Is this relevant for 8.3-release? And is it applied to python3?

**Comment by Dima73** [comment]
> Is this relevant for 8.3-release? And is it applied to python3?
yes

**Comment by WanWizard** [comment]
yes to both questions?

**Comment by Dima73** [comment]
applied to python3/8.3-release

**Pull request closed without merging**
