### PR TITLE
Update po files using updateallpo-multiOS.sh

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by littlesat** [comment]
When I verify the Dutch (NL) translation it is wrong...???

**Comment by WanWizard** [comment]
I don't see any added translations in here, just a regeneration of the po files?

**Comment by persianpros** [comment]
It's automatic procedure and I didn't touch it by hand ...

**Comment by WanWizard** [comment]
Why was it closed?

**Comment by persianpros** [comment]
I thought you don't want it and it has problems.

**Comment by WanWizard** [comment]
I don't, I just asked @littlesat what his problem is...

**Pull request closed without merging**
