### PR TITLE
Audio codec description replace one standard

### PR DESCRIPTION
**Pull request by Dima73**
-stream services return completely different audio codec, it is necessary to centralize this audio codec

thanks @original-birdman

### CODE REVIEW

**Comment by Taapat** [comment]
1. Why create _acedits as a global variable if it is only used in the StdAudioDesc function? I think it would be correct to place it in the in function where we use it, and not to create unnecessary global variables.
2. Maybe I'm missing something, but description should be the name of the codec.
Why is a loop through a tuple needed to replace the description at all? Why not create a dictionary and set the name directly without a loop?
3. After description.split()[0] you check if it is not "WMA Pro".
How can it consist of two words if split will divide it?

**Comment by original-birdman** [comment]
> 1. Why create _acedits as a global variable if it is only used in the StdAudioDesc function? 

So that it is created once, not every time the function is called.

>     2. Maybe I'm missing something, but description should be the name of the codec.

What you are missing is that this was taken from an OpenVix PR, where there were 4 long strings of **identical** replace()s all in a single-statement. All this did was centralize/rationalize code which _already_ existed there.

>        Why is a loop through a tuple needed to replace the description at all? Why not create a dictionary and set the name directly without a loop?

Multiple replace()s can occur in one description.

**Comment by Taapat** [comment]
> So that it is created once, not every time the function is called.

And it stays in memory forever. Why don't we define all variables globally so that they are only created once?


> What you are missing is that this was taken from an OpenVix

But this is not a PR in OpenVix. 4 long strings of identical replaces do not exist here.
In OpenVix it has come from openatv. In my opinion, on openatv this replace is in the correct place - in servicemp3.
Why get the description from one place in servicemp3 and change it ater in python code in several places?

**Comment by original-birdman** [comment]
> And it stays in memory forever. Why don't we define all variables globally so that they are only created once?

It would need to be in memory to create it locally. It doesn't get magicked out of thin air.
Yes, it is now a global name (hence the starting "_"), but unless you import it you won't have a clash.

**Comment by original-birdman** [comment]
> But this is not a PR in OpenVix. 

It is as far as my involvement goes. and where it originated. And hence why I'm getting message about it.

**Comment by Ev0-BH** [comment]
> But this is not a PR in OpenVix. 4 long strings of identical replaces do not exist here. In OpenVix it has come from openatv. In my opinion, on openatv this replace is in the correct place - in servicemp3. Why get the description from one place in servicemp3 and change it ater in python code in several places?

The original code was in the 4 python files, which I updated in OpenBh and was pushed to OpenVix, then OpenAtv merged it and then ported it to servicemp3, however that does not work properly as every media player gives a different name for a codec, so you need to patch serviceapp too, but again it still did not work properly (in OpenBh atleast), so it was reverted and then updated in the 4 python files again.

original-birdman has just cleaned up 4 files and put all the codec replaces into 1 file to make it nice and simple and then created a PR for OpenPLi, implement it however you want, either in python or in c++.

**Comment by Dima73** [comment]
My test...
This replace work fine in serviceapp/servicemp3 for OpenPLi.


I’m also tired of these incomprehensible names of codecs from streaming services, now everything is as it should be.

**Comment by Dima73** [comment]
`So that it is created once, not every time the function is called.`

Converter ServiceInfo сalled after each zap.
And there it is constantly checked "IsMultichannel"(standard OpenPLi skins).

**Comment by Taapat** [comment]
As I understand this only affects streaming.
So ,I don't see a problem to add it also in serviceapp if needed.
Ok, in addition to that, it will also be needed in servicehisilicon and then we can discuss whether it should be placed in python or not.

I assume that the name of the codec does not depend on the media player, as you write, but on the streaming service.
Why you want to convert something when the streaming service has specified a codec based on their own considerations or standards?
Are all the necessary replace variants here? Maybe you need more, but maybe you need less?
As far as I can observe in the commit history, all changes have been made without specific examples what needs to be replaced and why.

**Comment by Taapat** [comment]
@Ev0-BH and how can you comment on this: https://github.com/openatv/enigma2/commit/1891f68cf79c19f55c3f79471f3c5ecd50cc02b6
I understand that all the replaces offered here are not needed?

**Comment by Ev0-BH** [comment]
> @Ev0-BH and how can you comment on this: [openatv/enigma2@1891f68](https://github.com/openatv/enigma2/commit/1891f68cf79c19f55c3f79471f3c5ecd50cc02b6) I understand that all the replaces offered here are not needed?

Not sure what you are calling me out on ?

As I said above, after OpenAtv merged the python changes, they then converted it to C++ in servicemp3 and serviceapp, but it did not work well in OpenBh, I made some changes that improved things (which is what the commit above is that OpenAtv also merged), but ultimately it was reverted in OpenBh and OpenVix and we went back to the replaces in python.

**Pull request closed without merging**
