### PR TITLE
Cleanup python files #1

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by littlesat** [comment]
Are you sure the source.close() is required in keymapparser?
In e2reactor.py I would consider to indent the two error..... lines.
is 
class AFTEREVENT:
 +	def __init__(self):
 +		pass
 +
really required (was simply pass not sufficiant)?

**Comment by persianpros** [comment]
Yes we have to close the files otherwise for some STBs specially the ones with low flash it wil end up in I/O errors because too many files are open.
When we can close it right after we're done with it why not just do it ? This way we can be sure about it not hope for it to be closed.
About "def __init__(self)" read this : http://stackoverflow.com/questions/625083/python-init-and-self-what-do-they-do

**Comment by littlesat** [comment]
This is not requiredd at all...

**Comment by littlesat** [comment]
That is not requried at all...

**Pull request closed without merging**
