### PR TITLE
Fix translation in VirtualKeyBoard

### PR DESCRIPTION
**Pull request by Taapat**
You cannot translate a variable because in this case you can create a translated phrase when generating translation files and these words are removed from the translation files.

### CODE REVIEW

**Comment by IanSav** [comment]
This change breaks translations of user defined buttons.

**Comment by Taapat** [comment]
And in what buttons need translation?

**Comment by Taapat** [comment]
And how this translation is parsed on po file generation?

**Comment by IanSav** [comment]
Text string translations have been changed in the next version of VirtualKeyBoard.  It will now be a requirement that ALL text strings for use as text buttons must now be individually translated.  This should address the concern / issue of translation string harvesting.

The documentation will be updated with this new requirement.

**Comment by littlesat** [comment]
Hopefully all included in #2101

**Comment by IanSav** [comment]
If there are still any issues please report the details in the appropriate forum thread.

**Pull request closed without merging**
