### PR TITLE
[About] crashlog - add folder /tmp/enigma2_crash.log for search

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by littlesat** [comment]
As far I know not required as the crashlog is not written in /tmp.....?

**Comment by Dima73** [comment]
https://github.com/OpenPLi/enigma2/search?utf8=%E2%9C%93&q=%2Ftmp%2Fenigma2_crash.log

**Comment by littlesat** [comment]
And when do you think this might happen?

**Comment by Dima73** [comment]
Maybe directory /home/root does not exist or read-only...

**Pull request merged**
