### PR TITLE
Components Language: add os.environ["LANGUAGE"]

### PR DESCRIPTION
**Pull request by Dima73**
-it solves a strange problem with the installation of the native language
for some plugins, e.g. PartnerBox

### CODE REVIEW

**Comment by littlesat** [comment]
And what about the utf8????

**Comment by Dima73** [comment]
I'm sorry, I did not understand.

**Comment by Dima73** [comment]
https://github.com/OpenPLi/enigma2-plugins/commit/f9ba4297c3fb3a0d8c6859068159d602ab70a228

**Comment by eriksl** [comment]
Dimitrij, as we are using UTF-8 on enigma2, there is no need to select encodings. Just make sure all other encodings are converted to UTF-8, that is the real solution.

**Pull request closed without merging**
