### PR TITLE
Add converter VfdDisplay

### PR DESCRIPTION
**Pull request by Taapat**
This adds converter that you can use in skin_text.xml for 7 segment vfd displays.

By default you can use:
<widget source=session.CurrentService render=Label position=0,0 size=1,1>
    <convert type=VfdDisplay></convert>
</widget>
This show service number after the channel switching, and after 5 seconds show the clock.

Possible attributes:
  Number - show channel number
  Clock - show clock
  12h or 12H - show the clock in 12 hour format
  Noblink - do not show a blinking : between the digits (probably not supported by display)
  Nozero - do not show a zero before the channel number and the clock (64 instead of 0064)
  Loop - constantly change the channel number and the clock
  digit (2) - delay time in seconds (default 5)

Examples;
  Show only channel number:
    <convert type=VfdDisplay>Number</convert>
  Show only clock:
    <convert type=VfdDisplay>Clock</convert>
  Show channel number and after 10 seconds clock:
    <convert type=VfdDisplay>10</convert>
  Loop channel number and clock:
    <convert type=VfdDisplay>Loop</convert>
  Loop channel number and clock, dealy 10 seconds, do not show a zero before:
    <convert type=VfdDisplay>Loop;10;Nozero</convert>

### CODE REVIEW

**Comment by littlesat** [comment]
if '12h' in self.type or '12H' in self.type:
-> if '12h' in self.type.lower():

**Comment by Taapat** [comment]
self.type is list, so therefore can not be used lower()

if ... else It works much faster than and, and therefore I chose them.
If you can justify why the and is better (although it working slowly) I can change it.

**Comment by Taapat** [comment]
About the first point. I think something like this before, but I do not know why, but I suddenly found a solution only after your comment. Thank you for your initiative.

The second I disagree with you, but you're the boss.

**Comment by Dima73** [comment]
if /else one line...
What for?
Who needs it?
It is being implemented in all of the code of Enigma.
It is very difficult to read and understand.

**Comment by littlesat** [comment]
Does it work now or does it as it also required a display_txt.xml

**Comment by littlesat** [comment]
It is not diffucult to read it is so standaard python

**Comment by Taapat** [comment]
It also required a skin_text.xml.

This is an independent converter that can be used in skin_text.xml or in any other skin which
introduce the same functionality as in the plugin VfdDisplay.
Without this converter can not make changes in the skin.
Therefore, I want to add their first so after that I could point to these changes.

Speaking about zgemma h3. First need to remove the plugin VfdDisplay from the image so that not conflict with skin_text.xml.
I've created a pull request, but it looks like that zgemma do not pay attention to it: https://github.com/zgemma-star/meta-zgemma/pull/6

After the update in zgemma bsp I can change skin_text.xml for zgemma h3 to use this converter.

**Comment by Dima73** [comment]
This converter for the future.
All right.
Please apply this patch.

**Comment by littlesat** [comment]
OK for the 'players'....

**Comment by zgemma-star** [comment]
with this solution the skin_text.xml should been build against the 7segment display option.
There should come a generic solution (Machine-feature) and so that not all boxes should been add manual with it's own skin_text.xml

**Comment by Taapat** [comment]
I agree. It would be better to use 7segment display option.

**Pull request merged**
