### PR TITLE
Add menu_sort - thx vti

### PR DESCRIPTION
**Pull request by arn354**
1.) Set config.usage.menu_sort_mode to "user"
2.) Stay in menu tree
3.) Press Blue => Edit mode on
3.1) Select menu entry to edit or hide
3.2.1) Press Green to activate "Move mode", move menu entry to desired position and press Green again to exit "Move mode".
3.2.2) Press Yellow to hide/unhide selected menu entry
3.3) Press Blue to switch Edit mode off

Might be a good idea to add a additionel %Edit Screen to show colorbuttons once Editmode is enabled

### CODE REVIEW

**Comment by littlesat** [comment]
First there are good idea's around this patch.... but...

Why not simply change the order by the < > just like we do with the blue button menu/hotkey instead of going to a move mode...?

But I understand this is a free offer... beside some cleanups it looks nice and I think this might be a wish of many users.... 

Hopefully you will consider some improvements later....

**Comment by arn354** [comment]
i just ported from VTI as is. It is improvable (like you mentionend getting more in line with Pluginsort) - but it works as a first step.

My commit description was also misleading, sorry:
2.) Stay in menu tree
That's actually wrong.

2.) Leave Menu and re-open it
You have to initialize menu tree new, before you can enable Move mode.

**Comment by RobvanderDoes** [comment]
1- Alphabetical anly seems to apply to the main menu, not to the sub-menu's. While the latter are the interesting ones to sort.
2- When re-opening the main-menu (after setting to 'user') and trying to enable move-mode, E2 crashes:
```
<   391.807> Traceback (most recent call last):
<   391.807>   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 46, in action
<   391.810>   File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 133, in save
<   391.811>   File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 137, in run
<   391.811>   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/CrossEPG/plugin.py", line 21, in call_downloader
<   391.812>     crossepg_main.downloader(session)
<   391.813>   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/CrossEPG/crossepg_main.py", line 20, in downloader
<   391.814>     CrossEPG_Auto.instance.lock = True
<   391.816> AttributeError: 'NoneType' object has no attribute 'lock'
```

**Comment by arn354** [comment]
alphabetical ordering works here for any submenu.
I switched config.usage.menu_sort_mode to a_z,
saved, 
closed menu completely and reopened it. All menu's (including submenus e.g. osd, network, ...) are sorted alphabetical.

**Comment by RobvanderDoes** [comment]
And no crash on 'user' and trying to move? Then you have a different box/setup/xxx.

I forgot to say: I tested on today's PLi on Ultimo.

**Comment by RobvanderDoes** [comment]
I keep getting crashes, even on only opening the main menu. I had to delete 'config.usage.menu_sort_mode=user' from the settings file to recover the box.

```
<  5743.969> loading mainmenu XML...

<  5744.121> warning, skin is missing element blue in <class 'Screens.Menu.MainMenu'>

<  5744.123> warning, skin is missing element green in <class 'Screens.Menu.MainMenu'>
<  5744.125> warning, skin is missing element yellow in <class 'Screens.Menu.MainMenu'>

<  5745.652> action ->  WizardActions up
<  5745.653> Traceback (most recent call last):
<  5745.653>   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 46, in action

<  5745.654>   File "/usr/lib/enigma2/python/Screens/Menu.py", line 417, in keyUp
<  5745.655> AttributeError: 'List' object has no attribute 'getSelectedIndex'

Killed
root@vuultimo:~# 
```

**Comment by RobvanderDoes** [comment]
Using 'alphabetic' sub menu's (like 'A/V-settings', 'Customize' etc etc) are still sorted by default. And especially these are the ones that would need sorting.

**Comment by RobvanderDoes** [comment]
It's 'key up' and 'key down' in main menu that cause the crash:
```
<  6272.398> action ->  InfobarMenuActions mainMenu

<  6272.399> loading mainmenu XML...

<  6272.538> warning, skin is missing element blue in <class 'Screens.Menu.MainMenu'>

<  6272.540> warning, skin is missing element green in <class 'Screens.Menu.MainMenu'>
<  6272.542> warning, skin is missing element yellow in <class 'Screens.Menu.MainMenu'>

<  6273.958> action ->  WizardActions down

<  6273.959> Traceback (most recent call last):
<  6273.959>   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 46, in action
<  6273.960>   File "/usr/lib/enigma2/python/Screens/Menu.py", line 411, in keyDown
<  6273.961> AttributeError: 'List' object has no attribute 'getSelectedIndex'

Killed
root@vuultimo:~# 
```

**Comment by arn354** [comment]
found it - sorry missed a change. will create pull request.

**Comment by arn354** [comment]
https://github.com/OpenPLi/enigma2/pull/332/commits/7d369fb1fb1d5f6d2d554aa4f38c249d397f6f42
This solves also issues with some plugins developed by vti users.

**Comment by RobvanderDoes** [comment]
Thanks, that fixed it.
Albeit rather primitive, at last an option to sort some of the menu's.

And... accidentally hiding 'System' is a PitA .....

**Comment by RobvanderDoes** [comment]
It is not clear to me how to un-hide an entry, as one cannot select it (apart from manually changing the entry in the settings-file that is).

**Comment by arn354** [comment]
unhide :
Blue (then all menu entries appear)
Select the menu entry and hit Yellow (unhide).
Blue (disable Move/Hide mode)

as said a screen which shows the colobuttons and according texts would be helpful.

**Comment by RobvanderDoes** [comment]
A pity https://github.com/OpenPLi/enigma2/pull/332/commits/7d369fb1fb1d5f6d2d554aa4f38c249d397f6f42 hasn't been merged; now today's PLi is hampered with the crashes I reported and that could have been fixed :(

**Pull request merged**
