### PR TITLE
[ChannelSelection] title - add "User - bouquets (TV)" to lokalize

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by Taapat** [comment]
I think it is not right.
And how about user radio bouquets?

I think that first of all need to correct removeModeStr.
Remove anymore unused translations from (TV) and (Radio).
And then create the conditions only for Bouquets or User - bouquets.
Or maybe we can use simply:
`if 'bouquets' in str.upper():`

**Comment by littlesat** [comment]
I suggest it should be tolower this eay... ;)

**Comment by Taapat** [comment]
Yes of course, str.upper(), sorry :(.

**Comment by Taapat** [comment]
Maybe I miss something, but if we use the if 'bouquets' in str.lower(), then removeModeStr is not necessary and we can remove this function.

**Pull request merged**
