### PR TITLE
[UsageConfig] rename 'None' as 'No'

### PR DESCRIPTION
**Pull request by Dima73**
-remove twice entry config.usage.record_indicator_mode

### CODE REVIEW

**Comment by littlesat** [comment]
Why the replace None by No? And why default 3? For those who want tot get recordings highlighted can set it?

**Comment by Dima73** [comment]
> Why the replace None by No? And why default 3? For those who want tot get recordings highlighted can set it?

What is None?
What is the meaning of programming language (Python, C+)?

default 3...
It was like this before, it's not my decision:
https://github.com/OpenPLi/enigma2/blob/develop/lib/python/Components/UsageConfig.py#L47

**Comment by littlesat** [comment]
I do not see any reason to change None to No here. None is in English also the same for show None... Nothing... Then No is also doubtful. Maybe better discuss this before on the forum then doing a direct merge request. Also for the default of the red letters for recordings in the channel selection screen. When was that changed to from '3' to '0'?

**Comment by Ev0-BH** [comment]
> I do not see any reason to change None to No here. None is in English also the same for show None... Nothing... Then No is also doubtful. Maybe better discuss this before on the forum then doing a direct merge request. Also for the default of the red letters for recordings in the channel selection screen. When was that changed to from '3' to '0'?

Totally up to you want you want the options to say (it's your image).

But....

The question on the screen is asking "Do you want to show" ....

So the reply to that in correct English would be No not None

**Comment by WanWizard** [comment]
Agreed.

Same with the others, they are all questions where "No" is the answer, not "None" (which would be correct for countable items, for 0 or the absence of a value).

**Comment by WanWizard** [comment]
And while we're at it, can we also have a discussion about the use of ucfirst/title?

Nothing annoys me more than seeing "Yes" and "yes" or "No" and "no" in the same list. Can we standardize on either all UC first, or none of them, but not some?

**Comment by WanWizard** [comment]
> When was that changed to from '3' to '0'?

@DimitarCC changed it, two weeks ago: https://github.com/OpenPLi/enigma2/commit/c9be99cf32ae9ad05bd6f09a73cccf6d47cb033d

**Comment by littlesat** [comment]
I think that was by accident...
Should we accept this merge request for now?

**Comment by DimitarCC** [comment]
This seems to be merging issue since that was duplicated. The default is different in oe-a for where the originally code was made for. But now i am confused which have to be the default value.

**Comment by littlesat** [comment]
Sounds we had red letters 😉

**Comment by WanWizard** [comment]
It most have changed multiple times, as it was 0 is OpenPLi 7.x and 8.x.. So that seems to be correct.

But the other part of this PR, the "None to No", must be merged, so that requires a new PR, as merging is all or nothing.

**Comment by WanWizard** [comment]
The problem now is that the line is there twice: https://github.com/OpenPLi/enigma2/blob/develop/lib/python/Components/UsageConfig.py#L46-L47

So the one with default=3 just needs removing.

**Review by Dima73 — COMMENTED** [review]
this not need

**Pull request closed without merging**
