### PR TITLE
SK lang update (sk.po)

### PR DESCRIPTION
**Pull request by Pr0metheus2**

### CODE REVIEW

**Comment by littlesat** [comment]
Please request the merge to the develop branch....

**Comment by Pr0metheus2** [comment]
How can I do that? Please explain...

**Comment by littlesat** [comment]
By pushing a new merge request on the DEVELOP branch (now default).

**Comment by Pr0metheus2** [comment]
OK, so you want me to do the same again, if I am correct. I will push again. Thanks.

**Pull request closed without merging**
