### PR TITLE
[Ci] add sanity check '/proc/stb/tsmux/ci0_tsclk_choices'

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by littlesat** [comment]
Why is this sanity check needed?

**Comment by ims21** [comment]
due [this](https://forums.openpli.org/topic/95812-gigablue-quad-4k-doesnt-start-up/#entry1558184) ?

**Comment by littlesat** [comment]
Please mention it in the merge request, so it is documented. I do not have a glass magic sphere that tells me why 😉
But unless this still strange that the proc does not exist. As far I know this should not happen? So there should be more behind it....  so it could still be killing the symptom for me...

**Comment by jbleyel** [comment]
I have no access to the forum link.
What exactly is the issue?

What's wrong here?
```
for cislot in range(0, SystemInfo["CommonInterface"]):
	SystemInfo["CI%dSupportsHighBitrates" % cislot] = fileCheck("/proc/stb/tsmux/ci%d_tsclk" % cislot)

```

**Comment by ims21** [comment]
> I have no access to the forum link. What exactly is the issue?
> 
> What's wrong here?
> 
> ```
> for cislot in range(0, SystemInfo["CommonInterface"]):
> 	SystemInfo["CI%dSupportsHighBitrates" % cislot] = fileCheck("/proc/stb/tsmux/ci%d_tsclk" % cislot)
> ```
for one user enagma crashed on start:
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/StartEnigma.py", line 597, in <module>
    Screens.Ci.InitCiConfig()
  File "/usr/lib/enigma2/python/Screens/Ci.py", line 50, in InitCiConfig
FileNotFoundError: [Errno 2] No such file or directory: '/proc/stb/tsmux/ci0_tsclk_choices'

**Comment by WanWizard** [comment]
Gigablue Quad 4K doesn't have "/proc/stb/tsmux/ci0_tsclk_choices'"

**Pull request merged**
