### PR TITLE
Signal slots library and usage update

### PR DESCRIPTION
**Pull request by stevenhoving**
Draft pull request for signal and slots library update. Not ready for merge (yet).

### CODE REVIEW

**Comment by littlesat** [comment]
Travis ci build failed...???

**Comment by stevenhoving** [comment]
@littlesat working on it...

**Comment by littlesat** [comment]
Thanks

**Comment by stevenhoving** [comment]
I obviously wasn't thinking about the c++ standard requirements of the signals/slots library.  It seems it requires c++14. And our lowest gcc version has partial supports for it.
A bit disappointing, I think I will close this pr.

**Comment by littlesat** [comment]
Sjoot....

**Pull request closed without merging**
