### PR TITLE
GMEPG - increased upper limit for event font size to 32px

### PR DESCRIPTION
**Pull request by ims21**

### CODE REVIEW

**Comment by littlesat** [comment]
Why that big? I do not see any reason why????

**Comment by littlesat** [comment]
It is a relative enlargement to what the skin is given.... So I really do not see any reason to do it like this...

**Comment by ims21** [comment]
Do you think, that I did not try it ?  Interesting, that you made  permanently in FullNight skin this size to 26px (and user cannot configure it in menu GMEPG more... )

You can set different number of rows => you  can to want bigger text ...

**Comment by ims21** [comment]
ok, "px" is wrong, but 32 is ok.

**Pull request closed without merging**
