### PR TITLE
Fixed default (emergency) skin not showing

### PR DESCRIPTION
**Pull request by nautilus7**
Apparently just loading "/usr/share/enigma2/skin_default.xml" is not enough. The "/usr/share/enigma2/skin.xml" is also needed.
This commit combines these 2 xml files and puts the code inside the "/usr/share/enigma2/skin_default/skin.xml", which is what is loaded by skin.py.
Putting the code directly inside "/usr/share/enigma2/skin_default/skin.xml" is way simpler and less prone to (future) errors than having them as "includes" in it.

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
Doesn't the makefile within the skin_default folder need updating to include skin.xml too?

**Comment by nautilus7** [comment]
There is already a skin.xml in there which is also present in the makefile.am

https://github.com/OpenPLi/enigma2/blob/develop/data/skin_default/Makefile.am#L55

**Comment by nautilus7** [comment]
Your confusion proves my point that the current layout (code) is too complicated...

**Comment by AbuBaniaz** [comment]
The idea is to make every skin self-contained including the the emergency skin, which you have so nicely done. On OE-A, the skin is shared among distros. Not all have the the new skin code so cannot be done yet.

**Comment by littlesat** [comment]
Merge?

**Comment by AbuBaniaz** [comment]
Yes please.

**Comment by IanSav** [comment]
I wasn't able to do this combination on the other images as the emergency skin is shared between images.  As OpenPLi has its own, private, emergency skin this should be fine.  In fact the original skin.xml and skin_default.xml in /usr/share/enigma2 can now be deleted!

**Comment by nautilus7** [comment]
I see. Aren't they deleted with my commit or I missing something?

**Comment by IanSav** [comment]
At the time I posted I hadn't looked.  My OpenPLi machine is dead so I have to boot OpenPLi on my OpenViX development machine from time to time to check out changes.

**Pull request merged**
