### PR TITLE
[frontend] correct SNR value for AVL6211(hd51/vs1500)

### PR DESCRIPTION
**Pull request by Dima73**
-we will remove it when the drivers are fixed

### CODE REVIEW

**Comment by littlesat** [comment]
We should wait for the drivers to be fixed is my suggestion... When we merge this then there is no motivation for the manufacturer to fix it as we already worked-around it...

**Comment by Dima73** [comment]
ok,wait.
But how much should we wait?

**Comment by littlesat** [comment]
When the manufacturer does not fix it forever... 
Did OE-A/OpenATV worked around that?

**Comment by Dima73** [comment]
I did not see(OE-A/OpenATV).

**Comment by HD-Digital** [comment]
The AVL6211 gives now the "real" SNR value. This means it's not manipulate anymore that value is always between 80 till 100%. Can you please explain why this new value should been wrong.

**Comment by Dima73** [comment]
example:
vs1500
dB 13.3-13.5
SNR 68%

Really(Formuler1/old driver et8500/dual tuner Vuplus DVB-S NIM(AVL6222) solo4k)
dB 13.2
SNR 88%

**Comment by Dima73** [comment]
example:
vs1500
dB 12.0
SNR 60%

Really
dB 10.8
SNR 67%

**Pull request closed without merging**
