### PR TITLE
keyboard.xml - translate OPTION buton to HELP for Gigablue

### PR DESCRIPTION
**Pull request by ims21**
- temporary - it should be solved in driver with manufacturer

### CODE REVIEW

**Comment by littlesat** [comment]
Is this if gigablue then do something else thing really needed?

**Comment by littlesat** [comment]
I mean do we really need if device is gigablue?

**Comment by ims21** [comment]
I don't care. I want not to have it in userfile keytranslate.xml, where they added it and what was reverted by WanWizard fortunately (because it replaced user file)

GB has not Help button on RC, afaik.

**Comment by littlesat** [comment]
Other boxes have that other key... then just add it....

**Comment by ims21** [comment]
lets manufacturer change code "option button" to "help button" in driver for e2

**Comment by ims21** [comment]
> 
> 
> Other boxes have that other key... then just add it....

I do not understand ...

**Comment by littlesat** [comment]
Just remove the part that checks for the GB remote controll....

**Pull request merged**
