### PR TITLE
[Ci] add option "Relevant PIDs routing"

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by littlesat** [comment]
Please explain what this is.
And again there are more changes the. Described... Yes -> yes for example...

**Comment by littlesat** [comment]
And why the open close on the proc, with the try except while you can check the file exists... and why the hasattr is suddenly needed for the highspeed?

**Comment by Dima73** [comment]
config.cimisc.dvbCiDelay  is global option.
It must be initialized only once.
Before it is done 4 times.
Now it is used hasattr.

**Comment by littlesat** [comment]
Is this for the latest vu changes?

**Comment by Dima73** [comment]
Yes

**Comment by littlesat** [comment]
See my comments on the forum

**Comment by Dima73** [comment]
We need another patch.

**Comment by littlesat** [comment]
Please keep it open so we don't forget it....

**Comment by littlesat** [comment]
Merged but with a new patch....

**Pull request closed without merging**
