### PR TITLE
[nimListCompressed] not visible only FBC link tuners

### PR DESCRIPTION
**Pull request by Dima73**
Discussion here
https://forums.openpli.org/topic/16424-some-questions-bugs/?view=findpost&p=739111

### CODE REVIEW

**Comment by littlesat** [comment]
Please do not merge. We first need to investigate Why this one box makes the mistake with that dvb-t tuner. We should not revert something when it is driver related... or it can be fixed

**Comment by littlesat** [comment]
Looks like a driverbug... or at least the internally connectable chec should be solved

**Comment by littlesat** [comment]
In addition when we solve it like this because one box made a mistake we have to remove a few other lines...

**Comment by Dima73** [comment]
Why can not we see the tuner internally connectable?
Who and why did this decide for everyone?

**Comment by littlesat** [comment]
A driver issue Actually did... Please verify first Why it indicated conectable

**Comment by littlesat** [comment]
Why closing it and do not try to get it right.... :(

Can you give me the following info of that box...
"/proc/bus/nim_sockets"
and
ls -R /proc/stb/frontend

Just to verify/investigate what is going-on on that box/tuner.... probably we could find a real solution....

**Pull request closed without merging**
