### PR TITLE
[HDMI-CEC] plugin - set default enabled as off

### PR DESCRIPTION
**Pull request by Dima73**
-this plugin is not for normal users

### CODE REVIEW

**Comment by Taykun345** [comment]
I agree. I for example want this off, as I use Logitech remote.

**Comment by littlesat** [comment]
I suggest we should left it ON.... the way it is now is fine....

**Comment by ims21** [comment]
"I agree. I for example want this off, as I use Logitech remote" 

 ... good argument ...   omg

**Comment by Taykun345** [comment]
Yeah, not a good argument :D

**Comment by WanWizard** [comment]
We agreed the default should be "off". ;-)

**Pull request merged**
