### PR TITLE
PEP8 all .py files with PEP8.sh

### PR DESCRIPTION
**Pull request by persianpros**
Information: https://github.com/OpenPLi/enigma2/pull/2917

This is how .py look after running PEP8.sh once and safe to merge/use for devs/end-users.

Please normal merge this PR not squash merge as we need to see the changes separately.

### CODE REVIEW

**Comment by persianpros** [comment]
@WanWizard 

If you check ATV and OE-A repos you see my commits about this matter.

I hope PLi accept this so I could send PEP8 and other cleanups to all of your repos as well :+1:

**Comment by littlesat** [comment]
@persianpros
Can you also offer a merge request to OpenVix... so we all can stay somehow in sync?

**Comment by persianpros** [comment]
@littlesat 

Of course! I did it for ATV and I will do it for all ViX repos, you have my word.

**Comment by littlesat** [comment]
Please also note that such a big merge request will break keeping communities in sync... better for a next time to discuss this first on fora before making merge requests.... (where e.g. I have the feeling OpenATV easily accepts requests and here at OpenPLi we think more than twice about thinks, add arguments before 'blindly' accept something).

**Comment by persianpros** [comment]
No ATV won't accept PRs easily, my PEP8 comits proved to be 100% safe that's why all my PRs accepted on all OE-A, ATV and Open WebIF.

For the sync problem I offer my help to all your repos and ViX so we could all benefit at the final results that once for all we PEP8 all the repos.

**Comment by persianpros** [comment]
@littlesat 

Done, I sent the needed PRs for ViX and also new PRs for PLi's repos.

**Comment by littlesat** [comment]
Based on this information

One of Guido’s key insights is that code is read much more often than it is written. The guidelines provided here are intended to improve the readability of code and make it consistent across the wide spectrum of Python code. As PEP 20 says, “Readability counts”.

A style guide is about consistency. Consistency with this style guide is important. Consistency within a project is more important. Consistency within one module or function is the most important.

However, know when to be inconsistent—sometimes style guide recommendations just aren't applicable. When in doubt, use your best judgment. Look at other examples and decide what looks best. And don’t hesitate to ask!

**_In particular: do not break backwards compatibility just to comply with this PEP!_**

SOURCE: (on top) https://pep8.org/#a-foolish-consistency-is-the-hobgoblin-of-little-minds

We may consider not to adapt this 'big' merge request....

**Comment by persianpros** [comment]
Up to you but if you do we would have some kind of standard across the enigma2 scene and you will be part of it.

We want to bring stable and good things from OV and ATV to PLi or vice versa, don't you think it's better if we all follow the safe codes?

As it won't change spaces to tabs or tabs to spaces it just make all repos like each other, easier to read, easier to cherry-pick and easier to work on and this is happening for the first time I think so please be supportive about this change and see the better future.

Also other PRs for PLi:

https://github.com/OpenPLi/enigma2-pliplugins/pull/12

https://github.com/OpenPLi/tuxtxt/pull/7

https://github.com/OpenPLi/enigma2-plugin-systemplugins-quadpip/pull/8

https://github.com/OpenPLi/servicemp3/pull/18

https://github.com/OpenPLi/enigma2-plugins/pull/656

https://github.com/OpenPLi/enigma2-plugin-extensions-epgimport/pull/52

https://github.com/OpenPLi/openpli-oe-core/pull/951

**Comment by original-birdman** [comment]
> Up to you but if you do we would have some kind of standard across the enigma2 scene and you will be part of it.

I thought there already was a sort-of standard across current enigma2 code.
It seems that you are trying to change it to a *different* one.

**Comment by original-birdman** [comment]
A request:

Could you please send a parallel pull to:
https://github.com/OpenViX/enigma2/commits/Dev-python3-compatible

Otherwise this PR would leave us out of sync.

**Comment by persianpros** [comment]
@original-birdman 

The only agreement is using tabs instead of spaces, in some repos devs used PEP8 like Open WebIF (but not in all py files) and in some there is no sign of PEP8.

We use PEP8 for long and recently OE-A and ATV joined to use PEP8 in all repos, this is a good good thing that is happening to have common style.

As requested: https://github.com/OpenViX/enigma2/pull/670

**Comment by persianpros** [comment]
Now OE guys are merging my PRs: https://github.com/openembedded/meta-openembedded/commits/master

**Pull request merged**
