### PR TITLE
[Menu] Rename Service searching

### PR DESCRIPTION
**Pull request by AbuBaniaz**
The current name does not mention anything about tuners. Tuners and scanning covers both terms

### CODE REVIEW

**Comment by WanWizard** [comment]
I fully agree with renaming it. 

But does that require a HTML entity for the ampersand? Maybe it is/looks better if you just use "and" instead?

**Comment by AbuBaniaz** [comment]
Needs the HTML entity, otherwise won't load. I used `&` instead of `and` to keep length shorter. I can change it to `and` if you prefer.  However, ViX has new name, pull request submitted to ATV.

**Comment by WanWizard** [comment]
Ok, clear.

**Comment by AbuBaniaz** [comment]
Thanks for merging.

**Pull request merged**
