### PR TITLE
[MovieSelectionFileManagerList] 1) Corrected 'text' into 'description…

### PR DESCRIPTION
**Pull request by RobvanderDoes**
…'; 2) More clear help text (now that 'green' does the same as 'menu').

### CODE REVIEW

**Comment by nautilus7** [comment]
It's the first time I see a button with a "Do" label. And I don't mean in enigma2, but in general...!!!

Come on guys... a "Do" button???

**Comment by RobvanderDoes** [comment]
Well, let me know if you have a better suggestion?
Having an OK-button (on the remote) and an OK-button on the GUI (green) with different functionality, you do need to change the label to something meaningful.
And 'Do' is (as native English speakers told me).

**Comment by nautilus7** [comment]
Maybe "Select" ??? Maybe "Go" ???

**Comment by RobvanderDoes** [comment]
No: 'Select' is what the OK-button does.
The green-button now does 'do' (same functionality as 'menu').

**Comment by nautilus7** [comment]
Sorry, I haven't check the screen in my box or the code. I just proposed a few alternatives I thought they are good.

What are the available "operations" that you can do with Green or Menu button then?

EDIT: I see it can "Move to" or "Copy to" the selected file, right?

**Comment by RobvanderDoes** [comment]
One gets a choicebox in which one can select either 'move' or 'copy'.
And hopefully later on also 'delete' and 'save as 'playlist'.
Trust me: native English speakers think 'Do' is the best label for this button.
Or better: trust them....
And of course in any translation you can say whatever suits you best for your language.

**Comment by nautilus7** [comment]
I don't say "Do" is bad in general. It's just not common in buttons. Whatever....

What about changing this `self["key_blue"] = Button(_("Inversion"))` to "**Invert**" ? This way, there will be "Cancel, Do, Sort, Invert. **All verbs!**

**Comment by ims21** [comment]
DO NOT ADD NONSENCE, IF YOU DO NOT KNOW ANYTHING ABOUT IT !!!

Do not change texts, id you do not know nothing about it ...

There is select with OK and then via MENU is selected operation (or with Ok). But priority is via MENU !!!!!!!!!!

If you want change it, change it as "Select files with 'OK' and then use '**Menu**' or 'Green' to select operation

Next time, I'd rather lie in bed than add something :-(

**Comment by RobvanderDoes** [comment]
No need to shout. Just doing my best to save you some time.

**Comment by RobvanderDoes** [comment]
Very last time I created a pullrequest for PLi, thanks very much.
And 'green' (as added by Littlesat") is indeed far more intuitive and ergonomic then menu (but the label 'OK' is not).

BTW: 'Invert' is indeed better then 'Inversion'.

**Comment by ims21** [comment]
Sorry my emotions ... (partialy due rebuild my whole oe build directory for 7 boxes... ) . I created fix yet.

**Comment by ims21** [comment]
'Invert' or 'Inversion', both is true.
'Inversion' as noun, 'invert' as verb

**Pull request closed without merging**
