### PR TITLE
[ActionMap] sanity check when contexts not list

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by Taapat** [comment]
If this is really necessary, then maybe it would be better:
`if contexts and not isinstance(contexts, list):`
Then anything that is not a list, not just a string, would be converted to a list.

**Comment by Dima73** [comment]
#>>> contexts=None
>>> isinstance(contexts, list)
False
>>> contexts = [contexts]
>>> contexts
[None]#
 this not good

**Comment by littlesat** [comment]
Why is this sanity check needed?

**Comment by Dima73** [comment]
E.g. 
[ActionMap] Keymap(s) 'I, n, f, o, b, a, r, V, m, o, d, e, B, u, t, t, o, n, A, c, t, i, o, n, s' -> Undefined action(s) 'vmodeSelection'.


Same as HelpableActionMap
https://github.com/OpenPLi/enigma2/blob/2bc264b922cb3c73a87e94ab1385bb465491888b/lib/python/Components/ActionMap.py#L103

**Comment by ims21** [comment]
If there will be  'I, n, f, o, b, a, r, V, m, o, d, e, B, u, t, t, o, n, A, c, t, i, o, n, s', then it is wrong conversion in code to py3 and then will be much better, when in this case will be enigma crashing, imho

**Comment by Dima73** [comment]
> If there will be 'I, n, f, o, b, a, r, V, m, o, d, e, B, u, t, t, o, n, A, c, t, i, o, n, s', then it is wrong conversion in code to py3 and then will be much better, when in this case will be enigma crashing, imho

ok, I agree

**Pull request closed without merging**
