### PR TITLE
FlashImage - fixed typo

### PR DESCRIPTION
**Pull request by ims21**

### CODE REVIEW

**Comment by nautilus7** [comment]
Maybe @WanWizard prefers to do an amend commit to keep the git history clean. Anyway, what ever you like.

**Comment by WanWizard** [comment]
Sorry for the typo.

You can't do an amend of a commit that is already pushed public, that would rewrite history and create problems for people that have already pulled it.

**Comment by nautilus7** [comment]
True, but git experts can overcome them.

**Comment by WanWizard** [comment]
I'm not expecting everyone is... :grin:

**Pull request merged**
