### PR TITLE
[VideoEnhancement] update plugin

### PR DESCRIPTION
**Pull request by Dima73**
-add new options "Scaler vertical dejagging"/"Smooth"
-add  description setting

source code openATV team

### CODE REVIEW

**Comment by littlesat** [comment]
Please maken onelines from writing do the procs...

**Comment by athoik** [comment]
@Dima73

```
-					open("/proc/stb/vmpeg/0/pep_hue", "w").write("%0.8X" % myval)
+					open("/proc/stb/vmpeg/0/pep_hue", "w").write("%0.8X\n" % myval)
```

Is new line also required? Maybe remove those as well?

**Comment by Dima73** [comment]
https://github.com/openatv/enigma2/commit/688eb51569114ce74f787b85cf72300ba09ce804#diff-404d41541210aa14f7e464cfda515834

???

**Comment by athoik** [comment]
It says `try to fix possible color errors` and as far as I know, the new line is not required when writing to proc entries.

**Pull request merged**
