### PR TITLE
Update menu.xml

### PR DESCRIPTION
**Pull request by badsystem**

### CODE REVIEW

**Comment by WanWizard** [comment]
Why is this needed? Aren't these options not added to the menu automatically when the plugin is installed?

**Comment by badsystem** [comment]
This is required to display the icon in main-setup, as in the main-menu. 
[https://www.mediafire.com/view/4w2u8yxhjet4f5r/%25D0%2591%25D0%25B5%25D0%25B7_%25D0%25BD%25D0%25B0%25D0%25B7%25D0%25B2%25D0%25B8-2.png/file](url)
[https://www.mediafire.com/file/hr3tpgvksia2hko/809.jpg/file](url)

**Comment by badsystem** [comment]
This is required to display the icon in main-setup, as in the main-menu.
[https://www.mediafire.com/view/4w2u8yxhjet4f5r/%25D0%2591%25D0%25B5%25D0%25B7_%25D0%25BD%25D0%25B0%25D0%25B7%25D0%25B2%25D0%25B8-2.png/file](https://github.com/OpenPLi/enigma2/pull/url)
[https://www.mediafire.com/file/hr3tpgvksia2hko/809.jpg/file](https://github.com/OpenPLi/enigma2/pull/url)

**Comment by badsystem** [comment]
I'm sorry. Instead of deleting the message, I deleted the pull request

**Pull request closed without merging**
