### PR TITLE
[Dish] show icon if tuner for current sattelite use motorized mode

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by littlesat** [comment]
This one should be in rc

**Comment by Dima73** [comment]
Please add this yourself.
I do not use this branch.

**Comment by WanWizard** [comment]
You can create the PR against the rc branch instead of the develop branch?

**Comment by Dima73** [comment]
No I can not.
On my local github use only develop branch.

**Comment by eriksl** [comment]
That's something you can do something about.

But in this case I will help you out and cherry pick it into rc.

**Pull request closed without merging**
