### PR TITLE
[sec.cpp] Unicable: don't output debug during timer simulation

### PR DESCRIPTION
**Pull request by Huevos**

### CODE REVIEW

**Comment by littlesat** [comment]
Cannot be merged

**Comment by Huevos** [comment]
What is the problem with this commit?

Unicable is the only type outputted during simulation. All other LNB types have suppressed simulation.

**Comment by athoik** [comment]
I'll check it, the simulate variable is not defined on some context.

**Comment by Huevos** [comment]
Not sure but I was using it in my ViX git. Littlesat said it would not merge.

**Comment by athoik** [comment]
No, the CI build failed, check logs on Travis CI.

**Comment by athoik** [comment]
In prepareTurnOffSatCR there is no simulate variable. That's why CI build failed.

**Pull request closed without merging**
