### PR TITLE
osmio4k: support multiboot and online flashing

### PR DESCRIPTION
**Pull request by athoik**
osmio4k uses by default mmcblk1 but FlashImage and Multiboot has
hardcoded values to mmcblk0.

Add the mmc devide used by machine to SystemInfo canMultiboot tuple.
Also add True/False to canMultiboot tuple, once true it will copy
the startup slot, like Gigablue does.

### CODE REVIEW

**Comment by athoik** [comment]
> Then line 6 I have doubts... I think we should avoid the +'p' and use "%s%s" % (...., 'p') instead.

Should be fixed via  e2f4cf4

**Comment by eriksl** [comment]
I also think this is better suited for develop.

**Comment by littlesat** [comment]
“%sp” you even make it better!

**Comment by littlesat** [comment]
Sorry I can not merge this as the merge request is agains RC... Please offer a new merge request on Develop.

**Pull request merged**
