### PR TITLE
Convert "TimerEntry" class buttons to new style

### PR DESCRIPTION
**Pull request by nautilus7**
I tested it and it works ok. I renamed "OK" to "Save", as it better describes the creation or edit action on a timer.

### CODE REVIEW

**Comment by littlesat** [comment]
It also needs some changes to the skin..
Cancelok templates can be temoved

**Comment by RobvanderDoes** [comment]
But for backwards compatibility reasons you can leave the old name in as well as the new name.

**Comment by littlesat** [comment]
Sorry I did not merge this one as I do not understand the need....

**Comment by nautilus7** [comment]
Why? The need is similar to this: https://github.com/OpenPLi/enigma2/commit/2a7abe5d9df27b3b23815771dbc4977e06f0001d#diff-85d20ea518b17e47e87a1fb6ac80d56cL34

You changed "ok" and"cancel" button names to "key_red" and "key_green". 
I also changed Label() to staticText(), to be consistent with the rest of the buttons in that file.

**Pull request merged**
