### PR TITLE
Added .vscode folder to .gitignore

### PR DESCRIPTION
**Pull request by nautilus7**
For those who develop using the Visual Studio Code.

### CODE REVIEW

**Comment by WanWizard** [comment]
Visual what? ;-)

**Comment by nautilus7** [comment]
Don't you know it? It's the open source code editor from Microsoft and one of the best ones.

https://code.visualstudio.com
https://github.com/microsoft/vscode

This editor (and I guess every code editor), creates a folder that stores some configuration files for the project (enigma2 in this case), so in order to make life easier it would be nice if this folder is ignored by git.

**Comment by WanWizard** [comment]
Microsoft has seen the light? Wonders aren't out of the world yet... ;-)
No, I haven't, I haven't written any C in over 30 years.

**Comment by nautilus7** [comment]
@WanWizard, since you didn't merge this...

Can you explain how a programmer is supposed to setup his development environment to write python or C++ for enigma2?

How is syntax highlighting, code auto completion, etc, (which make a programmer's life easier) are supposed to work inside a code editor (any code editing application), without the editor saving some files somewhere?

So, why these editor files need to be visible as repository changes in git? And why is it so bad to add a single line in .gitignore?

**Comment by WanWizard** [comment]
Eh? I did? Just didn't know what it was, which is why I asked.

**Comment by nautilus7** [comment]
Yes, and I posted the links about vscode. But then the PR was closed by you.

**Comment by WanWizard** [comment]
Chips, sorry, I see it, wrong button. Sorry, it's been a long day...

**Comment by nautilus7** [comment]
No problem, I understand.

**Pull request merged**
