### PR TITLE
MovieSelection/MovieContextMenu: add new option "Auto play blu-ray file"

### PR DESCRIPTION
**Pull request by Dima73**
-select folder BDMV --> press menu and set this opton
play *.m2ts ( large size)
-add spaces for better readability

### CODE REVIEW

**Comment by milosoftware** [comment]
Please always create separate commits for "cosmetic-only" changes.

**Comment by milosoftware** [comment]
Try integrating this with the standard can_/do_ functions that the movielist provides. This allows the function to be bound to a function key, and reduces the amount of code. Or integrate it like the DVD playback and make this the default action on BR images.

**Comment by Dima73** [comment]
Sorry, but what you do not like that option?

**Comment by milosoftware** [comment]
Make a separate commit that contains only the whitespace changes.

The functionality is fine, it would just be better to fully integrate it, so that pressing "OK" on a BR folder will play the movie, just like what happens for DVD folders.

**Pull request closed without merging**
