### PR TITLE
[RecordTimer] create directory  /media/hdd/movie if it doesn't exist

### PR DESCRIPTION
**Pull request by Dima73**
Attention!
Let's discuss this proposal first.

### CODE REVIEW

**Comment by WanWizard** [comment]
What is the reasoning for this, as this has been removed a few years ago.

I have my NAS mounted on /media/hdd, and record in the root of that mount, I don't want nor need a "movie" directory.

**Comment by Dima73** [comment]
> 
> 
> What is the reasoning for this, as this has been removed a few years ago.
> 
> I have my NAS mounted on /media/hdd, and record in the root of that mount, I don't want nor need a "movie" directory.

I recently installed a new disk and the movie folder had to be created manually.
Even if you do not use this folder, how does it get in the way?

**Comment by WanWizard** [comment]
If the directory is there, it will be used automatically. So that means a directory I don't use is created, AND I need to manually change the default location for recordings to /media/hdd, otherwise they get into the wrong place.

Another option: create it only if /media/hdd is a mointpoint for a local block device, AND it is empty ?

**Comment by Dima73** [comment]
> 
> 

> 
> Another option: create it only if /media/hdd is a mointpoint for a local block device, AND it is empty ?

I don't know how to check it.

**Pull request closed without merging**
