### PR TITLE
fixed regression for bcm7401 based receivers as the kernel won't report mips on them

### PR DESCRIPTION
**Pull request by lprot**

### CODE REVIEW

**Comment by littlesat** [comment]
There is more than one change in this merge request

**Comment by lprot** [comment]
Previous two are already merged.

**Comment by eriksl** [comment]
It's irrelevant, we don't have machines using bcm7401 in our portfolio.

**Comment by lprot** [comment]
dm800, dm800se don't know about others, but before arm worked ok there

**Comment by littlesat** [comment]
We do not support these dmm boxes anymore so still not relevant...

**Comment by lprot** [comment]
well, the more akward way will be to patch the kernel on them :)

**Comment by eriksl** [comment]
> dm800, dm800se don't know about others, but before arm worked ok there
Wrong, dm800se = bcm7405. So only dm800 left and we stopped supporting that one in OpenPLi 2.1...

**Comment by lprot** [comment]
Hmm, right
```
root@dm800se:/# uname -a
Linux dm800se 3.2-dm800se #1 SMP Sat Sep 28 00:31:25 UTC 2013 mips GNU/Linux
```

**Pull request closed without merging**
