### PR TITLE
Testscreens - added 'Pixels' screen with color test screens

### PR DESCRIPTION
**Pull request by ims21**

### CODE REVIEW

**Comment by ims21** [comment]
For me it is more comfortable for user. User must not thinking about buttons.
All colors are cyclically switched with left (r,g,b,w,bk,c,m,y) or right(y,m,c,bk,w,b,g,r) and in addition, r,g,b is used for red, green, blue color too (except yellow - it is not basic color).

**Comment by littlesat** [comment]
I think it is better you toggle RGB with the color buttons... and of course use left right...

**Comment by ims21** [comment]
And what is there used ?!

**Comment by littlesat** [comment]
Can be improved later so I merge...

**Pull request merged**
