### PR TITLE
[NumericalTextInput.py] Update language tables

### PR DESCRIPTION
**Pull request by IanSav**
- Add Persian
- Update Czech as requested by Ims
- Update Finnish, German, Polish, Russian, Slovak, Spanish, Swedish, Ukrainian as per ETSI, EU 202 130
- Update Latvian as requested by Taapat

### CODE REVIEW

**Comment by blzr** [comment]
Polish layout is wrong - see https://forums.openpli.org/topic/60472-language-assistance-requested/?view=findpost&p=931395

**Comment by IanSav** [comment]
Did you read the code or test it out.  That data displayed on the screen is a result of calculations and not just the data in any single table.

Please actually test the code and report back.

**Comment by blzr** [comment]
well, reading the code was enough for me to find that wrong characters (ã, é, ë, ò, ô, ù) have been added to Polish layout, but if you insist on hard proofs, see: https://photos.google.com/share/AF1QipOUmpqLtGrtiW880lg7n7P3tz7ALohPyijT9cIOShCsCe9KWlmZORqZHMFdK7LVzw/photo/AF1QipMTC6g3W_SOSo6F05nR0lIB31QsEbQ_Kmk-Pqtx?key=bzhaOFdwMlB3b2hubWxqRXVnX21JUEpHemx1R0xn

**Comment by IanSav** [comment]
If any corrections are required for Polish then please post them in the forum.

It appears that I should not have put my trust in the ETSI, EU 202 130 reference document.  :(

**Pull request merged**
