### PR TITLE
	fixed reporting gstreamer version:   About.py

### PR DESCRIPTION
**Pull request by lprot**
made Now and Next translatable:   Converter/EventName.py

### CODE REVIEW

**Comment by WanWizard** [comment]
The only remark I have is that these are two unrelated commits into a single PR, which makes cherry-picking and reverting complexer. So please don't mix unrelated commits.

**Comment by ims21** [comment]
Btw - where is untranslated Next/Now ?

**Comment by lprot** [comment]
Yes it is. Just cherry pick and fix those two bugs guys. I don't mind closing this PR.

**Comment by Taapat** [comment]
I also have not seen that Now/Next would not be translated.
Where exactly does not work?

Maybe you do not use openpli components to display epg information?

**Comment by lprot** [comment]
In PLi-HD skin on homebuild images.

**Comment by ims21** [comment]
I do not see in PLi-HD not translated Now/Next still. All is translated.

**Comment by lprot** [comment]
I don't know why but I encountered that two times. Maybe homebuild somehow uses non-openpli component as Taapat said but I just using standard skin-PLiHD from littlesat's github. No problem I will patch EventName.py on every build it's just annoying :(

**Comment by ims21** [comment]
I am using homebuild on my all boxes and using PLi skins only and all I is translated... => problem is somewhere on your side...

I do not see here your box, language, screenshot with not translated text...

**Comment by Taapat** [comment]
I do not see any problem in my Latvian in your mentioned secondinfobar on skin-PLiHD:
screenshot

**Comment by Taapat** [comment]
You do not need a patch EventName.py on every build.
You need to find the reason why pgettext translation does not work for you.
And then you need to fix this, not to add translation to an already translated word.

**Comment by lprot** [comment]
Well my stb is dm800hd pvr. And I suppose it's because python 2.7.13 of it doesn't localize the strings in pgettext, About language it is russian/ukrainian and untranslated strings are the same ones that Taapat underlined in red on his screenshot.

**Comment by ims21** [comment]
Python in PLi is 2.7.13.

**Comment by ims21** [comment]
dm800hd pvr is not supported very long time and it worked under oe3 or oe4 ?

Btw - you can use your own patches for build ...  there in your ~/oe/meta-local/ create path:

~/oe/meta-local/recipes-local/enigma2/enigma2/
in ~/oe/meta-local/recipes-local/enigma2/ create file enigma2.bbappend with:

`
FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"

SRC_URI += " file://0001-my-patch1.patch"
SRC_URI += " file://0001-my-patch2.patch"
SRC_URI += " file://0001-my-patch3.patch"
`

and this patches put into:
~/oe/meta-local/recipes-local/enigma2/enigma2/

**Comment by lprot** [comment]
These are the converters I got on the image:
```
-rw-r--r-- 1 root root  4272 кві 25 15:21 ClientsStreaming.pyo
-rw-r--r-- 1 root root  3521 кві 25 15:21 ClockToText.pyo
-rw-r--r-- 1 root root   967 кві 25 15:21 Combine.pyo
-rw-r--r-- 1 root root  3003 кві 25 15:21 ConditionalShowHide.pyo
-rw-r--r-- 1 root root  2061 кві 25 15:21 ConfigEntryTest.pyo
-rw-r--r-- 1 root root  1071 кві 25 15:21 Converter.pyo
-rw-r--r-- 1 root root  1573 кві 25 15:21 CryptoInfo.pyo
-rw-r--r-- 1 root root  4585 кві 26 22:38 EventName.pyo
-rw-r--r-- 1 root root  2761 кві 25 15:21 EventTime.pyo
-rw-r--r-- 1 root root  4408 кві 25 15:21 FrontendInfo.pyo
-rw-r--r-- 1 root root  4467 кві 25 15:21 genre.pyo
-rw-r--r-- 1 root root   143 кві 25 15:21 __init__.pyo
-rw-r--r-- 1 root root  1692 кві 25 15:21 MenuEntryCompare.pyo
-rw-r--r-- 1 root root  2618 кві 25 15:21 MovieInfo.pyo
-rw-r--r-- 1 root root  4893 бер  6 01:14 MSNWeather.py
-rw-r--r-- 1 root root  4652 бер  6 01:18 MSNWeather.pyo
-rw-r--r-- 1 root root 14232 кві 25 15:21 PliExtraInfo.pyo
-rw-r--r-- 1 root root  2258 кві 25 15:21 Poll.pyo
-rw-r--r-- 1 root root  1173 кві 25 15:21 ProgressToText.pyo
-rw-r--r-- 1 root root  2402 кві 25 15:21 RdsInfo.pyo
-rw-r--r-- 1 root root  2137 кві 25 15:21 RemainingToText.pyo
-rw-r--r-- 1 root root  3811 кві 25 15:21 RotorPosition.pyo
-rw-r--r-- 1 root root  1086 кві 25 15:21 SensorToText.pyo
-rw-r--r-- 1 root root  7994 кві 25 15:21 ServiceInfo.pyo
-rw-r--r-- 1 root root  2620 кві 25 15:21 ServiceName.pyo
-rw-r--r-- 1 root root  2539 кві 25 15:21 ServiceOrbitalPosition.pyo
-rw-r--r-- 1 root root  4929 кві 25 15:21 ServicePosition.pyo
-rw-r--r-- 1 root root  1625 кві 25 15:21 ServiceTime.pyo
-rw-r--r-- 1 root root  1078 кві 25 15:21 StaticMultiList.pyo
-rw-r--r-- 1 root root   681 кві 25 15:21 StaticText.pyo
-rw-r--r-- 1 root root  1190 кві 25 15:21 Streaming.pyo
-rw-r--r-- 1 root root  2798 кві 25 15:21 StringList.pyo
-rw-r--r-- 1 root root  1618 кві 25 15:21 StringListSelection.pyo
-rw-r--r-- 1 root root  2970 кві 25 15:21 TemplatedMultiContent.pyo
-rw-r--r-- 1 root root  1233 кві 25 15:21 TextCase.pyo
-rw-r--r-- 1 root root  3538 кві 25 15:21 TransponderInfo.pyo
-rw-r--r-- 1 root root  1966 кві 25 15:21 TunerInfo.pyo
-rw-r--r-- 1 root root   985 кві 25 15:21 ValueBitTest.pyo
-rw-r--r-- 1 root root  1173 кві 25 15:21 ValueRange.pyo
-rw-r--r-- 1 root root  2065 кві 25 15:21 ValueToPixmap.pyo
-rw-r--r-- 1 root root  2692 кві 25 15:21 VfdDisplay.pyo
```

**Comment by pieterg** [comment]
I agree with WanWizard's comment.
Your gstreamer fix is good, I'd like to merge it.
It should have been a separate commit (and separate pull request, preferably, so the two different commits could be pulled independently)

**Comment by lprot** [comment]
Ok, done gstreamer ver detection in separate PR. But I have no clue why pgettext doesn't localize the strings. In /usr/lib/python2.7/gettext.pyo I see following definition:
```
def pgettext(self, context, message):
        if self._fallback:
            return self._fallback.pgettext(context, message)
        return message
```
and:
```
def pgettext(self, context, message):
        ctxt_msg_id = self.CONTEXT % (context, message)
        missing = object()
        tmsg = self._catalog.get(ctxt_msg_id, missing)
        if tmsg is missing:
            if self._fallback:
                return self._fallback.pgettext(context, message)
            return message
        if self._output_charset:
            return tmsg.encode(self._output_charset)
        if self._charset:
            return tmsg.encode(self._charset)
        return tmsg
```
and:
```
def pgettext(context, message):
    return dpgettext(_current_domain, context, message)
```
and:
```
def dpgettext(domain, context, message):
    try:
        t = translation(domain, _localedirs.get(domain, None), codeset=_localecodesets.get(domain))
    except IOError:
        return message

    return t.pgettext(context, message)
```
Is anything wrong with this?

**Comment by Taapat** [comment]
Have you always get not translated Now/Next, or only in some cases?
If always, do you use the original translation from the enigma?

**Comment by lprot** [comment]
enigma2.po are ok. But pgettext fails on all screens always.

**Comment by Taapat** [comment]
I've just checked the Russian and Ukrainian languages, and I have no problem with the Now/Next translation in secondinfobar on develop.
As ims21 wrote- problem is somewhere on your side...

**Comment by lprot** [comment]
Ops. I've found the cause. Indeed I wasn't using original translation file. mo file was missing strings with:
```
msgctxt "now/next: 'now' event label"
msgid "Now"
```
Sorry for raising this.

**Pull request closed without merging**
