### PR TITLE
Remove superfluous usage of "skin_default/" in image paths

### PR DESCRIPTION
**Pull request by IanSav**
UPDATED!

I believe this pull request is ready to merge for wider testing.

This pull request has been created for review by OpenPLi developers.  My initial testing is complete.  All tests that had issues have been addressed with additional commits in this pull request.

OpenPLi developers may have other questions or observations that may be triggered by reviewing these proposed changes.  If so, please discuss any problems before reverting the changes.

NOTE: This pull request has a partner pull request for the skins: https://github.com/littlesat/skin-PLiHD/pull/799

### CODE REVIEW

**Comment by IanSav** [comment]
I have completed my initial testing and I am very happy with the results.

There are some issues with which I would like some assistance.  The following images are used by the base code but there is no image in the skin_default directories.  I think they have always been missing.  Can anyone point me to, or provide these missing images for skin_default:

- ./lib/python/Plugins/Extensions/PicturePlayer/ui.py:
    - pic_frame = resolveFilename(SCOPE_CURRENT_SKIN, "skin_default/icons/pic_frame.png")
- ./lib/python/Plugins/Extensions/GraphMultiEPG/GraphMultiEpg.py:
    - self.nowEvPix = loadPNG(resolveFilename(SCOPE_CURRENT_SKIN, 'epg/CurrentEvent.png'))
    - self.othEvPix = loadPNG(resolveFilename(SCOPE_CURRENT_SKIN, 'epg/OtherEvent.png'))
    - self.selEvPix = loadPNG(resolveFilename(SCOPE_CURRENT_SKIN, 'epg/SelectedEvent.png'))
    - self.recEvPix = loadPNG(resolveFilename(SCOPE_CURRENT_SKIN, 'epg/RecordingEvent.png'))
    - self.curSerPix = loadPNG(resolveFilename(SCOPE_CURRENT_SKIN, 'epg/CurrentService.png'))

EDIT: Images have been found to satisfy these missing images.

**Comment by littlesat** [comment]
Ready to merge?

**Comment by AbuBaniaz** [comment]
Yes, both pull request are ready to merge

**Comment by IanSav** [comment]
I have run tests on both pull requests (code and skins) and detected no issues.

I would like to see both pull requests merged and put under more strenuous testing.  If there are any issues alert me to them and I will attend to them immediately.  If they are simply skin cosmetic issues then it would be appropriate to ask the skin designers to assist.

**Pull request merged**
