### PR TITLE
Add option enable/disable conflict detection for each timer

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by littlesat** [comment]
Please do not make changes to the current general timer conflict detection and remove all checks for the fallback tuner.... T

**Comment by eriksl** [comment]
I think littlesat means: don't use the fallback tuner setting (on/off) for assumptions with timers. I agree, we talked about that. Lets discuss on the forum.

**Comment by Dima73** [comment]
<Please do not make changes to the current general timer conflict detection>
if only small rename text "Enable timer conflict detection"-->"Enable global timer conflict detection"

<remove all checks for the fallback tuner>
If it is not turned on "Enable fallback remote receiver", then I do not understand the meaning of the others changed.
The basis of all - use of a fallback tuner

**Comment by littlesat** [comment]
I want to remove the general setting.... And go for your individual one only and then without a fallback tuner is availalble check....

**Comment by Dima73** [comment]
ок

**Pull request closed without merging**
