### PR TITLE
Fastscan - added FreeSAT SK, FocuSat and UPC Direct on Thor 0.8W

### PR DESCRIPTION
**Pull request by ims21**
pls, to 7.1 then too

### CODE REVIEW

**Comment by WanWizard** [comment]
I am getting merge conflicts in the 7.1 branch, due to other changes in develop: https://github.com/ims21/enigma2/commits/47fde7ed762ffe48c9ee9c0c66bfb68e299bb073/lib/python/Plugins/SystemPlugins/FastScan/plugin.py

I assume your other one can go in too, what about IanSav's change? We have to make sure that doesn't break the release build.

**Comment by ims21** [comment]
Where you got merge conflicts ? It is merged to develop well. Could I create this last 3 fastscan's PRs for 7.1 ?

**Comment by ims21** [comment]
But there must be merged previous patche (21.7.) for python's FreeSat as first - without it be conflict, because there in 7.1 not exist added line in this first patche from 21.7.
And must be meger fix for cpp (FastScan - fix west position - 21.7. too). 
That's all.

**Comment by WanWizard** [comment]
That is what I asked, I can not judge if the other commits (yours and IanSav's) can be merged without side effects.

**Comment by ims21** [comment]
Who decides that exists in fixed fastscan side effect ? Nobody will test it , imho. 
I am working with it and have no problem. And parameters for next 3 fastscan's providers I got from official sources.

**Comment by WanWizard** [comment]
I wasn't talking about your changes, but about IanSav's commit, which is related to a ton of other commits. Ideally I don't want to merge that one. Can I just remove it from the merge conflict, and only merge your two commits?

**Comment by ims21** [comment]
If you want, I have prepared this same 3 PRs for Fastscan (one fix + 2 enhancement) against 7.1 ... tell me and I will push it to queue for enigma2 7.1.

**Comment by WanWizard** [comment]
Already figured out how to properly pick them, must be the heat. ;-)

Jjust pushed the changes to 7.1-release.

**Comment by ims21** [comment]
Thanks. Would be possible for once run build 7.1 earlier than next monday?

**Comment by WanWizard** [comment]
Build is running.

**Pull request merged**
