### PR TITLE
enigma2: control debug level using tmp file

### PR DESCRIPTION
**Pull request by athoik**
Store next debug level on /tmp/enigma_debug_lvl and once gui is respawn "source" the file to get the ENIGMA_DEBUG_LVL.

This makes enigma2 main loop in script not required any more. The inittab will handle the respawn of gui as we used to.

### CODE REVIEW

**Comment by littlesat** [comment]
We don’t wanna do it that way... please hold on! I also do not want to continously write a file with tie, but let e2 also create a log when you have a spinner and on demand.

**Comment by athoik** [comment]
En-light me how do you want to do it then?

**Comment by littlesat** [comment]
We’re still discussing... First at least the loop should stay. I think exit it when debug_lvl <= 4.... and no tie... but something else instead....

**Comment by athoik** [comment]
Control the debug level from UI? 
Change the debug level in real time without restarting?
Use syslog?

**Comment by littlesat** [comment]
Control the debug level from UI? -> When it can be done?
But also write a 'spinner log' when we have a spinner and/or write a log on demand....!

Then this whole thing can be reverted

**Comment by littlesat** [comment]
Wanwizard did solve this and also improved the UI.

**Pull request closed without merging**
