### PR TITLE
[Converter/ServiceInfo] clear all old video value if new service start

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by littlesat** [comment]
Do we need to clear for vu+ or is this idea beyond vu+?

**Comment by Dima73** [comment]
for all box 
+ 
same wrong info in screen ServiceInfo

**Comment by Taapat** [comment]
If it necessary evStart then evVideoSizeChanged does not work correctly.
If it is really necessary for all receivers maybe need to correct video size changed event in enigma?

**Comment by Dima73** [comment]
no vu+
this wrong info from last service

**Comment by Dima73** [comment]
If start new channel, but there is no picture then remains data of the previous channel

**Comment by WanWizard** [comment]
Agreed. If you zap from a channel you can watch to a channel you don't, all info in the infobar still refers to the previous channel.

**Pull request merged**
