### PR TITLE
[MultibootSelection] move to index (preselect the current slot)

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by littlesat** [comment]
Why should this be an advantage?

**Comment by Dima73** [comment]
Place the cursor on the current image.
Why not.

**Comment by Dima73** [comment]
Place the cursor on the current image.
Why not.

**Comment by littlesat** [comment]
Because I think there is an easier way to do it. And it is not completed as it does not cover the modes.

**Comment by littlesat** [comment]
E.G. modes sorting it does not work in that.....

**Comment by littlesat** [comment]
I will commit an alternative

**Pull request closed without merging**
