### PR TITLE
[SleepTimerEdit] add new option 'Power off timer'

### PR DESCRIPTION
**Pull request by Dima73**
-Select the days of the week to turn off
-Next day starts at (time)
-Force power off (even when not in standby)
-exceptionsExternalTools for exception time plugins, .e.g.
from Components.PowerOffTimer import exceptionsExternalTools
exceptionsExternalTools.append(("EPGRefresh", epgrefresh.isRunning))

### CODE REVIEW

**Comment by littlesat** [comment]
Why do we need a poweroff timer???

We have already turn ON per day and the poweroff is auto (on activity).... I suggest this does not help at all...

**Comment by Dima73** [comment]
This advanced functionality,
e.g. used as a server at certain times.
Start time 8:00 / end time 23:00

I think this option will appeal to many users.
I checked everything works fine, no errors noticed.

**Comment by RobvanderDoes** [comment]
So IMHO it would be better to enhance the built-in functionality.

**Comment by littlesat** [comment]
I do not ink many users will use this... So when we have a plugin I suggest leave it there... Whar a weird idea having a server on limited times.....

**Comment by Dima73** [comment]
You decide for everyone.
Very sorry.

**Comment by RobvanderDoes** [comment]
It's not a weird idea; it's a very good idea to power off devices that are not needed. In most households an STB/server/NAS/Amp/TV/PC/Laptop is only being used for a couple of hours per day. Letting the all work will cost an enormous amount of power per year. And that's exactly the reason that more and more people turn off devices (sometimes even by a complete power cut). So any device that could be automated to be on at times they are most likely to be used, and off at other times, will enhance proper use by people.

**Comment by Dima73** [comment]
Yes, to save power.
In the world and so the resource crisis.

**Comment by littlesat** [comment]
To save power we have already the activity timer and time to block this activity timer... That is why I do not understand a hard power down is needed....

**Comment by Dima73** [comment]
I agree.
You can of course use the inactivity timer for this purpose.
But this is a direct option and it will find its user.

**Comment by Dima73** [comment]
First step wake up timer.
Next step power off timer.
In my opinion it is logical.

**Comment by RobvanderDoes** [comment]
Yep.
That's why many images have it that way.

**Pull request closed without merging**
