### PR TITLE
[Pager] various fixes

### PR DESCRIPTION
**Pull request by Huevos**
Various commits. Please don't squash.

Fixes for Pager.

Remove redundant code.

Fix Makefiles and configure.ac.

### CODE REVIEW

**Comment by Huevos** [comment]
There is a build error with this in PLi. i.e. warnings treated as errors. Will try to fix.

**Comment by Taapat** [comment]
I'm not sure, but maybe you should pay attention to this: https://github.com/OpenPLi/enigma2/actions/runs/4392133687/jobs/7691715249#step:8:2422

**Comment by Huevos** [comment]
I've closed this and opened a new one. Let's see if that builds ok.
https://github.com/OpenPLi/enigma2/pull/3645

**Comment by Huevos** [comment]
Yes just a case of the compiler being fussy. Works now with this change:
https://github.com/OpenPLi/enigma2/pull/3645/commits/d714a16893f4ce6e2ef2a43ccdb1c2a2a41fcade

**Pull request merged**
