### PR TITLE
[RecordTimer] Add new option 'Event Name First" for recording filenames.

### PR DESCRIPTION
**Pull request by Huevos**
Adds a fourth type of filename composition. standard, long, short, then "Event Name First"
so recorded filenames do not have the date as the filename prefix.

Credit: AndyBlac
https://github.com/OpenViX/enigma2/commit/5ec78dfb9dec22dbdca8734662f7623c1037aa80

### CODE REVIEW

**Comment by littlesat** [comment]
Why should we need this? What is the big advantage?

**Comment by WanWizard** [comment]
I can see a use-case, if you record the same event from different channels (I do that quite a lot for series), and you are not using the GUI to access the files (I move them to series folders on my NAS). With a name starting with event, it is easier to sort and select.

**Comment by AbuBaniaz** [comment]
The fourth format will be as pictured.
filename composition

You will only see the change if you **choose** to use the option and inspect the recording folder. The issue has been mentioned a few times on PLi forum.
To me, people record "events", so this should be the prominent/first thing you read on the filename. The date and service on which it was recorded are important, but not more important.

**Comment by littlesat** [comment]
It is another setting and even with the current format the name from the program is in it. Somyou can still "order" and "filter" on it. I think it does not have a real added value. I think even short and long could be removed.
But from the other side it does not really harm as long there are no plugins that are pasing this stuff

**Comment by WanWizard** [comment]
It is not about the event name being "in it", it is about the event name being "at the start". Without it, you need programme experience or special tools to be able to do something smart with them.

So, thanks for merging. ;-)

**Pull request merged**
