### PR TITLE
[fastscan] skip transponders if satelite position is '0'

### PR DESCRIPTION
**Pull request by Dima73**
more info:

https://forums.openpli.org/topic/97184-unable-to-delete-the-00e-services-created-by-fastscan/

### CODE REVIEW

**Comment by littlesat** [comment]
When does this happen? And why?

**Comment by Dima73** [comment]
If the provider gives fictitious data, the orbital position is zero, a zero satellite appears that cannot be deleted.
This patch solves the problem.

**Comment by littlesat** [comment]
What provider is doing this.... this should not be an openpli issue in general? Then the provider sends an incorrect channel list (and this means this is a work a round for someone else's failure) or there might be another reason behind it.

**Comment by Dima73** [comment]
provider TéléSAT
read this https://forums.openpli.org/topic/97184-unable-to-delete-the-00e-services-created-by-fastscan/?view=findpost&p=1592824

**Comment by littlesat** [comment]
Why didn't you add it to the description then I did not need to ask it a reference to the tread from months ago was also helpful

**Pull request merged**
