### PR TITLE
Add ipaddress.py you need it OpenWebif

### PR DESCRIPTION
**Pull request by chipcard**

### CODE REVIEW

**Comment by athoik** [comment]
This is not part of python-ipaddress package?

**Comment by chipcard** [comment]
Hi is not part of it.

**Comment by athoik** [comment]
Are you sure?

Please check once again...

**Comment by littlesat** [comment]
When OWIF needs it I think OWIF should arrange that it is included in their package or as dependancy

**Comment by arn354** [comment]
root@box1:/var/lib/opkg/info# cat python-ipaddress.list
/usr/lib/python2.7/site-packages/ipaddress.pyo
/usr/lib/python2.7/site-packages/ipaddress-1.0.18-py2.7.egg-info/
/usr/lib/python2.7/site-packages/ipaddress.py
/usr/lib/python2.7/site-packages/ipaddress-1.0.18-py2.7.egg-info/dependency_links.txt
/usr/lib/python2.7/site-packages/ipaddress-1.0.18-py2.7.egg-info/SOURCES.txt
/usr/lib/python2.7/site-packages/ipaddress-1.0.18-py2.7.egg-info/PKG-INFO
/usr/lib/python2.7/site-packages/ipaddress-1.0.18-py2.7.egg-info/top_level.txt
root@box1:/var/lib/opkg/info#

**Pull request closed without merging**
