### PR TITLE
EventView - avoid crash using KEY_INFO

### PR DESCRIPTION
**Pull request by fairbird**
EventViewBase.__init__(self, Event, Ref, callback, similarEPGCB, parent)
TypeError: EventViewBase__init__() takes at most 5 arguments (6 given)

re-commit previous commit to correct commit info - working tree must have been dirty...

Thank's teamblue
https://github.com/teamblue-e2/enigma2/commit/b8c71d7fcbe1fb7c6d57ca6bde75c0f72bad33b2#diff-0b2df61f72a741cfb67a38e78da24ec5

### CODE REVIEW

**Comment by ims21** [comment]
I do not know, where you are hunting this, but under PLi no GSOD in EventView with Key_INFO ...

**Comment by fairbird** [comment]
Try to install this plugin
https://sites.google.com/site/kashmirplugins/enigma2-plugin-extensions-translator_1.1rc1_all.ipk?attredirects=0
If you  installed .. you will get that crash in Epg features with KEY_INFO...

**Comment by ims21** [comment]
then fix plugin and not change enigma ...

**Comment by fairbird** [comment]
Ok..
I will ask author of plugin ..
Thank you

**Comment by RobvanderDoes** [comment]
> then fix plugin and not change enigma ...

+1!

**Pull request closed without merging**
