### PR TITLE
[estring] remove character ';' in line 71, a string is truncated with…

### PR DESCRIPTION
**Pull request by Dima73**
…out an invalid character at the end of line

More info:
https://github.com/openatv/enigma2/issues/1681
-use tab instead space

### CODE REVIEW

**Comment by athoik** [comment]
Code "assumes" ;)

There might be better "truncate" functions available: 

https://stackoverflow.com/questions/35328529/stdstring-optimal-way-to-truncate-utf-8-at-safe-place
https://stackoverflow.com/questions/30995246/substring-of-a-stdstring-in-utf-8-c11

I find the one written on C++ 14 (on first post) much more readable, with an huge explanation what the code does.

**Comment by Dima73** [comment]
**athoik** 
Please make the correct patch.

**Comment by littlesat** [comment]
Can we merge this one or not!

**Comment by Dima73** [comment]
I think everything is in order here.
Let's apply and check.
test:
`Original string: Футбол. Чемпионат Европы-2021. Молодёжные сборные. Отборочный турнир.
Truncated string: Футбол. Чемпионат Европы-2021. Молодёжные сборные. ОтборЊ <--- Invalid character
truncateUTF8=100
Truncated string v2: Футбол. Чемпионат Европы-2021. Молодёжные сборные.
truncateUTF8v2=88`

**Pull request closed without merging**
