### PR TITLE
[HdmiCecSetupScreen] Clean-up and optimization

### PR DESCRIPTION
**Pull request by nautilus7**
* Put all imports on top and sort them alphabetically.
* Allow for individual skinning, while keeping existing fallback to "Setup" skin.
* Use parent class functions for saving and closing. Less code plus the user is now asked to exit without saving changes.
* Use parent class mechanisms for updating the config list and description. Again, less code written.
* Renamed green button text from "OK" to "Save" to be consistent with other setup screens.
* Other small cleanups and enhancements.

### CODE REVIEW

**Comment by nautilus7** [comment]
Everything seem to work as expected regarding my changes, but @littlesat @IanSav @Huevos @WanWizard @athoik can have a look just to be sure...

Another change I am thinking of is to convert this plugin to a screen. hdmi-cec is considered standard functionality today, so there's no point to keep it as a plugin. Should I offer a patch for this as well?

**Comment by WanWizard** [comment]
Sounds like a plan, yes!

**Comment by Huevos** [comment]
@nautilus7, have a look at OpenViX version. Much simpler. 60 lines of code not 125.

https://github.com/OpenViX/enigma2/blob/Dev/lib/python/Plugins/SystemPlugins/HdmiCEC/plugin.py

**Comment by nautilus7** [comment]
@Huevos thanks for the heads up! I can't do it this way in openpli, because your "Setup" class is on steroids to read xml files from plugins, plus it allows conditional creation of config entries. There are about 50 commits from @IanSav and you in this direction during the past year, which openpli unfortunately lacks. These changes in the "Setup" class can help a lot to simplify the code of many setup-like screens around enigma2. I don't know why they are not in openpli too.

**Comment by nautilus7** [comment]
> 60 lines of code not 125.

I dropped from 160 to 125 and could go to 110 if converted to screen instead of a plugin, without changing anything else in enigma2. But yes, further reduction in this and many other similar classes is possible with your distro.

**Pull request closed without merging**
