### PR TITLE
[SystemInfo] "CommonInterface" zgemmah9combo/pulse4kmini use only 1 slot

### PR DESCRIPTION
**Pull request by Dima73**
-drivers --> bug answer two ci slot

### CODE REVIEW

**Comment by Marchella1983** [comment]
Thank you! It works but with this edit
` SystemInfo["CommonInterface"] = model in ("zgemmah9combo", "h10", "pulse4kmini") and 1 or eDVBCIInterfaces.getInstance().getNumOfSlots()`

on OpenPli for  Zgemma H9 Combo you need to see how it outputs
`cat  /proc/stb/info/model `

**Comment by Dima73** [comment]
> Thank you! It works but with this edit ` SystemInfo["CommonInterface"] = model in ("zgemmah9combo", "h10", "pulse4kmini") and 1 or eDVBCIInterfaces.getInstance().getNumOfSlots()`
> 
> on OpenPli for Zgemma H9 Combo you need to see how it outputs `cat /proc/stb/info/model `
> 
> 

Please answer cat /proc/stb/info/model
zgemma H10 and zgemma H9 combo

**Comment by Marchella1983** [comment]
```
h10 login: root
root@h10:~# cat /proc/stb/info/model
h10
```

**Comment by Dima73** [comment]
[Add more box in SystemInfo["CommonInterface"]](https://github.com/OpenPLi/enigma2/pull/3259)

**Pull request merged**
