### PR TITLE
FlashImage - Downloaded images will add downloaded homebuild images too

### PR DESCRIPTION
**Pull request by ims21**
BSP generating homebuild images as '...-model_'

### CODE REVIEW

**Comment by littlesat** [comment]
I prefer not to merge this one sorry...

**Comment by WanWizard** [comment]
What do you suggest homebuild users do instead?

**Comment by WanWizard** [comment]
To be clear, this is what the build produces:
````
./alphatriplehd/openpli-develop-alphatriplehd_usb.zip
./dual/openpli-develop-dual_multiboot_ofgwrite.zip
./dual/openpli-develop-dual_usb.zip
./et10000/openpli-develop-et10000_usb.zip
./et1x000/openpli-enigma2-develop-et1x000_usb.zip
./et4x00/openpli-develop-et4x00_usb.zip
./et5x00/openpli-develop-et5x00_usb.zip
./et6x00/openpli-develop-et6x00_usb.zip
./et7000mini/openpli-develop-et7000mini_usb.zip
./et7x00/openpli-develop-et7x00_usb.zip
./et8000/openpli-develop-et8000_usb.zip
./et8500/openpli-develop-et8500_usb.zip
./et9x00/openpli-develop-et9x00_usb.zip
./formuler1/openpli-develop-formuler1_usb.zip
./formuler3/openpli-develop-formuler3_usb.zip
./formuler4/openpli-develop-formuler4_usb.zip
./formuler4turbo/openpli-develop-formuler4turbo_usb.zip
./fusionhd/openpli-enigma2-develop-fusionhd_usb.zip
./fusionhdse/openpli-enigma2-develop-fusionhdse_usb.zip
./galaxy4k/openpli-enigma2-develop-galaxy4k_usb.zip
./gbquad4k/openpli-enigma2-develop-gbquad4k_usb.zip
./gbtrio4k/openpli-develop-gbtrio4k_multiboot_ofgwrite.zip
./gbtrio4k/openpli-develop-gbtrio4k_usb.zip
./gbue4k/openpli-enigma2-develop-gbue4k_usb.zip
./h10/openpli-develop-h10_emmc.zip
./h10/openpli-develop-h10_full_recovery_emmc.zip
./h10/openpli-develop-h10_recovery_emmc.zip
./h11/openpli-develop-h11_emmc.zip
./h11/openpli-develop-h11_full_recovery_emmc.zip
./h11/openpli-develop-h11_recovery_emmc.zip
./h3/openpli-develop-h3_usb.zip
./h4/openpli-develop-h4_usb.zip
./h5/openpli-develop-h5_usb.zip
./h6/openpli-develop-h6_usb.zip
./h7/openpli-develop-h7_multiboot_ofgwrite.zip
./h7/openpli-develop-h7_usb.zip
./h8/openpli-develop-h8_nand.zip
./h8/openpli-develop-h8_usb.zip
./h9combo/openpli-develop-h9combo_emmc.zip
./h9combo/openpli-develop-h9combo_full_recovery_emmc.zip
./h9combo/openpli-develop-h9combo_recovery_emmc.zip
./h9combose/openpli-develop-h9combose_emmc.zip
./h9combose/openpli-develop-h9combose_full_recovery_emmc.zip
./h9combose/openpli-develop-h9combose_recovery_emmc.zip
./h9/openpli-develop-h9_usb.zip
./h9se/openpli-develop-h9se_emmc.zip
./h9se/openpli-develop-h9se_full_recovery_emmc.zip
./h9se/openpli-develop-h9se_recovery_emmc.zip
./hd1100/openpli-develop-hd1100_usb.zip
./hd11/openpli-develop-hd11_usb.zip
./hd1200/openpli-develop-hd1200_usb.zip
./hd1265/openpli-develop-hd1265_usb.zip
./hd1500/openpli-develop-hd1500_usb.zip
./hd2400/openpli-develop-hd2400_usb.zip
./hd500c/openpli-develop-hd500c_usb.zip
./hd51/openpli-develop-hd51_multiboot_ofgwrite.zip
./hd51/openpli-develop-hd51_usb.zip
./hd530c/openpli-develop-hd530c_usb.zip
./hd60/openpli-develop-hd60_emmc.zip
./hd60/openpli-develop-hd60_recovery_emmc.zip
./hd66se/openpli-develop-hd66se_emmc.zip
./hd66se/openpli-develop-hd66se_recovery_emmc.zip
./i55/openpli-develop-i55_usb.zip
./i55plus/openpli-develop-i55plus_usb.zip
./i55se/openpli-develop-i55se_emmc.zip
./i55se/openpli-develop-i55se_full_recovery_emmc.zip
./i55se/openpli-develop-i55se_recovery_emmc.zip
./lc/openpli-develop-lc_usb.zip
./lunix3-4k/openpli-enigma2-develop-lunix3-4k_usb.zip
./lunix4k/openpli-enigma2-develop-lunix4k_usb.zip
./lunix/openpli-enigma2-develop-lunix_usb.zip
./mbmicro/openpli-develop-mbmicro_usb.zip
./mbmicrov2/openpli-develop-mbmicrov2_usb.zip
./mbtwinplus/openpli-develop-mbtwinplus_usb.zip
./multibox/openpli-develop-multibox_emmc.zip
./multibox/openpli-develop-multibox_recovery_emmc.zip
./multiboxse/openpli-develop-multiboxse_emmc.zip
./multiboxse/openpli-develop-multiboxse_recovery_emmc.zip
./osmega/openpli-develop-osmega_usb.zip
./osmini4k/openpli-develop-osmini4k_multiboot_ofgwrite.zip
./osmini4k/openpli-develop-osmini4k_usb.zip
./osmini/openpli-develop-osmini_usb.zip
./osminiplus/openpli-develop-osminiplus_usb.zip
./osmio4k/openpli-develop-osmio4k_multiboot_ofgwrite.zip
./osmio4k/openpli-develop-osmio4k_usb.zip
./osmio4kplus/openpli-develop-osmio4kplus_multiboot_ofgwrite.zip
./osmio4kplus/openpli-develop-osmio4kplus_usb.zip
./osnino/openpli-develop-osnino_usb.zip
./osninoplus/openpli-develop-osninoplus_usb.zip
./osninopro/openpli-develop-osninopro_usb.zip
./pulse4kmini/openpli-develop-pulse4kmini_emmc.zip
./pulse4kmini/openpli-develop-pulse4kmini_recovery_emmc.zip
./pulse4k/openpli-develop-pulse4k_emmc.zip
./pulse4k/openpli-develop-pulse4k_recovery_emmc.zip
./purehd/openpli-enigma2-develop-purehd_usb.zip
./purehdse/openpli-enigma2-develop-purehdse_usb.zip
./revo4k/openpli-enigma2-develop-revo4k_usb.zip
./sf8008m/openpli-develop-sf8008m_multiboot_ofgwrite.zip
./sf8008m/openpli-develop-sf8008m_usb.zip
./sf8008/openpli-develop-sf8008_multiboot_ofgwrite.zip
./sf8008/openpli-develop-sf8008_usb.zip
./sfx6008/openpli-develop-sfx6008_multiboot_ofgwrite.zip
./sfx6008/openpli-develop-sfx6008_usb.zip
./sh1/openpli-develop-sh1_usb.zip
./spycatmini/openpli-develop-spycatmini_usb.zip
./spycatminiplus/openpli-develop-spycatminiplus_usb.zip
./spycat/openpli-develop-spycat_usb.zip
./sx88v2/openpli-develop-sx88v2_multiboot_ofgwrite.zip
./sx88v2/openpli-develop-sx88v2_usb.zip
./ustym4kpro/openpli-develop-ustym4kpro_multiboot_ofgwrite.zip
./ustym4kpro/openpli-develop-ustym4kpro_usb.zip
./ustym4ks2ottx/openpli-develop-ustym4ks2ottx_multiboot_ofgwrite.zip
./ustym4ks2ottx/openpli-develop-ustym4ks2ottx_usb.zip
./vipercombohdd/openpli-develop-vipercombohdd_usb.zip
./vipercombo/openpli-develop-vipercombo_usb.zip
./viperslim/openpli-develop-viperslim_usb.zip
./vipert2c/openpli-develop-vipert2c_usb.zip
./vs1000/openpli-develop-vs1000_usb.zip
./vs1500/openpli-develop-vs1500_multiboot_ofgwrite.zip
./vs1500/openpli-develop-vs1500_usb.zip
./vuduo2/openpli-develop-vuduo2_usb.zip
./vuduo4k/openpli-develop-vuduo4k_usb.zip
./vuduo4kse/openpli-develop-vuduo4kse_usb.zip
./vuduo/openpli-develop-vuduo_usb.zip
./vusolo2/openpli-develop-vusolo2_usb.zip
./vusolo4k/openpli-develop-vusolo4k_usb.zip
./vusolo/openpli-develop-vusolo_usb.zip
./vusolose/openpli-develop-vusolose_usb.zip
./vuultimo4k/openpli-develop-vuultimo4k_usb.zip
./vuultimo/openpli-develop-vuultimo_usb.zip
./vuuno4k/openpli-develop-vuuno4k_usb.zip
./vuuno4kse/openpli-develop-vuuno4kse_usb.zip
./vuuno/openpli-develop-vuuno_usb.zip
./vuzero4k/openpli-develop-vuzero4k_usb.zip
./vuzero/openpli-develop-vuzero_usb.zip
./xp1000/openpli-develop-xp1000_usb.zip
./xpeedc/openpli-develop-xpeedc_usb.zip
````

**Comment by littlesat** [comment]
Clear how it comes out of an homebuild. But it looks now like an exception in enigma2 code. Homebuilders could also easily adapt it to the format?

**Comment by WanWizard** [comment]
Fine if that an option. Is it? How do you suggest they do this, as I think that needs documenting in the wiki.

**Comment by littlesat** [comment]
Agree.... but just out of the box is just checking on dash then model without the extra dash not sufficiant so just check on -vuultimo4k as example? Then you cover both without adding an extra check?

**Comment by WanWizard** [comment]
Yes, but that also matches a lot more, including words in which the model is only the start.

For example, `-sf8008m_` is matched by `-sf8008`, which is absolutely not what you want, as that is a different box. The solution proposed by @ims21 rules that out, it matches only the exact model name.

**Comment by ims21** [comment]
What exception is it? Wanwizard mentioned what the homebuild generates (by the way, it also generates in PLi, Wanwizard adding "-date" after compilation). Are you sorry for one additional condition? Sure, I can put test into homebuild, but that doesn't solve it when in PLi I need to reflash the downloaded homebuild (for example, because the network doesn't work in PLi, etc.). Without that, I either have to take USB or fix everything manually, which is time-consuming.

**Comment by littlesat** [comment]
Good point wanwizard!
The exception is that for homebuild it seems you need to adapt the code, while a homebuilder can also adapt it manually or with a small script. Then it is not too much manual work. But I'm not alone here to decide what we do.

**Comment by WanWizard** [comment]
Like @ims21 already mentioned, changing the result of the build either means BSP changes, a full blown webserver with scripting to rename the file requested on the fly, or a fairly complex script (our buildserver script is many hunderds of lines). Plenty of arguments for not wanting to require users to do this.

On the other hand, I haven't seen a single argument why the suggestion in the PR is a problem, other than "you don't like it".

**Comment by ims21** [comment]
It looks like instead of adding one trivial condition (which precisely accepts the created image for all homebuild), I will be creating a script where I'll handle renaming, when yes, when no, when to delete the previous one, etc, for all boxes. ... that's called progress...

**Pull request merged**
