### PR TITLE
[encoding.conf] Updating, cleanup wrong format ..

### PR DESCRIPTION
**Pull request by thawtes**
updated unused and non-essential TP's
add new 42E DigitalPlatfom  ( thanks @tanerkaderli ) 
fixed this issue : https://github.com/openatv/enigma2/issues/1750

### CODE REVIEW

**Comment by blzr** [comment]
And why you deleted all 0.8W and 13.0E transponders entries? Are sure they're all not needed? You've tested this?

**Comment by thawtes** [comment]
> And why you deleted all 0.8W and 13.0E transponders entries? Are sure they're all not needed? You've tested this?

yes i tested all of them one by one, no problem.

**Comment by WanWizard** [comment]
@blzr merge ok?

**Comment by blzr** [comment]
I think so...
It's not that I suggested that this wasn't tested, was just a bit surprised that so many entries are obsolete now, so I'd like to make sure it was not accidental.
Tested myself on 13E for two days, a didn't spot a single problem, and there were many Polish transponders included in previous version, now removed.

**Comment by WanWizard** [comment]
Ok, I'll merge..

**Comment by dervishm** [comment]
New Changes ONID...
41401 1070 ISO8859-9 # Digital Platform 42°E - 12.209 H
42001 1070 ISO8859-9 # Digital Platform 42°E - 12.379 H

**Comment by WanWizard** [comment]
Updated in https://github.com/OpenPLi/enigma2/pull/3503

**Pull request merged**
