### PR TITLE
Added missing uclan ustym keys Magic and Context to hotkeys

### PR DESCRIPTION
**Pull request by ims21**
Weird, that it missed ... may be, add it to release too...

### CODE REVIEW

**Comment by WanWizard** [comment]
And backported to 8.2-release.

**Review by catullus89 — COMMENTED** [review]
Good job. But I also noticed that it misses also the buttons "F4" and the button "Resolution". They are not mapped and cannot map in the 8.2 release I have

**Comment by ims21** [comment]
> 

But oroginal RC for Uclan Ustym 4k Pro has not  F4, Resolution buttons ...

**Comment by orator89** [comment]
Newer versions of the box have F4 also (the F3 is already working) and "Resolution" button
USTYM-4K-PRO-Twin-Enigma2-Oscam-IPTV-Kodi-Netflix-Typ-tunera-DVB-S2
USTYM-4K-PRO-Twin-Enigma2-Oscam-IPTV-Kodi-Netflix

**Comment by ims21** [comment]
then install in telnet 'evtest' (opkg install evtest), stop enigma in telnet with "init 4", then run evtest, choose "0" and try this 2 buttons - you will see text code and number code for this 2 buttons. I need it for add this buttons.  (for run enigma then use 'init 3' )

**Comment by orator89** [comment]
The results:
"RESOLUTION BUTTON":

```
Event: time 1658604182.981963, type 4 (EV_MSC), code 4 (MSC_SCAN), value 5fa28d7
Event: time 1658604182.981963, type 1 (EV_KEY), code 373 (KEY_MODE), value 1
Event: time 1658604182.981963, -------------- SYN_REPORT ------------
Event: time 1658604183.191016, type 1 (EV_KEY), code 373 (KEY_MODE), value 0
Event: time 1658604183.191016, -------------- SYN_REPORT ------------
```

"F4 BUTTON":
```
Event: time 1658604250.771748, type 4 (EV_MSC), code 4 (MSC_SCAN), value 5fa18e7
Event: time 1658604250.771748, type 1 (EV_KEY), code 62 (KEY_F4), value 1
Event: time 1658604250.771748, -------------- SYN_REPORT ------------
Event: time 1658604250.980980, type 1 (EV_KEY), code 62 (KEY_F4), value 0
Event: time 1658604250.980980, -------------- SYN_REPORT ------------
```

**Comment by ims21** [comment]
thx ... [PR](https://github.com/OpenPLi/enigma2/pull/3500) created

**Pull request merged**
