### PR TITLE
ATSC: Add missing support

### PR DESCRIPTION
**Pull request by athoik**
This commit add support for ATSC (Terrestrial and Cable) using devices supported by receiver kernel.

Reading atsc.xml reading/writing lamedb, scanning, piority, recording priority, alternative priority (mapped with DVB-C) and display proper tuner information were implemented.

### CODE REVIEW

**Comment by littlesat** [comment]
I,m just thinking it mit be better to merge this in our next-master branch...

**Comment by athoik** [comment]
This will make review by ATSC users harder since there is no next-master images. Also my/our job will be used by others maybe starting from today and not from us.

**Comment by littlesat** [comment]
We're planning to create next-master hopefully within a few weeks... And due to jess and so I think it is better to push this in next-master

**Comment by athoik** [comment]
Ok to the next-master when ready!

**Pull request closed without merging**
