### PR TITLE
Update unicable.xml

### PR DESCRIPTION
**Pull request by kueken**

### CODE REVIEW

**Comment by kueken** [comment]
Maybe you like it that way?

**Comment by WanWizard** [comment]
Think in your original commit I saw Jultec's with 2 UB's, which means "JPSxx/JRSxx 2 UB" is missing?

**Comment by kueken** [comment]
Yes, but in the forum the request was made not to change Jultec. So I made it back.
I then took care of the syntax error at Kathrein.
greetings

**Comment by persianpros** [comment]
You could use our updated version based on PLi: https://github.com/OpenVisionE2/enigma2-openvision/blob/develop/data/unicable.xml

Simply replace it.

**Comment by WanWizard** [comment]
Also missing the "JPSxx/JRSxx 2 UB" :grin:

**Comment by persianpros** [comment]
@WanWizard 

Where is "JPSxx/JRSxx 2 UB" that you said?

**Comment by WanWizard** [comment]
It was in the original PR.

**Pull request closed without merging**
