### PR TITLE
Add Travis CI build status

### PR DESCRIPTION
**Pull request by persianpros**
Demo: https://github.com/OpenVisionE2/enigma2-openvision/blob/develop/README.md
If you want to use this for your other branches as well, after merge just change "branch=develop" to what you want.

### CODE REVIEW

**Comment by littlesat** [comment]
Please explain...

**Review by nautilus7 — APPROVED** [review]

**Comment by athoik** [comment]
Here one more: [HitCount](http://hits.dwyl.io/openpli/enigma2)

**Comment by athoik** [comment]
[start with why](http://www.openpli.org)

**Comment by athoik** [comment]
[contributors](http://www.openpli.org)
GitHub last commit
GitHub
GitHub code size in bytes

GitHub forks
GitHub followers
GitHub stars

And many more here: https://shields.io/

**Pull request closed without merging**
