### PR TITLE
PictureInPicture: change text No free tuner! --> No free tuner for Pi…

### PR DESCRIPTION
**Pull request by Dima73**
…P service!

e.g. run PiP from the channel list/it more clear

### CODE REVIEW

**Comment by eriksl** [comment]
I don't think it's appropriate, if no tuner is free, that can apply to PiP, but also to recordings.

**Comment by Dima73** [comment]
Why is not appropriate?
It explains exactly why we can not play the service PiP.

**Comment by eriksl** [comment]
It can also show when you try to watch a channel but a recording is active. Or streaming.

**Comment by Dima73** [comment]
This notice, that we can not turn service PiP.
This window PictureInPicture.not live TV.

**Comment by littlesat** [comment]
Closed.... As it does not really got added value and all translaters need to translate it...

**Pull request closed without merging**
