### PR TITLE
[About] not visible str(fp_version).startswith("0")

### PR DESCRIPTION
**Pull request by Dima73**
gbquad4k login: root
root@gbquad4k:~# python
>>> ret = open("/proc/stb/fp/version", "r").read()
>>> ret
'0\n'

### CODE REVIEW

**Comment by littlesat** [comment]
Maybe better use strip() what comes back in the line above and then ensure it is a string also over there and check for "0". Maybe better then do it with startswith().

**Comment by Dima73** [comment]
My version works with both string and number.

**Comment by littlesat** [comment]
It works but with strip() instead of startswith() it works always...

**Comment by littlesat** [comment]
Please use strip to get rid of the extra \n the gigablue returns that is more universal solution

**Pull request closed without merging**
