### PR TITLE
Include sd, fhd, and uhd in picon.py for Release 9.0

### PR DESCRIPTION
**Pull request by AbuBaniaz**

### CODE REVIEW

**Comment by WanWizard** [comment]
@littlesat ok to merge?

**Comment by Huevos** [comment]
I don't get it. The is already a proper fix in the develop branch. If needed in 9.0 branch that should be picked.

**Comment by Huevos** [comment]
https://github.com/OpenPLi/enigma2/commit/7e218348b7046319de779b97fdd5c24c0ea653fb
https://github.com/OpenPLi/enigma2/commit/0ba08af47d54db1e36216ffad2f53d1b522ac3a4

The end code is much simpler.

**Comment by AbuBaniaz** [comment]
I added Littlesat's two commits as they resolve issue 3830. Your commit which is after Littlesat's is about unicode names and not explicitly to do with issue 3830. I'm sure your commit will be added later on.

Now we start the discussion about backports are for bugfixes and not new features. The same reason why the steamrelay code still isn't in 9.0.

**Comment by Huevos** [comment]
And removes the endless "if name" horrible code.

**Comment by littlesat** [comment]
I think it is OK to Merge... but somehow I get a message Merging is Blocked...
Thinks because it is a commit in Release 9.0... merge request should be done in Develop instead!!!

In the commit there is also a typo Releae... we miss an S there ;)

**Comment by WanWizard** [comment]
> Now we start the discussion about backports are for bugfixes and not new features. The same reason why the steamrelay code still isn't in 9.0.

If develop has new features that should be in a release image, it is an indication that a new release is overdue...

**Comment by Huevos** [comment]
> > Now we start the discussion about backports are for bugfixes and not new features. The same reason why the steamrelay code still isn't in 9.0.
> 
> If develop has new features that should be in a release image, it is an indication that a new release is overdue...

Some picons with new 4k and uhd names don't show... Not too important...

Stream relay stuff really is an important missing feature though.

**Comment by littlesat** [comment]
The issue is no new release!!!

**Comment by WanWizard** [comment]
Appearently if I don't take action, nobody does. I tried twice, zero response or feedback.

**Comment by littlesat** [comment]
I cannot merge in Release... please add a new merge request for Develop. Then we can 'port' it back to Release. That is how it should be done. For Release I get "merging is blocked"....

**Comment by AbuBaniaz** [comment]
This is a cherry pick of your two commits already in develop.

**Comment by Huevos** [comment]
I don't understand wasting time on this. It is not a bug fix, but a new feature in a later version. People can either wait for Release 9.1, or switch to Develop, which is undated daily.

And even with the 2 commits the code still won't be in sync with the new version.

**Comment by AbuBaniaz** [comment]
An issue was raised to add a feature for users who are mostly on release. The feature was added in two commits by Littlesat into develop image. The issue was closed a long time after citing it had been added ( yes It is in develop).

This pull request is to add the two commits by Littlesat into release image. Wanwizard asked Littlesat if it is okay to merge them, Littlesat has finally agreed after a long time. But it seems he can't merge his own commits into release 

I hope the PLi team can see through the spiteful/vindictiveness behind the objection.

**Comment by Huevos** [comment]
It is not an objection. It is an  observation. Resources are limited so we should be concentrating on the future.

**Comment by littlesat** [comment]
As far I can see this is not a cherry pick from develop but a kind of stand allone merge request on release. And indeed it is also a feature improvement and not a fix for a bug. The issue is more people who want to stuck on release and want this improvement…
While we are also make no release of the current develop

**Comment by AbuBaniaz** [comment]
It is a merge request into Release 9.0 of two cherry picks of following commits in Developer image:

https://github.com/OpenPLi/enigma2/commit/7e218348b7046319de779b97fdd5c24c0ea653fb1
https://github.com/OpenPLi/enigma2/commit/232a00ae5a5e49674b28537c2a0c57714054c1e7

The commit hashes if you want to cherry pick them yourself are
`7e218348b7046319de779b97fdd5c24c0ea653fb`
`232a00ae5a5e49674b28537c2a0c57714054c1e7`

I branched of 9.0, cherry picked those two commits and submitted a pull request when this issue  https://github.com/OpenPLi/enigma2/issues/3830 was closed You can clearly see those two commits in the branch from which the pull request was sent.

https://github.com/AbuBaniaz/enigma2_openpli/commits/releae-9.0_picon/

**Comment by WanWizard** [comment]
I have no objections, only accounts with write access to a repo can do direct cherry-picks.

The only downside of doing it with a merge is that you may loose original commit information, so it might be better if someone with the correct access cherry picks these two commits.

**Comment by Huevos** [comment]
Like I already said it is not just 2 commits.

**Comment by AbuBaniaz** [comment]
I count two commits. Which other commits are there to fulfill Kiddac's request?

**Comment by AbuBaniaz** [comment]
Instead of trolling, why don't you just say,
 ```
If you are making changes picon.py in Release 9.0 please add my commit too.
https://github.com/OpenPLi/enigma2/commit/0ba08af47d54db1e36216ffad2f53d1b522ac3a4
```
Your commit was 4 months after Littlesat's and is nothing to do with the change request by Kiddac. It makes code better. You should submit it to ATV too.

**Comment by Huevos** [comment]
Why don't you just commit what is there?

**Comment by Huevos** [comment]
Actually don't bother because it is not going to run on a python 2 image.

**Comment by littlesat** [comment]
@WanWizard, can you please close this merge request and/or consider to cherry pick?

**Comment by WanWizard** [comment]
No problem, if someone can provide me with the list of commits to pick, in the correct order?

**Comment by AbuBaniaz** [comment]
Only two commits . Already mentioned above in correct order.

**Comment by WanWizard** [comment]
Ok, done.

**Pull request closed without merging**
