### PR TITLE
About: read image install date using /etc/version

### PR DESCRIPTION
**Pull request by athoik**
This solves install date displayed as 1970 in some machines

### CODE REVIEW

**Comment by littlesat** [comment]
Are you sure this presents the install date..... for my ET10K it goes back to Jul 31  2015 which was never the install date...???

**Comment by littlesat** [comment]
I think we better can go for /etc/installed... but then we also have the risk that the time is unknown when it is created :(.... So somehow we need to write a date with the image in E2 as soon we have the first time a date above 1970...

**Comment by athoik** [comment]
Sure, once there is a date after the date that Enigma created it should create file and use the info from there, else use unknown.

**Comment by littlesat** [comment]
Maybe we just need to search for a file that has a timestamp of the build...

**Comment by littlesat** [comment]
I did some checks over several hardware and debugs for an hour and it seems this commit request is pretty reasonable... Sorry for all the delay!!!

**Pull request merged**
