### PR TITLE
[frontend] add snr calculation Astrometa/os mega

### PR DESCRIPTION
**Pull request by Dima73**
-thanks openATV

### CODE REVIEW

**Comment by mirakels** [comment]
Maybe this is nicer:

```
if m_description in ("Broadcom BCM73XX",
                               "FTS-260 (Montage RS6000)",
                               "Panasonic MN88472",
                               "Panasonic MN88473"
                               ):

```

**Comment by athoik** [comment]
Please do not merge this one is not ok.

We are using DVB API 5, why do we need the wrong calculations from DVB API 3?

**Comment by Dima73** [comment]
1)why DVB API 3 wrong?
2)DVB API 5 calculations really wrong for os mega/sundtek
 can not return a value without checking them 
https://github.com/OpenPLi/enigma2/blob/f544402e58516905b91b65fcb319e719d0c87238/lib/dvb/frontend.cpp#L1184

And please do not say that driver developers are required to give the correct value, because they are making money.

**Comment by athoik** [comment]
Please read here: https://linuxtv.org/downloads/v4l-dvb-apis/uapi/dvb/frontend-stat-properties.html

FE_SCALE_RELATIVE - parameter is a unsigned value, where 0 means 0% and 65535 means 100%.

Explain now what is wrong.

**Comment by Dima73** [comment]
os mega Broadcom BCM73XX  always return 99%
os mega multituner dvb-t type  always return 99%

**Comment by Dima73** [comment]
need add if(!signalquality && !signalqualitydb || signalquality != signalqualitydb)

**Comment by athoik** [comment]
If the driver returns DVB API 5 statistics you will never get into (fallback) DVB API 3.

If the driver returns wrong DVB API 5 statistics, drivers should be fixed, not Enigma2.

So the core you are proposing will never work, because DVB API 5 has preference over DVB API 3.

**Comment by Dima73** [comment]
> 
If the driver returns wrong DVB API 5 statistics, drivers should be fixed, not Enigma2.
> 
Serious?
I want and I can do the correct values himself, now and for all users.
Let us then apply DVB API 3 and values as they are, without workaround.
Then we write requests to manufacturers.
And users can not care, let them see the deceptive values.

This was done with Sundek,thank you very much for that.

**Pull request merged**
