### PR TITLE
[frontend] update default maxdb value in calculateSignalPercentage

### PR DESCRIPTION
**Pull request by Dima73**
-tnanks openViX team

### CODE REVIEW

**Comment by littlesat** [comment]
It is not clear to me why this is needed. The new max levels look far too high. When you make it this way then better introduce a min value instead of increasing the max high value and do not depend on min = 2/3 of max or so….

**Comment by Dima73** [comment]
I noticed a long time ago that the SNR is often 100%, in relation to an incomplete DB, when using a new API.
This applies to many new receivers, especially on HiSilicon.
I think these changes will give a more accurate SNR ratio.
Moreover, this code is used only when there is a DB, but there is no SNR.

That is, the manufacturer can always correct this in the drivers, as he sees fit.

**Comment by littlesat** [comment]
Maybe we should simply show dB only when the api gives dB and no percentage… now we are implementing two ‘estimations’…. SNR in percentage makes actually no sense at all as the dimension is usually always expressed in dB.
The 2/3 factor I do not understand at all….

**Comment by Dima73** [comment]
https://github.com/OpenPLi/enigma2/blob/develop/lib/dvb/frontend.cpp#L1457

**Comment by Dima73** [comment]
/* provide an estimated percentage when drivers lack this info */

**Comment by littlesat** [comment]
This function calculateSignalPercentage...

Mayby better go for the type and directly return a value without going for a max db etc...

**Comment by Dima73** [comment]
The authors(openViX team) has a detailed explanation of the changes, I trust them.
https://github.com/OpenPLi/enigma2/pull/3495/commits/ec6d66fe8fa25530abe1fced2ccbfb357a3c05ae#diff-c9bdd86f4f4fa89ad924eb5b5e5394962c92619d035229fa90fac09b6e2adb38R906

**Comment by WanWizard** [comment]
What is the status of this PR?

**Comment by Dima73** [comment]
Let's put it off for now.

**Pull request closed without merging**
