### PR TITLE
[Satconfig] setup tuners FBCLink  remove all 1.2 diseqc mode

### PR DESCRIPTION
**Pull request by Dima73**
-When FBCRoot not 1.2 diseqc mode tuners FBCLink  not visible
"Additional cable of motorized LNB"

### CODE REVIEW

**Comment by RobvanderDoes** [comment]
I hope this is not going to be merged: it would break my setup.
I use a motor with a (dual) Unicable LNB; this allows me to see/record e.g. BBC1/2/4

**Comment by Dima73** [comment]
This patch only tuners FBC  link(virtual) not FBC root.
What are your settings?
You're using tuners FBC  link(virtual) as 1.2 diseqc mode?

**Comment by RobvanderDoes** [comment]
Root = rotor Unicable scr1
Link = extra cable scr2

**Comment by Dima73** [comment]
Root = rotor Unicable scr1 --> 1.2 diseqc mode
Link = extra cable scr2--> 1.2 diseqc mode?

**Comment by RobvanderDoes** [comment]
If you're saying that with your tweak I can still use my setup, it's fine with me of course.

**Comment by WanWizard** [comment]
It's all Python code, so easy enough to test on your particular setup?

**Comment by RobvanderDoes** [comment]
Harro, you're absolutely right to say so, only atm I can't do that.
Nevertheless: this forced me to look a bit better at the PR and I think it won't harm my setup, and it indeed gets rid of an (under the circumstances) useless setting.

**Pull request merged**
