### PR TITLE
[ConfigList] sanity check use dummyConfigActions

### PR DESCRIPTION
**Pull request by Dima73**
File
"/usr/lib/enigma2/python/Plugins/SystemPlugins/SatipClient/plugin.py", line 387, in DiscoveryStart
  File
"/usr/lib/enigma2/python/Components/ConfigList.py", line 457, in dummyConfigActions
KeyError: 'menuConfigActions'

### CODE REVIEW

**Comment by littlesat** [comment]
How do you trigger this?

**Comment by littlesat** [comment]
OK… I’m afraid this could be better resolved in that plugin.

**Comment by Dima73** [comment]
The problem is not in the plugin, but in the fact that self["menuConfigActions"] and etc is not always initialized at startup, but only under certain conditions. That's why I added an additional check.
`			if "key_menu" not in self and menu_button:
				self["key_menu"] = StaticText(menu_button.get('text', ''))
				self["menuConfigActions"] = HelpableActionMap(self, "ConfigListActions", {`
So,need fullUI=True and "key_menu" not in self and menu_button...

**Comment by Dima73** [comment]
Same as self["charConfigActions"].
Where does this even get initialized?

**Comment by littlesat** [comment]
Put it on the forum needs some investigation
It should be declared/initialized.
The check is as far I see not a solution.

**Comment by Huevos** [comment]
https://forums.openpli.org/topic/98908-setup-code-proposal-and-more/page-14#entry1635297

The plugin cannot be calling `ConfigListScreen.__init__()`.

**Pull request closed without merging**
