### PR TITLE
[Added] Option to disable blinking entierly

### PR DESCRIPTION
**Pull request by DimitarCC**

### CODE REVIEW

**Comment by WanWizard** [comment]
Wouldn't it be more logical to make the default False, so the default is the current behavior?

**Comment by littlesat** [comment]
Years ago we had the discussion not to go for blinking in openPli. I also see a blinking clock when a recording is ongoing that currently is not in a setting, but the config is there

**Comment by littlesat** [comment]
The name of the config is not correct... is says disable_blanking... while it actually does enable_blanking

**Comment by DimitarCC** [comment]
Ahh yes.... OK i will change the name and will propose a PR

**Pull request merged**
