### PR TITLE
About - box uptime to description

### PR DESCRIPTION
**Pull request by ims21**

### CODE REVIEW

**Comment by littlesat** [comment]
Nice idea... but why is this info not added in the about text instead... why at description?

**Comment by ims21** [comment]
Because I think, this info is more about working as about box info - I did not want add it to scrolllabel, where is a lot of informations yet.
And under PIG is so much unused space :-)
My first variant was add it as "About" + "Uptime: .... to Title, but it was ugly. This is more decent...

I have prepared skins ... :-)

**Comment by 68foxboris** [comment]
I add this line AboutText += _("Uptime: ") + about.getBoxUptime() + "\n"
1_0_16_2C1_7_70_1680000_0_0_0_20200618185530

**Comment by ims21** [comment]
Yes, but when are more HDDs, then this next info adding scrollbars and I did not want it - scroll in info ... STUPID...
Under PIG is cca 1/4 free whole screen ...

**Comment by persianpros** [comment]
This is how I did it 2 months ago: https://github.com/OpenVisionE2/enigma2-openvision/commit/7fdb7c95b206fce1a715d737b06dd9b773f36547

**Comment by ims21** [comment]
obrazek

Decent imho ...  but I want not spend full 7 pages in discussion about one screen ;-)

**Comment by WanWizard** [comment]
I think the entire screen should be redesigned, because this looks absolutely weird, that one item on the left. 

I may be a better idea to move the entire Enigma section to the left, and keep the right side for everything hardware / OS related. It will also prevent a scrollbar when you have more tuners, storage devices and network interfaces (an ET10000 with wifi has 3).

**Comment by persianpros** [comment]
In OV it's different, we have more menu sections in About: https://github.com/OpenVisionE2/enigma2-openvision/blob/develop/data/menu.xml#L25~L36

**Comment by ims21** [comment]
> 
> 
> I think the entire screen should be redesigned, because this looks absolutely weird, that one item on the left.
> 
> I may be a better idea to move the entire Enigma section to the left, and keep the right side for everything hardware / OS related. It will also prevent a scrollbar when you have more tuners, storage devices and network interfaces (an ET10000 with wifi has 3).

Agree ... I have more HDDs and why must I then use scrollbar, when I want see IP ? Due It I moved it left, where is free space. And it is not true 'box info', imho

**Comment by ims21** [comment]
I don't care - added it to scrollbar

**Pull request closed without merging**
