### PR TITLE
RCU correct Wizard Picture

### PR DESCRIPTION
**Pull request by miraclebox-git**
One file change:

https://github.com/miraclebox-git/enigma2/commit/5ef9c8f8b0deb50093643329f1bbe06073fdea63

### CODE REVIEW

**Comment by miraclebox-git** [comment]
Just one small change:

https://github.com/miraclebox-git/enigma2/commit/5ef9c8f8b0deb50093643329f1bbe06073fdea63

**Comment by Dima73** [comment]
fix MB Twin+ RCU picture detection, since new driver from april

**Comment by Dima73** [comment]
fix MB Twin+ RCU picture detection, since new driver from april

**Comment by Dima73** [comment]
https://github.com/OpenPLi/enigma2/pull/1035

**Pull request closed without merging**
