### PR TITLE
[Picon] Fix for IPTV with buffering enabled

### PR DESCRIPTION
**Pull request by AbuBaniaz**
See thread here
https://forums.openpli.org/topic/41198-serviceapp-gstplayer-and-exteplayer3/page-41#entry945158

### CODE REVIEW

**Review by athoik — APPROVED** [review]

**Comment by littlesat** [comment]
Now it searches twice... so )when it’s a stream) make it always zero and just search once...

**Comment by AbuBaniaz** [comment]
I don't know how to do that.

**Comment by pr2git** [comment]
In fact just before your proposed change we already test it it is a stream so place your change there, no need to specifically test if the 9th field is not null since this parameter is only relevant for stream, so you suppress a useless if by doing this that way.

**Comment by Ev0-BH** [comment]
Is this more exceptable ?

[code]
	if not pngname and fields[0] != '1':
		#fallback to 1 for IPTV streams and 9th field to 0 when buffering
		fields[0] = '1'
		fields[9] = '0'
		pngname = findPicon('_'.join(fields))
[/code]

**Comment by Ev0-BH** [comment]
What needs to be changed then ?

What Abu posted, works fine.

Remember not all iptv is service 1:0:1, we also have 5002:0:1, 5001:0:1 and 4097:0:1

**Pull request closed without merging**
