### PR TITLE
Proposal for Standardised and Uniform Buttons

### PR DESCRIPTION
**Pull request by IanSav**

### CODE REVIEW

**Comment by persianpros** [comment]
Thanks for the doc :)

**Comment by WanWizard** [comment]
@IanSav we're busy setting up a development platform (running Redmine), any objections to move this to it's wiki when it's online, so all development information can be centralized?

**Comment by persianpros** [comment]
It won't harm if we have a copy of it in doc folder ;)

**Comment by WanWizard** [comment]
The problem with copies is that they tend to diverge and get out of date...

**Comment by IanSav** [comment]
I have no objections to the document being put anywhere where it can be seen and used by code and skin writers.

I would still like the document in the doc directory so it will be forked, cloned and merged to downstream repositories.

**Comment by IanSav** [comment]
Did you guys ever grab my date and time changes from OpenViX or Beyonwiz?  It also has a comprehensive manual for developers and skin authors.

I added the ability for Enigma2 to display dates and times in locally preferred formats.  I integrated the code into the  ClockToText converter and anywhere in Enigma2 that date or time formats were hard coded.

I allow for International, European or American dates and times.

**Comment by IanSav** [comment]
I am also working on a refactor of the Setup.py and Menu.py menus.  That work will also come with documentation.  :)

**Comment by WanWizard** [comment]
If @littlesat hasn't picked it up, I don't think anyone did. He's our main man in all things Python.

As to setup.py, it would be nice to take OE-A's setup.xml for plugins functionalilty into account, to increase plugin compatibility.

**Comment by RobvanderDoes** [comment]
> Did you guys ever grab my date and time changes from OpenViX 

Maybe Ian would want to make a pullrequest against the development branch of PLi?

For information of PLi: Ian's Date/Time update has brought universal time settings in the GUI (choice between 12/24 hrs clock in several formats). Really worth the effort.

**Comment by IanSav** [comment]
Rob, I would prefer if someone could pick out the changes from OpenViX.  For me to do this will further delay the other changes I am trying to complete.  ;)

(I suggest OpenViX as the source given that the Beyonwiz build is quite different to OpenViX and OpenPLi.)

**Comment by RobvanderDoes** [comment]
> For information of PLi: Ian's Date/Time update has brought universal time settings in the GUI (choice between 12/24 hrs clock in several formats). Really worth the effort.

I forgot to say that, although some skinning is required to use the universal Date/Time code, not-adapted skins will not be affected (but will then not show the new lay-out).


> Rob, I would prefer if someone could pick out the changes from OpenViX. For me to do this will further delay the other changes I am trying to complete. ;)

Not sure who would be capable of doing that.....

**Comment by IanSav** [comment]
What is the usual turn-around time for pull requests to be merged in OpenPLi?

**Comment by WanWizard** [comment]
That depends on what it is. I check daily, but I don't have the expertise to accept and merge everything. For this topic, I'd like to leave it to littlesat.

**Comment by IanSav** [comment]
This is simply a text document with no operational implications.  I didn't think there would be much of an issue.

**Comment by IanSav** [comment]
Hi WanWizard,

> As to setup.py, it would be nice to take OE-A's setup.xml for plugins functionalilty into account, to increase plugin compatibility.

It is probably a bad idea to go off topic to discuss this here.  Can you please contact me via any mechanism you prefer to explain and discuss this request.

Regards,
Ian.

**Comment by persianpros** [comment]
@littlesat Would you please merge this? It's a good thing to have in doc folder.

**Comment by littlesat** [comment]
Nice document but I consider that it is better to add it to our wiki... and mayby consider to add a document here with refferences to our wiki

**Comment by IanSav** [comment]
Is the wiki OpenPLi specific or is it open for all Enigma2 builds?

**Comment by WanWizard** [comment]
The wiki will be/can be made public (it isn't created yet), the Redmine platform is open for anyone with an account on the forum (both share the same auth database).

**Comment by IanSav** [comment]
That is not my point.  Is the wiki intended for OpenPLi developers or will it be equally supporting any and ALL Enigma2 developers for any and all builds?  This question is particularly important for information that has absolutely no relationship to the OpenPLi build.

As I wrote on the forum:

> If the wiki was on the OE-Alliance site then that would be a true Enigma2 resource.  Putting it on an OpenPLi server makes it appear to be an OpenPLi resource.  It is very unlikely that an OpenPLi resource would be accepted as a generic Enigma2 reference.
>
> Putting information in a private wiki is unlikely to have that information flow to other builds.  Knowing that other builds pull from the OpenPLi fork means that if the document goes into the /doc directory, as I requested, then the document WILL flow to all those repositories!

**Comment by IanSav** [comment]
Thank you for the merge.

Feel free to point to the document from the wiki.  I will update the repository if/when anything changes.

**Pull request merged**
