### PR TITLE
Script to update all the po files out of normal build process

### PR DESCRIPTION
**Pull request by pr2git**

### CODE REVIEW

**Comment by WanWizard** [comment]
Shouldn't this clean up all temp files created?

**Comment by pr2git** [comment]
It acts exactly the same as when you update the files with the make process. But if you want it is of course possible to clean up the 2 temporary .pot files and the final enigma2.pot (even if it would be nice to have the enigma2.pot file proposed in your github for people willing to add a new language).

**Comment by pr2git** [comment]
rm added to remove the pot files in the PR.

**Comment by WanWizard** [comment]
Thanks !

This probably needs to happen in the other scripts too?

**Pull request merged**
