### PR TITLE
NimManager.py: add new method "getNimListForSat".

### PR DESCRIPTION
**Pull request by Huevos**
Returns a list of tuners available for the orbital position given as the argument.
e.g. find all the tuners that can tune Astra 1...
nimmanager.getNimListForSat(192)

### CODE REVIEW

**Comment by littlesat** [comment]
What Will use it?

**Comment by Huevos** [comment]
Well nothing at the moment because it wasn't present. So just another tool in the NimManager toolbox. Once present it can be used in enigma or plugins.

**Comment by Huevos** [comment]
E.g. a plugin such as CrossEPG could use this to simplify selecting a tuner list.

**Comment by littlesat** [comment]
Or ABM.

**Comment by Huevos** [comment]
Yes, that too. I think it is easier and cleaner to do this function from inside NimManager where all the variables are available, rather then a messy function inside a plugin.

Thanks for merging.

**Pull request merged**
