### PR TITLE
Add option "Default timer type" when create new timer

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by littlesat** [comment]
Please do not commit... just recoding should be default no real need to a a default setting...

**Comment by Dima73** [comment]
Let's discuss it.
My default option is to Zap so as not to miss the event.

**Comment by littlesat** [comment]
Then better have an option to disable recoding from the recoding menu which change the default to zap. (And add that option also to the setup wizard) and the also block all the recoding options. And/or check for a device having more than x Gig and when that is not there change the default without setting (maybe warning that you can ignore)

**Comment by pr2git** [comment]
No please stop thinking of an automatic way to decide what the default action should be. You won't find any valid solution. So please, let to end user the opportunity to choose what is his favorite default action when setting up a recording. Simple and efficient.

**Comment by Dima73** [comment]
<item level="2 -->it means user level Expert

**Comment by nautilus7** [comment]
What changed and you re-opened this?

btw, expert user level should give more control to the user. Not less, by automating settings.

**Comment by WanWizard** [comment]
It was decided to accept this for now, and do a bit of finetuning later.

**Pull request merged**
