### PR TITLE
Cleanup python files #1

### PR DESCRIPTION
**Pull request by persianpros**

### CODE REVIEW

**Comment by littlesat** [comment]
I'm afraid some of these "cleanups" are not properly tested....

**Comment by littlesat** [comment]
In between you corrigated the recordtimer.py

**Comment by persianpros** [comment]
I think you mean this : https://github.com/OpenPLi/enigma2/pull/662/commits/3adf6ff3d3e214a79c370a50cd9cbc555b3b0412 for "RecordTimer.py" which is fixed now.
I see no more problems in #1 cleanup :)

**Comment by littlesat** [comment]
It is verh difficult to merge this.... As I ophave to merge all of them...

**Comment by persianpros** [comment]
You can compile and test it from https://github.com/OpenE2/enigma2 then merge it

**Pull request closed without merging**
